# Setting TV

In [ ]:
import pandas as pd
from datetime import datetime

# fee
fee = {
    "tax_stock": 0.003,  # 賣出0.003
    "tax_future": 0.00002 * 2,  # 買進與賣出各0.00002
    "fee_stock": 0.001425 * 2,  # 券商手續費公道價，買進與賣出各0.001425
    "fee_future": 0.00002 * 2,  # 各家不大相同，以交易稅計算
    "sliding_price": 0.00001,  # 滑價
}
# tw_index_fee = 0
tw_stock_fee = 0
# tw_stock_fee = fee["tax_stock"] + fee["fee_stock"] + fee["sliding_price"]
tw_index_fee = fee["tax_future"] + fee["fee_future"] + fee["sliding_price"]

# stock list
data = [
    ["2330", "台積電", "tw"],
    ["2308", "台達電", "tw", tw_stock_fee],
    ["2317", "鴻海", "tw", tw_stock_fee],
    ["2382", "廣達", "tw", tw_stock_fee],
    ["2412", "中華電", "tw", tw_stock_fee],
    ["2454", "聯發科", "tw", tw_stock_fee],
    ["2881", "富邦金", "tw", tw_stock_fee],
    ["2882", "國泰金", "tw", tw_stock_fee],
    ["2891", "中信金", "tw", tw_stock_fee],
    ["6505", "台塑化", "tw", tw_stock_fee],
    # ["3231", "緯創", "tw"],
    # ["2207", "和泰車", "tw"],
    # ["3661", "世芯", "tw"],
    # ["2603", "長榮", "tw"],
    # ["2408", "南亞科", "tw"],
    
    # ["6214", "精誠", "tw"],
    # ["3045", "台灣大", "tw"],
    # ["2379", "瑞昱", "tw"],
    # ["2357", "華碩", "tw"],
    # ["2345", "智邦", "tw"],
    
    # # old us
    # ["AAPL", "Apple Inc.", "us"],
    # ["MSFT", "Microsoft", "us"],    # 20
    # ["NVDA", "Nvidia", "us"],
    # ["AMZN", "Amazon inc.", "us"],
    # ["JPM", "JPMorgan Chase", "us"],
    # ["BA", "Boeing", "us"],
    # ["UNH", "UnitedHealth Group", "us"],
    # ["CSCO", "Cisco", "us"],
    # ["CVX", "Chevron", "us"],
    # ["PG", "Procter & Gamble", "us"],
    # ["DIS", "Disney", "us"],
    
    # ["META", "Meta Platforms", "us"],
    # ["GOOGL", "Google", "us"],
    # ["TSLA", "Tesla", "us"],
    # ["AVGO", "Broadcom", "us"],
    # ["BRK", "Berkshire Hathaway", "us"],
    # ["MRNA", "Moderna", "us"],
    # ["PYPL", "PayPal", "us"],
    # ["BAC", "Bank of America", "us"],
    # ["HD", "Home Depot", "us"],
    # ["WMT", "Walmart", "us"],
    # ["INTC", "Intel", "us"],
    # ["ADBE", "Adobe", "us"],
    
    # # DJIA 
    # ["AAPL", "Apple Inc.", "us"],
    # ["AMGN", "Amgen", "us"],
    # ["AMZN", "Amazon inc.", "us"],
    # ["AXP", "American Express", "us"],
    # ["BA", "Boeing", "us"],
    # ["CSCO", "Cisco", "us"],
    # ["CVX", "Chevron", "us"],
    # ["KO", "Coca-Cola", "us"],
    # ["CAT", "Caterpillar Inc.", "us"],
    # ["CRM", "Salesforce", "us"],    # 10
    # ["DIS", "Disney", "us"],
    # ["GS", "Goldman Sachs", "us"],
    # ["HD", "Home Depot", "us"],
    # ["HON", "Honeywell", "us"],
    # ["IBM", "IBM", "us"],
    # ["JNJ", "Johnson & Johnson", "us"],
    # ["JPM", "JPMorgan Chase", "us"],
    # ["MCD", "McDonald's", "us"],
    # ["MRK", "Merck", "us"],
    # ["MSFT", "Microsoft", "us"],    # 20
    # ["MMM", "3M", "us"],
    # ["NKE", "Nike", "us"],
    # ["NVDA", "Nvidia", "us"],
    # ["PG", "Procter & Gamble", "us"],
    # ["SHW", "Sherwin-Williams", "us"],
    # ["TRV", "Travelers", "us"],
    # ["UNH", "UnitedHealth Group", "us"],
    # ["VZ", "Verizon", "us"],
    # ["V", "Visa", "us"],
    # ["WMT", "Walmart", "us"],   # 30
    
    # Removed from DJIA in past 3 years
    # ["INTC", "Intel", "us"],
    # ["DOW", "Dow Inc.", "us"],
    # ["WBA", "Walgreens Boots Alliance", "us"],
    
    # Not in DJIA
    # ["ADBE", "Adobe", "us"],
    # ["AVGO", "Broadcom", "us"],
    # ["BRK", "Berkshire Hathaway", "us"],
    # ["GOOGL", "Google", "us"],
    # ["META", "Meta Platforms", "us"],
    # ["MRNA", "Moderna", "us"],
    # ["NVDA", "Nvidia", "us"],
    # ["PYPL", "PayPal", "us"],
    # ["TSLA", "Tesla", "us"],
    # ["BAC", "Bank of America", "us"],
]

# 指數
comp_twii = [
    ["2308", "台達電", "tw"],
    ["2317", "鴻海", "tw"],
    ["2330", "台積電", "tw"],
    ["2382", "廣達", "tw"],
    ["2412", "中華電", "tw"],
    ["2454", "聯發科", "tw"],
    ["2881", "富邦金", "tw"],
    ["2882", "國泰金", "tw"],
    ["2891", "中信金", "tw"],
    ["6505", "台塑化", "tw"],
]

comp_spx = [
    ["AAPL", "Apple Inc.", "us"],
    ["MSFT", "Microsoft", "us"],
    ["NVDA", "Nvidia", "us"],
    ["AMZN", "Amazon inc.", "us"],
    ["META", "Meta Platforms", "us"],
    ["GOOGL", "Google", "us"],
    ["TSLA", "Tesla", "us"],
    ["AVGO", "Broadcom", "us"],
    ["BRK", "Berkshire Hathaway", "us"],
    ["JPM", "JPMorgan Chase", "us"],
]

comp_djia = [
    ["GS", "Goldman Sachs", "us"],
    ["UNH", "UnitedHealth Group", "us"],
    ["MSFT", "Microsoft", "us"],
    ["HD", "Home Depot", "us"],
    ["CAT", "Caterpillar", "us"],
    ["V", "Visa", "us"],
    ["CRM", "Salesforce", "us"],
    ["AXP", "American Express", "us"],
    ["MCD", "McDonald's", "us"],
]


market_index = [
    ["twii", "台灣加權指數", "tw", comp_twii, tw_index_fee],
    # ["spx", "S&P 500", "us", comp_spx],
    # ["djia", "道瓊指數", "us", comp_djia],
    
    # ["tx", "台灣指數期貨", "tw", comp_twii, tw_index_fee],
]

data_range_tv = [
    # ["20220101", "20220110", 15.5], # test
    ["20220101", "20241231", 1], # tv1
    ["20220101", "20241231", 2], # tv2
    ["20220101", "20241231", 3], # tv3
    ["20220101", "20241231", 4], # tv4
    ["20220101", "20241231", 5], # tv5
    ["20220101", "20241231", 6], # tv6
    ["20220101", "20241231", 7], # tv7
    ["20220101", "20241231", 8], # tv8
    ["20220101", "20241231", 9], # tv9
    ["20220101", "20241231", 10], # tv10
    ["20220101", "20241231", 11], # tv11
    ["20220101", "20241231", 12], # tv12
    ["20220101", "20241231", 13], # tv13
    ["20220101", "20241231", 14], # tv14
    ["20220101", "20241231", 15], # tv15
    ["20220101", "20241231", 16], # tv16
    ["20220101", "20241231", 17], # tv17
    ["20220101", "20241231", 18], # tv18
    ["20220101", "20241231", 19], # tv19
    ["20220101", "20241231", 20], # tv20    
    ["20220101", "20241231", 21], # tv21
    ["20220101", "20241231", 22], # tv22
    ["20220101", "20241231", 23], # tv23
    ["20220101", "20241231", 24], # tv24
    ["20220101", "20241231", 25], # tv25
    ["20220101", "20241231", 26], # tv26
    ["20220101", "20241231", 27], # tv27
    ["20220101", "20241231", 28], # tv28
    ["20220101", "20241231", 29], # tv29
    ["20220101", "20241231", 30], # tv30
]

In [1]:
def get_balance_list(list_rtn, start_price):
    balance = start_price
    list_balance = [start_price]
    for rtn in list_rtn[1:]:
        balance = balance * (1 + float(rtn))
        list_balance.append(balance)
    return list_balance

In [2]:
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from math import ceil, sqrt

def display_all_plots(all_plots):
    # 計算需要的子圖行數與列數（接近正方形排列）
    num_plots = len(all_plots)
    cols = ceil(sqrt(num_plots))  # 列數
    rows = ceil(num_plots / cols)  # 行數

    # 創建一個大的畫布
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 5, rows * 4))
    # fig.suptitle("Trading Results for All Stocks", fontsize=16, y=0.95)

    # 確保 axes 是一個 2D 陣列
    if rows == 1 and cols == 1:
        axes = [[axes]]
    elif rows == 1 or cols == 1:
        axes = [axes] if rows == 1 else [[ax] for ax in axes]
    else:
        axes = axes.reshape(rows, cols)

    # 在每個子圖中顯示單獨的圖表
    for idx, single_fig in enumerate(all_plots):
        row, col = divmod(idx, cols)
        ax = axes[row][col]
        
        # 從單個圖表中提取並繪製數據
        for line in single_fig.axes[0].get_lines():
            ax.plot(line.get_xdata(), line.get_ydata(), label=line.get_label())
        
        # 設定標題、標籤與圖例
        ax.set_title(single_fig.axes[0].get_title())
        ax.set_xlabel(single_fig.axes[0].get_xlabel())
        ax.set_ylabel(single_fig.axes[0].get_ylabel())
        ax.legend()
        
        ax.xaxis.set_major_locator(MaxNLocator(nbins=5))  # 設置最多顯示 5 個標籤


    # 移除多餘的空白子圖
    for idx in range(num_plots, rows * cols):
        row, col = divmod(idx, cols)
        fig.delaxes(axes[row][col])

    # 調整整體佈局
    plt.tight_layout()
    plt.subplots_adjust(top=0.92)  # 調整總標題的位置
    plt.show()

In [3]:
def cacl_avg(df_stocks_results, wincount=None, ttl_count=None):
    '''
        only return average row
    '''
    
    average_row = pd.DataFrame()
    average_row['tp'] = [df_stocks_results['tp'].sum()]
    average_row['fp'] = [df_stocks_results['fp'].sum()]
    average_row['tn'] = [df_stocks_results['tn'].sum()]
    average_row['fn'] = [df_stocks_results['fn'].sum()]
    average_row['accuracy'] = (average_row['tp'] + average_row['tn']) / (average_row['tp'] + average_row['tn'] + average_row['fp'] + average_row['fn'])
    average_row['precision'] = average_row['tp'] / (average_row['tp'] + average_row['fp'])
    # EV 算法 每個ev成上avail_count 總和後再除上 avail_count 的平均
    average_row['avail_count'] = [df_stocks_results['avail_count'].sum()]
    average_row['pci_avl_count'] = [df_stocks_results['tp'].sum() + df_stocks_results['fp'].sum()]
    average_row['ev'] = (df_stocks_results['ev'].astype(float) * df_stocks_results['avail_count']).sum() / df_stocks_results['avail_count'].sum()
    average_row['precision_ev'] = (df_stocks_results['precision_ev'].astype(float) * (df_stocks_results['tp'] + df_stocks_results['fp'])).sum() / (df_stocks_results['tp'].sum() + df_stocks_results['fp'].sum())
    if ttl_count is None:
        average_row['win B&H'] = None
    else:
        average_row['win B&H'] = round(wincount / ttl_count, 2)
        
    if 'B&H' in df_stocks_results.columns:
        average_row['B&H'] = df_stocks_results['B&H'].mean()
    if 'RTN' in df_stocks_results.columns:
        average_row['RTN'] = df_stocks_results['RTN'].mean()
    
    return average_row

# TV-1 Stock - Usable DayTrade

In [6]:
from TV_usable_dt_stock import TV_UsableFactorDT
import pandas as pd

avgs = pd.DataFrame()
selected_columns = ['accuracy', 'precision', 'ev', 'precision_ev', 'avail_count', 'tp', 'fp', 'tn', 'fn']
# 修改 runAll(i) 函數
def runAll(i):
    stock_results = []
    index = []
    wincount = 0
    ttl_count = 0
    stocks_avg = pd.DataFrame()

    for stock in data:
        list_stock = []
        stock_avg_list = []  # 存放該支股票所有 TV 的結果

        for date_range in data_range_tv:
            env = {
                "stock_id" : stock[0],
                "stock_name" : stock[1],
                "country" : stock[2],
                "start_date" : date_range[0],
                "end_date" : date_range[1],
                "tv" : date_range[2],
                "run_count" : str(i)
            }
            print(env['stock_id'], env['stock_name'], env['country'], f"tv{date_range[2]}")

            eval_module = TV_UsableFactorDT(env)
            eval_module.run()
            train_datarange, test_datarange = eval_module.split_exp(date_range[2])
            
            mode = 1
            eval_module.training(mode, train_datarange, test_datarange)

            # 繪圖
            result = eval_module.get_result(1)   # Test 結果
            result_train = result["train"]  # Training 結果
            result_test = result["test"]  # Test 結果
            index.append(f"{stock[0]} - {date_range[2]}")
            stock_results.append(result_test)
            list_stock.append(result_test)
            
            # Training 報酬計算
            train_date, train_bnh_balance, train_stag_rtn = eval_module.get_return_list('train')
            train_stag_balance = get_balance_list(train_stag_rtn, train_bnh_balance[0])

            # Test 報酬計算
            list_date, list_bnh_balance, list_stag_rtn = eval_module.get_return_list('test')
            list_stag_balance = get_balance_list(list_stag_rtn, list_bnh_balance[0])
            
            ttl_count += 1
            if list_stag_balance[-1] > list_bnh_balance[-1]:
                print(f"win B&H")
                wincount += 1
            else:
                print(f"loss B&H")
            
            st = sorted(train_datarange.keys())[0]
            et = sorted(train_datarange.keys())[-1]
            train_N_days = (datetime.strptime(et, '%Y%m%d') - datetime.strptime(st, '%Y%m%d')).days
            
            st = sorted(test_datarange.keys())[0]
            et = sorted(test_datarange.keys())[-1]
            test_N_days = (datetime.strptime(et, '%Y%m%d') - datetime.strptime(st, '%Y%m%d')).days

            # 計算該 TV 的結果 (Test)
            stock_avg = cacl_avg(pd.DataFrame(list_stock).loc[:, selected_columns])
            stock_avg['stock_id'] = stock[0]  # 加入個股代碼
            stock_avg['tv'] = date_range[2]  # 加入 TV
            
            # 計算該 TV 的結果 (Training)
            stock_avg['Train_RTN'] = (train_stag_balance[-1] / train_bnh_balance[0] - 1) * 100
            stock_avg['Train_B&H'] = (train_bnh_balance[-1] / train_bnh_balance[0] - 1) * 100
            stock_avg['Ann_Train_RTN'] = ((1 + stock_avg['Train_RTN'] / 100) ** (252 / train_N_days) - 1) * 100  # 年化 Training 報酬率
            stock_avg['Ann_Train_B&H'] = ((1 + stock_avg['Train_B&H'] / 100) ** (252 / train_N_days) - 1) * 100  # 年化 Training B&H

            # 計算該 TV 的結果 (Test)
            stock_avg['RTN'] = (list_stag_balance[-1] / list_bnh_balance[0] - 1) * 100
            stock_avg['B&H'] = (list_bnh_balance[-1] / list_bnh_balance[0] - 1) * 100
            stock_avg['Ann_RTN'] = ((1 + stock_avg['RTN'] / 100) ** (252 / test_N_days) - 1) * 100  # 年化報酬率
            stock_avg['Ann_B&H'] = ((1 + stock_avg['B&H'] / 100) ** (252 / test_N_days) - 1) * 100  # 年化 B&H
            stock_avg['win B&H'] = ("yes" if list_stag_balance[-1] > list_bnh_balance[-1] else "no")

            stock_avg_list.append(stock_avg)  # 收集該股票的 TV 結果

        if stock_avg_list:
            stock_avg_df = pd.concat(stock_avg_list)
            display(stock_avg_df.loc[:, ['stock_id', 'tv', 'accuracy', 'precision', 'ev', 'precision_ev', 'Train_RTN', 'Ann_Train_RTN', 'Train_B&H', 'Ann_Train_B&H', 'RTN', 'Ann_RTN', 'B&H', 'Ann_B&H', 'win B&H', 'avail_count', 'tp', 'fp', 'tn', 'fn']])
            stocks_avg = pd.concat([stocks_avg, stock_avg_df])

    return stocks_avg

# 迭代執行
for i in range(1):
    print(i+1)
    avgs = pd.concat([avgs, runAll(i+1)])

# 計算 **所有 TV 的 RTN 與 B&H 總平均**
tv_avg_df = avgs.groupby("tv")[["RTN", "B&H", "Ann_RTN", "Ann_B&H", "Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H"]].mean().reset_index()
tv_avg_df["Train_RTN"] = tv_avg_df["Train_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Train_B&H"] = tv_avg_df["Train_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Train_RTN"] = tv_avg_df["Ann_Train_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Train_B&H"] = tv_avg_df["Ann_Train_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Test_RTN"] = tv_avg_df["RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Test_B&H"] = tv_avg_df["B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Test_RTN"] = tv_avg_df["Ann_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Test_B&H"] = tv_avg_df["Ann_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Win B&H"] = tv_avg_df["Ann_RTN"] > tv_avg_df["Ann_B&H"]
tv_avg_df["Diff"] = tv_avg_df["Ann_RTN"] - tv_avg_df["Ann_B&H"]
tv_avg_df["Diff"] = tv_avg_df["Diff"].apply(lambda x: f"{x:.2f}%")

display(tv_avg_df.loc[:, ["tv", "Ann_Train_RTN", "Ann_Train_B&H", "Ann_Test_RTN",  "Ann_Test_B&H", "Win B&H", "Diff"]])

1
2330 台積電 tw tv1
win B&H
2330 台積電 tw tv2
win B&H
2330 台積電 tw tv3
win B&H
2330 台積電 tw tv4
loss B&H
2330 台積電 tw tv5
loss B&H
2330 台積電 tw tv6
win B&H
2330 台積電 tw tv7
win B&H
2330 台積電 tw tv8
loss B&H
2330 台積電 tw tv9
loss B&H
2330 台積電 tw tv10
loss B&H
2330 台積電 tw tv11
win B&H
2330 台積電 tw tv12
win B&H
2330 台積電 tw tv13
win B&H
2330 台積電 tw tv14
loss B&H
2330 台積電 tw tv15
win B&H
2330 台積電 tw tv16
win B&H
2330 台積電 tw tv17
win B&H
2330 台積電 tw tv18
win B&H
2330 台積電 tw tv19
win B&H
2330 台積電 tw tv20
win B&H
2330 台積電 tw tv21
win B&H
2330 台積電 tw tv22
win B&H
2330 台積電 tw tv23
win B&H
2330 台積電 tw tv24
win B&H
2330 台積電 tw tv25
win B&H
2330 台積電 tw tv26
win B&H
2330 台積電 tw tv27
win B&H
2330 台積電 tw tv28
win B&H
2330 台積電 tw tv29
win B&H
2330 台積電 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2330,1,0.500724,0.480300,0.001524,0.000934,1.567350,18.577335,0.792393,9.032580,180.173340,27.811658,69.291339,13.359370,yes,691,256,277,90,68
0,2330,2,0.503682,0.483268,0.001538,0.000993,-1.695412,-6.228994,-8.874802,-29.499449,172.640543,28.026794,87.937063,16.815014,yes,1358,491,525,193,149
0,2330,3,0.502498,0.482190,0.001545,0.000988,-0.939528,-2.305176,-10.935024,-24.881553,162.807636,27.947902,91.622103,18.043148,yes,2002,731,785,275,211
0,2330,4,0.502498,0.482190,0.001545,0.000988,0.000000,0.000000,-16.006339,-27.446592,0.000000,0.000000,103.598485,20.683715,no,2002,731,785,275,211
0,2330,5,0.502498,0.482190,0.001545,0.000988,0.000000,0.000000,-22.900158,-31.684347,0.000000,0.000000,115.646941,23.485456,no,2002,731,785,275,211
0,2330,6,0.502915,0.483707,0.001568,0.001017,5.128037,6.277170,-19.334390,-23.015499,147.547003,29.522806,113.293651,24.132998,yes,2573,950,1014,344,265
0,2330,7,0.504328,0.485115,0.001600,0.001037,13.413895,14.005342,-23.137876,-23.969167,152.249702,31.647296,121.193416,26.606467,yes,3119,1157,1228,416,318
0,2330,8,0.502609,0.484252,0.001599,0.001046,16.855403,15.224096,-30.586371,-28.261087,127.203617,29.006510,167.745953,35.750549,no,3641,1353,1441,477,370
0,2330,9,0.502658,0.484306,0.001611,0.001064,26.405561,20.618228,-29.477021,-24.375151,119.703508,29.082109,123.958333,29.887617,no,4138,1543,1643,537,415
0,2330,10,0.503254,0.484669,0.001625,0.001073,28.479030,19.773080,-26.069731,-19.545184,126.788518,32.061725,134.972678,33.661367,no,4610,1723,1832,597,458
0,2330,11,0.504149,0.485568,0.001639,0.001081,13.054090,8.500179,-20.285261,-13.993301,118.548721,32.453366,97.974217,27.828233,yes,5062,1901,2014,651,496
0,2330,12,0.505643,0.486715,0.001671,0.001108,18.975686,11.070992,-19.017433,-11.968218,128.839651,36.466219,105.938697,31.167751,yes,5494,2070,2183,708,533
0,2330,13,0.506861,0.487639,0.001693,0.001124,27.205104,14.357220,-15.530903,-8.980922,120.579045,36.881138,102.830189,32.399301,yes,5903,2229,2342,763,569
0,2330,14,0.507553,0.488405,0.001708,0.001142,38.391026,18.146808,-19.175911,-10.350802,109.208467,36.275962,113.717694,37.499936,no,6289,2380,2493,812,604
0,2330,15,0.508798,0.489907,0.001731,0.001167,35.253218,15.534569,-6.497623,-3.161507,111.596452,39.695527,81.895093,30.582433,yes,6649,2524,2628,859,638
0,2330,16,0.510295,0.491513,0.001759,0.001195,29.864204,12.431631,-7.923930,-3.634082,117.515111,44.699381,85.664940,34.206473,yes,6994,2664,2756,905,669
0,2330,17,0.511682,0.493211,0.001790,0.001229,31.345738,12.176284,-10.618067,-4.620199,119.459899,49.325026,96.886447,41.281665,yes,7319,2797,2874,948,700
0,2330,18,0.513116,0.495004,0.001818,0.001261,36.666899,13.242163,-17.115689,-7.200959,108.581976,50.121339,101.688555,47.358938,yes,7624,2923,2982,989,730
0,2330,19,0.514101,0.496162,0.001842,0.001286,44.175272,14.799721,-13.312203,-5.246574,98.114225,50.130435,95.810565,49.090431,yes,7907,3038,3085,1027,757
0,2330,20,0.514699,0.496835,0.001869,0.001312,45.958646,14.495077,-9.667195,-3.573879,95.724759,55.024687,87.282230,50.625783,yes,8164,3140,3180,1062,782
0,2330,21,0.515065,0.497153,0.001895,0.001335,51.288899,15.163393,-7.448494,-2.604986,90.782611,59.005616,83.447099,54.592092,yes,8397,3230,3267,1095,805
0,2330,22,0.515444,0.497525,0.001924,0.001363,44.153553,12.644653,8.240887,2.611771,89.303278,66.350780,58.554572,44.422958,yes,8612,3317,3350,1122,823
0,2330,23,0.515847,0.498017,0.001949,0.001387,61.292907,16.056978,24.405705,7.039074,78.419922,68.071346,37.820513,33.332577,yes,8803,3390,3417,1151,845
0,2330,24,0.516553,0.498846,0.001973,0.001412,68.676522,16.894362,23.930269,6.615596,68.887218,71.059785,35.220126,36.218930,yes,8971,3458,3474,1176,863
0,2330,25,0.517060,0.499716,0.001994,0.001438,79.677602,18.293456,30.110935,7.838182,58.230104,72.987028,27.068558,33.123288,yes,9115,3517,3521,1196,881
0,2330,26,0.517163,0.500070,0.002007,0.001451,101.080444,21.239029,59.270998,13.692377,38.435455,59.309069,3.864734,5.579438,yes,9235,3562,3561,1214,898
0,2330,27,0.516717,0.499792,0.002001,0.001445,145.713769,26.962566,48.019017,10.975362,14.435914,27.252000,14.361702,27.104548,yes,9332,3596,3599,1226,911
0,2330,28,0.516695,0.500000,0.002000,0.001445,151.773185,26.676935,50.079239,10.957147,14.464009,37.872335,13.516367,35.174184,yes,9404,3623,3623,1236,922
0,2330,29,0.516501,0.500069,0.001996,0.001441,164.936439,27.155839,71.949287,14.299394,7.011133,27.627499,0.000000,0.000000,yes,9454,3640,3639,1243,932
0,2330,30,0.516139,0.499863,0.001993,0.001437,180.373785,27.863133,63.232964,12.392065,2.753996,21.604819,6.435644,56.684866,no,9480,3649,3651,1244,936

2308 台達電 tw tv1
loss B&H
2308 台達電 tw tv2
loss B&H
2308 台達電 tw tv3
loss B&H
2308 台達電 tw tv4
loss B&H
2308 台達電 tw tv5
loss B&H
2308 台達電 tw tv6
win B&H
2308 台達電 tw tv7
win B&H
2308 台達電 tw tv8
win B&H
2308 台達電 tw tv9
win B&H
2308 台達電 tw tv10
win B&H
2308 台達電 tw tv11
win B&H
2308 台達電 tw tv12
win B&H
2308 台達電 tw tv13
win B&H
2308 台達電 tw tv14
win B&H
2308 台達電 tw tv15
win B&H
2308 台達電 tw tv16
win B&H
2308 台達電 tw tv17
win B&H
2308 台達電 tw tv18
win B&H
2308 台達電 tw tv19
win B&H
2308 台達電 tw tv20
win B&H
2308 台達電 tw tv21
win B&H
2308 台達電 tw tv22
win B&H
2308 台達電 tw tv23
win B&H
2308 台達電 tw tv24
win B&H
2308 台達電 tw tv25
loss B&H
2308 台達電 tw tv26
win B&H
2308 台達電 tw tv27
win B&H
2308 台達電 tw tv28
win B&H
2308 台達電 tw tv29
win B&H
2308 台達電 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2308,1,0.489149,0.495114,0.000782,0.001758,9.847783,179.853493,-4.964539,-42.759419,50.046907,10.147510,58.856089,11.654481,no,599,152,155,141,151
0,2308,2,0.490662,0.495050,0.000787,0.001729,10.795510,47.047109,-7.092199,-24.170523,51.949412,10.855872,67.184466,13.496067,no,1178,300,306,278,294
0,2308,3,0.491379,0.496659,0.000805,0.001776,9.072845,23.931666,-11.524823,-26.104553,51.449062,11.167779,73.939394,15.163824,no,1740,446,452,409,433
0,2308,4,0.492772,0.498833,0.000820,0.001706,-8.067660,-14.335076,-19.680851,-33.177500,62.260474,13.654376,91.333333,18.717125,no,2352,641,644,518,549
0,2308,5,0.493236,0.500000,0.000867,0.001777,-1.514051,-2.210430,-15.248227,-21.525307,67.048865,15.125819,82.029598,17.872239,no,2883,783,783,639,678
0,2308,6,0.494256,0.501630,0.000929,0.001852,-9.590516,-11.550519,-8.510638,-10.262720,81.971683,18.632224,66.537718,15.669176,yes,3395,923,917,755,800
0,2308,7,0.498102,0.504624,0.001047,0.001838,-10.627865,-11.041860,-9.574468,-9.949751,153.393455,31.824399,68.493151,16.770571,yes,3951,1146,1125,822,858
0,2308,8,0.500780,0.506523,0.001115,0.001811,0.580301,0.527789,-2.482270,-2.260791,125.958125,28.786621,62.759924,16.319537,yes,4485,1359,1324,887,915
0,2308,9,0.502703,0.507967,0.001179,0.001818,-2.073317,-1.662122,1.241135,0.991682,125.984749,30.267619,46.928328,13.291256,yes,4995,1562,1513,949,971
0,2308,10,0.503374,0.507528,0.001211,0.001793,2.692716,1.931529,2.836879,2.034538,106.832872,27.994571,52.120141,15.312061,yes,5483,1753,1701,1007,1022
0,2308,11,0.503199,0.506306,0.001242,0.001786,12.268504,7.998292,1.418440,0.940904,99.314427,28.138642,49.220104,15.475160,yes,5940,1927,1879,1062,1072
0,2308,12,0.503213,0.505792,0.001279,0.001797,7.374136,4.393435,1.595745,0.961313,103.000696,30.461817,48.704663,16.069477,yes,6381,2096,2048,1115,1122
0,2308,13,0.503746,0.506156,0.001315,0.001816,0.943989,0.525200,6.737589,3.702104,110.348151,34.325464,46.179966,16.261470,yes,6807,2261,2206,1168,1172
0,2308,14,0.503826,0.507281,0.001315,0.001857,4.411495,2.240356,7.801418,3.930766,54.795325,20.106271,42.786070,16.107414,yes,7187,2369,2301,1252,1265
0,2308,15,0.504432,0.507988,0.001347,0.001882,12.455807,5.773880,25.177305,11.335748,98.982454,35.917908,16.351351,6.988038,yes,7559,2512,2433,1301,1313
0,2308,16,0.504802,0.508481,0.001378,0.001913,16.562078,7.113495,26.595745,11.153869,98.093852,38.405630,20.757363,9.382440,yes,7914,2638,2550,1357,1369
0,2308,17,0.504558,0.509155,0.001372,0.001941,15.815891,6.382991,26.595745,10.448518,44.725234,20.752762,24.602026,11.874062,yes,8227,2725,2627,1426,1449
0,2308,18,0.504982,0.509959,0.001395,0.001970,25.019692,9.296820,15.070922,5.747635,73.030087,35.392164,28.315946,14.772884,yes,8531,2842,2731,1466,1492
0,2308,19,0.505788,0.511427,0.001429,0.002012,15.972459,5.749320,5.851064,2.168299,90.727228,46.777801,41.611842,22.971498,yes,8812,2954,2822,1503,1533
0,2308,20,0.506231,0.512338,0.001458,0.002048,23.819623,7.947954,10.815603,3.744504,80.720405,47.159085,38.647343,23.778986,yes,9067,3052,2905,1538,1572
0,2308,21,0.506667,0.513399,0.001486,0.002091,27.513558,8.641277,4.078014,1.372333,77.458949,50.952226,45.685279,31.015920,yes,9300,3142,2978,1570,1610
0,2308,22,0.506884,0.514349,0.001512,0.002134,32.555670,9.610110,3.368794,1.084586,69.268945,52.153922,47.431507,36.284176,yes,9515,3226,3046,1597,1646
0,2308,23,0.506903,0.515062,0.001515,0.002147,68.170613,17.576406,26.950355,7.716322,37.484788,33.041268,22.127660,19.633988,yes,9706,3300,3107,1620,1679
0,2308,24,0.507191,0.516322,0.001526,0.002179,56.982496,14.413404,11.702128,3.359429,41.594619,42.800858,34.112150,35.075661,yes,9874,3369,3156,1639,1710
0,2308,25,0.506841,0.517142,0.001518,0.002210,46.936495,11.664290,15.248227,4.152545,10.471404,12.629947,27.744807,33.969862,no,10013,3409,3183,1666,1755
0,2308,26,0.506661,0.517863,0.001526,0.002241,76.567061,16.970341,37.234043,9.118847,23.427579,35.171665,7.089552,10.304300,yes,10133,3450,3212,1684,1787
0,2308,27,0.506745,0.518381,0.001536,0.002260,85.927456,17.902279,37.411348,8.805510,29.140112,57.940054,7.894737,14.545805,yes,10230,3483,3236,1701,1810
0,2308,28,0.507086,0.519225,0.001547,0.002285,82.806577,16.706613,36.524823,8.299728,24.156110,67.261449,11.673152,30.014390,yes,10302,3511,3251,1713,1827
0,2308,29,0.507148,0.519811,0.001558,0.002308,97.683629,18.298456,41.843972,9.001587,18.622473,84.927335,6.427689,25.140149,yes,10352,3529,3260,1721,1842
0,2308,30,0.507034,0.520141,0.001562,0.002321,119.413025,20.603684,39.539007,8.267216,7.118273,64.065639,11.096774,113.329263,no,10378,3538,3264,1724,1852

2317 鴻海 tw tv1
win B&H
2317 鴻海 tw tv2
win B&H
2317 鴻海 tw tv3
win B&H
2317 鴻海 tw tv4
win B&H
2317 鴻海 tw tv5
win B&H
2317 鴻海 tw tv6
win B&H
2317 鴻海 tw tv7
win B&H
2317 鴻海 tw tv8
win B&H
2317 鴻海 tw tv9
win B&H
2317 鴻海 tw tv10
win B&H
2317 鴻海 tw tv11
win B&H
2317 鴻海 tw tv12
win B&H
2317 鴻海 tw tv13
win B&H
2317 鴻海 tw tv14
win B&H
2317 鴻海 tw tv15
win B&H
2317 鴻海 tw tv16
win B&H
2317 鴻海 tw tv17
win B&H
2317 鴻海 tw tv18
win B&H
2317 鴻海 tw tv19
win B&H
2317 鴻海 tw tv20
win B&H
2317 鴻海 tw tv21
win B&H
2317 鴻海 tw tv22
win B&H
2317 鴻海 tw tv23
win B&H
2317 鴻海 tw tv24
win B&H
2317 鴻海 tw tv25
win B&H
2317 鴻海 tw tv26
win B&H
2317 鴻海 tw tv27
win B&H
2317 鴻海 tw tv28
win B&H
2317 鴻海 tw tv29
win B&H
2317 鴻海 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2317,1,0.428571,0.410194,0.001497,0.001196,7.861002,129.129009,-0.970874,-10.137885,164.714436,26.095444,78.640777,14.820138,yes,693,169,243,128,153
0,2317,2,0.430155,0.410804,0.001553,0.001254,7.771603,32.511978,0.485437,1.838094,175.038329,28.303241,79.512195,15.502680,yes,1353,327,469,255,302
0,2317,3,0.431138,0.411479,0.001558,0.001193,11.921238,32.081703,0.000000,0.000000,163.400166,28.021418,79.512195,16.093897,yes,2004,509,728,355,412
0,2317,4,0.431179,0.410081,0.001569,0.001192,11.424378,22.015828,3.883495,7.259556,157.498804,28.416408,70.370370,15.129627,yes,2630,659,948,475,548
0,2317,5,0.430337,0.408234,0.001577,0.001172,10.893211,16.356590,6.796117,10.112613,152.256118,28.916792,65.765766,14.882397,yes,3237,823,1193,570,651
0,2317,6,0.430031,0.407392,0.001586,0.001164,12.399178,15.291848,5.825243,7.135837,144.092686,29.004402,68.807339,16.116884,yes,3816,981,1427,660,748
0,2317,7,0.430139,0.406902,0.001598,0.001157,13.372971,13.962505,4.368932,4.553517,141.996104,30.033802,70.370370,17.155675,yes,4373,1132,1650,749,842
0,2317,8,0.430957,0.407136,0.001624,0.001169,9.798674,8.876236,4.368932,3.966910,157.220472,34.071417,76.923077,19.370945,yes,4910,1278,1861,838,933
0,2317,9,0.432761,0.408216,0.001667,0.001194,6.624976,5.265767,-1.456311,-1.166755,175.128432,38.851970,81.280788,21.280162,yes,5421,1421,2060,925,1015
0,2317,10,0.435063,0.409915,0.001708,0.001234,10.174521,7.225590,-1.456311,-1.050695,165.108855,39.252967,84.000000,23.009351,yes,5898,1538,2214,1028,1118
0,2317,11,0.436664,0.411706,0.001745,0.001274,12.327898,8.036278,-4.757282,-3.188914,158.704960,40.733573,87.563710,25.369905,yes,6355,1653,2362,1122,1218
0,2317,12,0.437518,0.412378,0.001775,0.001301,9.217699,5.472954,-1.941748,-1.177979,151.103907,41.308575,80.392157,24.802938,yes,6802,1779,2535,1197,1291
0,2317,13,0.438703,0.413483,0.001809,0.001336,15.784371,8.514119,0.970874,0.540126,152.346969,44.388665,77.777778,25.650428,yes,7219,1883,2671,1284,1381
0,2317,14,0.440026,0.414594,0.001851,0.001369,7.934458,3.996576,3.398058,1.729828,171.790521,52.080997,72.769953,25.768158,yes,7620,2000,2824,1353,1443
0,2317,15,0.441051,0.415461,0.001886,0.001398,18.231590,8.337697,9.223301,4.308943,147.290445,49.753655,65.022422,25.033966,yes,7990,2096,2949,1428,1517
0,2317,16,0.441766,0.415985,0.001925,0.001436,15.263328,6.576690,5.339806,2.360041,153.586926,55.650630,70.370370,28.831283,yes,8337,2186,3069,1497,1585
0,2317,17,0.442687,0.416728,0.001970,0.001486,8.161646,3.361462,6.310680,2.612349,167.260805,65.115880,70.370370,31.231798,yes,8663,2272,3180,1563,1648
0,2317,18,0.443837,0.418085,0.002020,0.001543,5.511759,2.158892,0.970874,0.385386,172.710408,74.093488,76.076555,36.704379,yes,8965,2358,3282,1621,1704
0,2317,19,0.445142,0.419505,0.002069,0.001600,11.569692,4.216529,-5.825243,-2.238713,164.385705,78.218488,92.066806,47.389634,yes,9242,2439,3375,1675,1753
0,2317,20,0.446856,0.421132,0.002123,0.001660,9.101609,3.167245,-1.456311,-0.523750,170.366604,91.425784,82.178218,47.932991,yes,9493,2515,3457,1727,1794
0,2317,21,0.448570,0.422411,0.002177,0.001717,11.797203,3.875952,-2.427184,-0.834383,161.260929,99.268237,84.000000,54.926467,yes,9722,2586,3536,1775,1825
0,2317,22,0.450216,0.423599,0.002232,0.001773,12.437774,3.890558,-1.456311,-0.476495,158.523950,113.283039,78.640777,58.835126,yes,9933,2653,3610,1819,1851
0,2317,23,0.451438,0.424299,0.002265,0.001794,43.621253,11.936816,41.262136,11.360809,107.500828,92.443162,26.460481,23.433431,yes,10121,2710,3677,1859,1875
0,2317,24,0.452425,0.424988,0.002288,0.001807,63.657710,15.844859,50.485437,12.978546,84.092949,86.853603,16.088328,16.511492,yes,10289,2762,3737,1893,1897
0,2317,25,0.453561,0.425732,0.002318,0.001827,60.981077,14.625213,66.990291,15.835911,85.890885,109.690323,4.249292,5.095701,yes,10433,2806,3785,1926,1916
0,2317,26,0.454089,0.425698,0.002326,0.001820,111.176376,22.887679,108.252427,22.416184,35.378769,54.296646,-18.763797,-25.736082,yes,10553,2836,3826,1956,1935
0,2317,27,0.454178,0.425472,0.002322,0.001806,146.539592,27.075737,63.592233,13.962801,16.284954,30.950112,4.545455,8.268677,yes,10650,2863,3866,1974,1947
0,2317,28,0.454393,0.425365,0.002324,0.001801,146.504268,25.992671,70.873786,14.706390,17.018480,45.299894,1.657459,3.985444,yes,10722,2881,3892,1991,1958
0,2317,29,0.454605,0.425169,0.002324,0.001792,161.822786,26.785716,103.883495,19.202672,9.703924,39.572475,-14.617169,-43.384679,yes,10772,2892,3910,2005,1965
0,2317,30,0.454621,0.424816,0.002324,0.001784,179.511206,27.769238,104.368932,18.578566,3.286831,26.218689,-9.135802,-49.831845,yes,10798,2893,3917,2016,1972

2382 廣達 tw tv1
loss B&H
2382 廣達 tw tv2
loss B&H
2382 廣達 tw tv3
loss B&H
2382 廣達 tw tv4
loss B&H
2382 廣達 tw tv5
loss B&H
2382 廣達 tw tv6
loss B&H
2382 廣達 tw tv7
loss B&H
2382 廣達 tw tv8
loss B&H
2382 廣達 tw tv9
loss B&H
2382 廣達 tw tv10
loss B&H
2382 廣達 tw tv11
loss B&H
2382 廣達 tw tv12
loss B&H
2382 廣達 tw tv13
loss B&H
2382 廣達 tw tv14
loss B&H
2382 廣達 tw tv15
loss B&H
2382 廣達 tw tv16
loss B&H
2382 廣達 tw tv17
loss B&H
2382 廣達 tw tv18
loss B&H
2382 廣達 tw tv19
loss B&H
2382 廣達 tw tv20
loss B&H
2382 廣達 tw tv21
loss B&H
2382 廣達 tw tv22
loss B&H
2382 廣達 tw tv23
loss B&H
2382 廣達 tw tv24
win B&H
2382 廣達 tw tv25
win B&H
2382 廣達 tw tv26
win B&H
2382 廣達 tw tv27
win B&H
2382 廣達 tw tv28
loss B&H
2382 廣達 tw tv29
win B&H
2382 廣達 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2382,1,0.479076,0.476190,0.000273,0.000161,0.950847,10.925382,-0.853789,-8.966915,1.940940,0.458924,206.296692,30.554525,no,693,260,286,72,75
0,2382,2,0.477974,0.475926,0.000303,0.000167,5.816798,23.695721,-1.814301,-6.654825,6.436113,1.548369,211.956522,32.346458,no,1362,514,566,137,145
0,2382,3,0.478369,0.476780,0.000363,0.000203,0.148573,0.367465,-8.324440,-19.324044,17.137648,4.117032,236.854460,36.310659,no,2011,770,845,192,204
0,2382,4,0.478393,0.477380,0.000382,0.000219,-0.271172,-0.498230,-20.490928,-34.411931,13.083509,3.304745,280.132450,42.347914,no,2638,1013,1109,249,267
0,2382,5,0.478569,0.477429,0.000478,0.000271,3.090778,4.560722,-14.194237,-20.091334,46.680922,11.089035,255.198020,41.615099,no,3243,1248,1366,304,325
0,2382,6,0.478512,0.477597,0.000530,0.000299,6.563373,8.046248,-9.711846,-11.695001,38.347712,9.706433,266.071429,44.822638,no,3816,1471,1609,355,381
0,2382,7,0.479047,0.477819,0.000597,0.000332,7.744477,8.077093,-16.862327,-17.494343,52.674774,13.399226,262.373737,46.610304,no,4367,1691,1848,401,427
0,2382,8,0.479788,0.478469,0.000642,0.000361,-0.525466,-0.478155,-20.170758,-18.531044,50.484332,13.522907,293.150685,52.939027,no,4898,1900,2071,450,477
0,2382,9,0.479788,0.478469,0.000642,0.000361,0.000000,0.000000,-22.091782,-18.103260,0.000000,0.000000,296.408840,56.312040,no,4898,1900,2071,450,477
0,2382,10,0.479788,0.478469,0.000642,0.000361,0.000000,0.000000,-22.732124,-16.946247,0.000000,0.000000,308.831909,61.322319,no,4898,1900,2071,450,477
0,2382,11,0.479788,0.478469,0.000642,0.000361,0.000000,0.000000,-19.957311,-13.758194,0.000000,0.000000,276.146789,61.002705,no,4898,1900,2071,450,477
0,2382,12,0.480165,0.478672,0.000704,0.000401,-8.223843,-5.053919,-14.514408,-9.041819,57.219598,18.522234,259.649123,61.720580,no,5344,2076,2261,490,517
0,2382,13,0.480583,0.478261,0.000767,0.000429,-1.100547,-0.615081,-4.909285,-2.767486,69.765264,23.371714,219.243604,58.511617,no,5768,2244,2448,528,548
0,2382,14,0.480473,0.477232,0.000816,0.000440,4.365661,2.217319,-2.027748,-1.045906,57.561635,21.001629,212.977099,61.350009,no,6171,2400,2629,565,577
0,2382,15,0.480073,0.476190,0.000843,0.000431,9.452250,4.413439,49.413020,21.168235,39.330473,15.943689,95.238095,34.771151,no,6549,2540,2794,604,611
0,2382,16,0.478753,0.474341,0.000822,0.000375,44.114705,17.805231,111.312700,39.860854,-2.987108,-1.431584,36.018957,15.750467,no,6895,2662,2950,639,644
0,2382,17,0.477550,0.472492,0.000764,0.000283,86.384699,30.002633,180.149413,54.359059,-19.079106,-10.236500,17.622951,8.632436,no,7216,2774,3097,672,673
0,2382,18,0.476108,0.470473,0.000707,0.000195,94.506679,30.324499,155.602988,45.296025,-26.998130,-15.962322,12.770138,6.867122,no,7513,2876,3237,701,699
0,2382,19,0.474833,0.468612,0.000669,0.000139,72.478845,22.830871,114.514408,33.364568,-13.413656,-8.204012,43.500000,23.943370,no,7788,2971,3369,727,721
0,2382,20,0.473940,0.467156,0.000649,0.000101,55.360635,17.082335,116.648879,31.882007,-3.198433,-2.099858,40.686275,24.964341,no,8039,3058,3488,752,741
0,2382,21,0.474009,0.466528,0.000650,0.000077,49.214052,14.622361,146.531483,36.028220,15.449123,10.864698,26.710817,18.526363,no,8272,3143,3594,778,757
0,2382,22,0.473411,0.465547,0.000634,0.000050,53.810654,15.048060,165.208111,37.376353,-1.323656,-1.056996,18.840580,14.757750,no,8481,3216,3692,799,774
0,2382,23,0.472652,0.464427,0.000631,0.000037,39.997190,11.049226,174.813234,37.011912,6.598334,5.897692,12.549020,11.184208,no,8666,3277,3779,819,791
0,2382,24,0.472379,0.463788,0.000637,0.000036,40.598481,10.709220,174.813234,35.234366,14.061220,14.427820,9.751434,10.000794,yes,8834,3330,3850,843,811
0,2382,25,0.472266,0.463261,0.000654,0.000042,29.768728,7.756792,192.422625,36.019262,22.517552,27.448982,1.592920,1.905377,yes,8978,3373,3908,867,830
0,2382,26,0.472192,0.462845,0.000661,0.000038,36.157492,8.882165,232.977588,39.327116,10.528080,15.410387,-10.172144,-14.238361,yes,9098,3407,3954,889,848
0,2382,27,0.471996,0.462389,0.000666,0.000038,55.823062,12.499851,166.808965,29.770028,7.990738,14.728021,7.490637,13.780193,yes,9195,3430,3988,910,867
0,2382,28,0.471782,0.461940,0.000662,0.000034,72.727115,15.023731,171.611526,29.161498,0.438935,1.046662,12.992126,33.694808,no,9267,3447,4015,925,880
0,2382,29,0.471504,0.461405,0.000654,0.000024,81.258379,15.795036,229.775880,34.208493,-2.475706,-8.629471,-10.031348,-31.651597,yes,9317,3455,4033,938,891
0,2382,30,0.470941,0.460893,0.000648,0.000015,80.607352,15.135286,219.103522,31.868976,-4.320096,-27.237225,-3.367003,-21.854635,no,9343,3459,4046,941,897

2412 中華電 tw tv1
loss B&H
2412 中華電 tw tv2
win B&H
2412 中華電 tw tv3
loss B&H
2412 中華電 tw tv4
loss B&H
2412 中華電 tw tv5
loss B&H
2412 中華電 tw tv6
loss B&H
2412 中華電 tw tv7
win B&H
2412 中華電 tw tv8
loss B&H
2412 中華電 tw tv9
loss B&H
2412 中華電 tw tv10
loss B&H
2412 中華電 tw tv11
loss B&H
2412 中華電 tw tv12
loss B&H
2412 中華電 tw tv13
loss B&H
2412 中華電 tw tv14
loss B&H
2412 中華電 tw tv15
loss B&H
2412 中華電 tw tv16
loss B&H
2412 中華電 tw tv17
loss B&H
2412 中華電 tw tv18
loss B&H
2412 中華電 tw tv19
loss B&H
2412 中華電 tw tv20
loss B&H
2412 中華電 tw tv21
loss B&H
2412 中華電 tw tv22
win B&H
2412 中華電 tw tv23
win B&H
2412 中華電 tw tv24
loss B&H
2412 中華電 tw tv25
win B&H
2412 中華電 tw tv26
loss B&H
2412 中華電 tw tv27
loss B&H
2412 中華電 tw tv28
loss B&H
2412 中華電 tw tv29
win B&H
2412 中華電 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2412,1,0.375180,0.377586,0.000023,0.000227,2.608647,32.598107,1.731602,20.695350,-0.379381,-0.090494,4.219409,0.989238,no,693,219,361,41,72
0,2412,2,0.375549,0.374890,0.000052,0.000209,6.478054,26.628234,6.060606,24.771083,4.112680,0.997761,0.406504,0.099983,yes,1366,427,712,86,141
0,2412,3,0.371910,0.368790,-0.000017,0.000116,7.849983,20.527154,12.121212,32.665517,-10.712449,-2.848683,-5.000000,-1.299770,no,1901,579,991,128,203
0,2412,4,0.367436,0.364323,-0.000054,0.000072,11.393871,21.954385,7.792208,14.799957,-11.033015,-3.044001,0.000000,0.000000,no,2512,772,1347,151,242
0,2412,5,0.364162,0.361509,-0.000088,0.000041,13.419386,20.260566,11.688312,17.580933,-13.288819,-3.838549,-3.891051,-1.083554,no,3114,958,1692,176,288
0,2412,6,0.362503,0.360329,-0.000089,0.000040,4.072684,4.979770,5.194805,6.359347,-5.846762,-1.704683,1.229508,0.349359,no,3691,1139,2022,199,331
0,2412,7,0.363914,0.362078,-0.000063,0.000062,-1.059809,-1.103360,4.761905,4.963484,4.487609,1.313071,1.229508,0.363805,yes,4251,1310,2308,237,396
0,2412,8,0.363914,0.362078,-0.000063,0.000062,0.000000,0.000000,-4.329004,-3.946117,0.000000,0.000000,13.302752,3.952095,no,4251,1310,2308,237,396
0,2412,9,0.365223,0.363545,-0.000042,0.000085,-4.835056,-3.887119,-5.194805,-4.177895,5.426433,1.728604,13.302752,4.133748,no,4756,1452,2542,285,477
0,2412,10,0.365267,0.364137,-0.000033,0.000101,0.929445,0.668333,-3.463203,-2.505778,1.661730,0.561293,10.762332,3.532466,no,5240,1588,2773,326,553
0,2412,11,0.365486,0.364833,-0.000031,0.000108,1.781771,1.181204,-1.298701,-0.865406,-0.112402,-0.040422,7.860262,2.757435,no,5702,1718,2991,366,627
0,2412,12,0.366048,0.365655,-0.000025,0.000116,-0.448525,-0.271292,0.000000,0.000000,1.681400,0.628180,7.391304,2.714256,no,6144,1844,3199,405,696
0,2412,13,0.366006,0.366148,-0.000019,0.000126,1.135672,0.631580,3.463203,1.916260,2.114167,0.833718,2.489627,0.980688,no,6560,1975,3419,426,740
0,2412,14,0.364917,0.365240,-0.000026,0.000119,10.491220,5.253724,9.523810,4.779735,-5.770177,-2.461257,-1.984127,-0.836790,no,6955,2091,3634,447,783
0,2412,15,0.364170,0.364585,-0.000030,0.000112,8.713033,4.075638,8.658009,4.050446,-4.607430,-2.081866,-1.593625,-0.713949,no,7329,2201,3836,468,824
0,2412,16,0.364181,0.364656,-0.000026,0.000114,13.347927,5.778882,-0.432900,-0.194344,1.966443,0.930213,6.926407,3.235504,no,7683,2309,4023,489,862
0,2412,17,0.363375,0.364227,-0.000031,0.000112,17.116458,6.884792,1.731602,0.726083,-4.640770,-2.394905,6.008584,3.021295,no,8011,2409,4205,502,895
0,2412,18,0.363155,0.364324,-0.000030,0.000115,15.748535,5.995101,0.432900,0.172116,-0.148327,-0.081997,6.008584,3.277152,no,8316,2504,4369,516,927
0,2412,19,0.363647,0.365157,-0.000025,0.000120,12.789153,4.644792,2.164502,0.811109,2.907649,1.718076,5.106383,3.004222,no,8599,2597,4515,530,957
0,2412,20,0.363821,0.365584,-0.000022,0.000125,13.228118,4.547387,4.329004,1.528548,2.499645,1.624891,2.916667,1.894629,no,8856,2679,4649,543,985
0,2412,21,0.363886,0.365980,-0.000021,0.000128,10.703449,3.528283,3.896104,1.311879,-0.390268,-0.280347,2.489627,1.781214,no,9088,2754,4771,553,1010
0,2412,22,0.364291,0.366481,-0.000016,0.000133,11.333249,3.557175,5.627706,1.798558,4.240594,3.367459,1.229508,0.979279,yes,9303,2823,4880,566,1034
0,2412,23,0.364546,0.366573,-0.000012,0.000135,12.230761,3.659627,7.359307,2.236608,2.154276,1.929818,-0.803213,-0.720618,yes,9494,2882,4980,579,1053
0,2412,24,0.364107,0.366100,-0.000016,0.000131,15.264735,4.332885,6.926407,2.019723,-4.210124,-4.310565,-0.803213,-0.822723,no,9662,2931,5075,587,1069
0,2412,25,0.363627,0.365437,-0.000017,0.000127,14.159716,3.869570,10.822511,2.989837,-1.087106,-1.296970,-2.755906,-3.282534,yes,9804,2971,5159,594,1080
0,2412,26,0.363664,0.365128,-0.000014,0.000126,12.227539,3.231675,3.896104,1.059374,2.133282,3.068484,3.781513,5.458333,no,9924,3005,5225,604,1090
0,2412,27,0.363337,0.364522,-0.000016,0.000120,18.440810,4.596644,5.627706,1.464480,-2.016481,-3.575277,1.646091,2.960989,no,10021,3031,5284,610,1096
0,2412,28,0.363024,0.364081,-0.000019,0.000115,15.710555,3.807723,7.792208,1.940215,-2.795505,-6.518421,-1.200000,-2.829290,no,10093,3051,5329,613,1100
0,2412,29,0.363009,0.364003,-0.000017,0.000114,14.191829,3.326419,6.060606,1.461438,0.801455,2.915426,0.406504,1.471165,yes,10143,3066,5357,616,1104
0,2412,30,0.362868,0.363841,-0.000017,0.000113,10.864396,2.489390,6.926407,1.609465,-0.409729,-2.912846,-0.403226,-2.867188,no,10169,3073,5373,617,1106

2454 聯發科 tw tv1
win B&H
2454 聯發科 tw tv2
loss B&H
2454 聯發科 tw tv3
win B&H
2454 聯發科 tw tv4
win B&H
2454 聯發科 tw tv5
loss B&H
2454 聯發科 tw tv6
loss B&H
2454 聯發科 tw tv7
loss B&H
2454 聯發科 tw tv8
loss B&H
2454 聯發科 tw tv9
loss B&H
2454 聯發科 tw tv10
loss B&H
2454 聯發科 tw tv11
loss B&H
2454 聯發科 tw tv12
win B&H
2454 聯發科 tw tv13
loss B&H
2454 聯發科 tw tv14
win B&H
2454 聯發科 tw tv15
win B&H
2454 聯發科 tw tv16
win B&H
2454 聯發科 tw tv17
win B&H
2454 聯發科 tw tv18
win B&H
2454 聯發科 tw tv19
win B&H
2454 聯發科 tw tv20
win B&H
2454 聯發科 tw tv21
win B&H
2454 聯發科 tw tv22
win B&H
2454 聯發科 tw tv23
win B&H
2454 聯發科 tw tv24
loss B&H
2454 聯發科 tw tv25
win B&H
2454 聯發科 tw tv26
win B&H
2454 聯發科 tw tv27
loss B&H
2454 聯發科 tw tv28
loss B&H
2454 聯發科 tw tv29
loss B&H
2454 聯發科 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2454,1,0.467438,0.442238,0.000827,0.000238,6.080028,90.921731,-6.521739,-52.237141,62.992300,12.340169,28.636364,6.181495,yes,691,245,309,78,59
0,2454,2,0.467438,0.442238,0.000827,0.000238,0.000000,0.000000,-16.260870,-48.699815,0.000000,0.000000,49.894068,10.484598,no,691,245,309,78,59
0,2454,3,0.474510,0.445783,0.001146,0.000565,8.179460,21.438884,-27.652174,-55.053254,119.343451,22.182078,69.867947,14.470187,yes,1275,407,506,198,164
0,2454,4,0.471827,0.442351,0.001203,0.000629,10.288962,19.738589,-26.434783,-43.146750,108.390474,21.428401,67.852906,14.677315,yes,1899,587,740,309,263
0,2454,5,0.468800,0.438421,0.001199,0.000678,4.551998,6.739244,-41.739130,-54.684167,87.241233,18.789179,108.702065,22.380782,no,2500,744,953,428,375
0,2454,6,0.468800,0.438421,0.001199,0.000678,0.000000,0.000000,-40.608696,-46.968711,0.000000,0.000000,103.890490,22.545967,no,2500,744,953,428,375
0,2454,7,0.469241,0.438376,0.001269,0.000764,2.634477,2.744820,-46.086957,-47.445874,115.793171,25.679927,124.247227,27.123400,no,3056,907,1162,527,460
0,2454,8,0.469342,0.438712,0.001320,0.000848,4.404790,3.999405,-50.782609,-47.530645,117.299733,27.234409,155.877034,33.853708,no,3588,1063,1360,621,544
0,2454,9,0.468137,0.437967,0.001327,0.000866,3.610502,2.878121,-39.391304,-33.007228,87.402945,22.593664,95.983380,24.386661,no,4080,1232,1581,678,589
0,2454,10,0.466272,0.436721,0.001287,0.000836,1.622147,1.165312,-42.956522,-33.247380,47.854763,14.203633,119.040248,30.511756,no,4566,1401,1807,728,630
0,2454,11,0.464825,0.435812,0.001283,0.000833,-6.518025,-4.382641,-39.739130,-28.592496,67.167884,20.287479,91.474966,26.303516,no,5032,1565,2026,774,667
0,2454,12,0.466288,0.436693,0.001358,0.000902,-1.896643,-1.150512,-37.130435,-24.456999,126.994904,36.052024,78.887484,24.410960,yes,5458,1690,2180,855,733
0,2454,13,0.466089,0.436757,0.001366,0.000909,1.866336,1.036265,-31.565217,-19.059996,79.257698,26.064490,87.915007,28.446334,no,5883,1837,2369,905,772
0,2454,14,0.466592,0.437431,0.001418,0.000956,0.470012,0.240953,-41.130435,-23.809791,122.847473,39.932966,111.826347,36.988397,yes,6286,1968,2531,965,822
0,2454,15,0.467449,0.438275,0.001469,0.000999,7.801390,3.657389,-32.173913,-16.942744,124.893478,43.544947,84.725849,31.484954,yes,6651,2084,2671,1025,871
0,2454,16,0.468477,0.439464,0.001521,0.001052,5.935039,2.618990,-39.478261,-20.162049,127.245885,47.741931,104.479769,40.509422,yes,6995,2196,2801,1081,917
0,2454,17,0.469006,0.440581,0.001562,0.001101,-7.310253,-3.148355,-39.913043,-19.317946,108.443272,45.452960,103.890490,43.823560,yes,7324,2306,2928,1129,961
0,2454,18,0.469840,0.441916,0.001606,0.001146,12.305223,4.728393,-36.086957,-16.323337,112.250050,51.574595,89.932886,42.548696,yes,7626,2408,3041,1175,1002
0,2454,19,0.470283,0.442713,0.001648,0.001184,15.386682,5.547501,-24.521739,-10.069118,107.611077,54.367032,62.643678,33.520094,yes,7908,2500,3147,1219,1042
0,2454,20,0.470912,0.443267,0.001686,0.001217,-0.108338,-0.038793,-18.000000,-6.857203,99.555884,56.999061,50.371945,30.515866,yes,8165,2594,3258,1251,1062
0,2454,21,0.470945,0.443577,0.001722,0.001258,19.793113,6.351928,-19.478261,-7.121273,92.056255,59.767006,53.470716,36.005598,yes,8398,2669,3348,1286,1095
0,2454,22,0.471148,0.444138,0.001758,0.001302,19.739212,6.040634,-15.652174,-5.391309,91.438717,67.845546,46.936656,35.919262,yes,8613,2739,3428,1319,1127
0,2454,23,0.470922,0.444075,0.001763,0.001316,36.464019,10.168534,-2.173913,-0.682295,40.507904,35.661813,26.339286,23.327340,yes,8804,2803,3509,1343,1149
0,2454,24,0.470687,0.444272,0.001759,0.001331,53.013612,13.541956,-12.608696,-3.944179,30.021010,30.856215,39.408867,40.543148,no,8972,2862,3580,1361,1169
0,2454,25,0.470601,0.444563,0.001765,0.001357,45.501700,11.350598,7.391304,2.065394,31.261586,38.386366,11.417323,13.782699,yes,9116,2911,3637,1379,1189
0,2454,26,0.470983,0.444965,0.001784,0.001386,57.914591,13.424594,17.391304,4.520000,35.573188,54.614017,-0.352113,-0.503778,yes,9236,2947,3676,1403,1210
0,2454,27,0.471017,0.445342,0.001785,0.001403,92.123475,18.933091,-2.173913,-0.581934,15.071243,28.517405,20.425532,39.400067,no,9333,2978,3709,1418,1228
0,2454,28,0.471132,0.445747,0.001795,0.001420,82.909192,16.723387,-2.173913,-0.561293,22.937298,63.384262,25.221239,70.692962,no,9405,3003,3734,1428,1240
0,2454,29,0.471074,0.445872,0.001794,0.001423,112.511844,20.427206,15.652174,3.650683,6.757029,26.539851,8.015267,31.991669,no,9455,3019,3752,1435,1249
0,2454,30,0.470942,0.445900,0.001786,0.001420,78.879214,14.871674,11.304348,2.586210,-2.764290,-18.276737,10.546875,105.842281,no,9481,3029,3764,1436,1252

2881 富邦金 tw tv1
win B&H
2881 富邦金 tw tv2
win B&H
2881 富邦金 tw tv3
win B&H
2881 富邦金 tw tv4
win B&H
2881 富邦金 tw tv5
win B&H
2881 富邦金 tw tv6
win B&H
2881 富邦金 tw tv7
loss B&H
2881 富邦金 tw tv8
loss B&H
2881 富邦金 tw tv9
loss B&H
2881 富邦金 tw tv10
win B&H
2881 富邦金 tw tv11
win B&H
2881 富邦金 tw tv12
win B&H
2881 富邦金 tw tv13
loss B&H
2881 富邦金 tw tv14
win B&H
2881 富邦金 tw tv15
win B&H
2881 富邦金 tw tv16
win B&H
2881 富邦金 tw tv17
win B&H
2881 富邦金 tw tv18
win B&H
2881 富邦金 tw tv19
win B&H
2881 富邦金 tw tv20
win B&H
2881 富邦金 tw tv21
win B&H
2881 富邦金 tw tv22
win B&H
2881 富邦金 tw tv23
win B&H
2881 富邦金 tw tv24
win B&H
2881 富邦金 tw tv25
win B&H
2881 富邦金 tw tv26
win B&H
2881 富邦金 tw tv27
loss B&H
2881 富邦金 tw tv28
win B&H
2881 富邦金 tw tv29
win B&H
2881 富邦金 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2881,1,0.514050,0.514754,0.000988,0.001671,9.682816,175.282982,0.398406,4.452763,80.069193,15.038154,17.120623,3.835882,yes,605,157,148,154,146
0,2881,2,0.518072,0.523810,0.001185,0.001956,17.000455,80.495597,-3.452855,-12.380241,131.954509,23.030064,24.209078,5.485605,yes,1245,319,290,326,310
0,2881,3,0.514846,0.523757,0.001162,0.002012,31.007526,94.890526,-0.265604,-0.654918,97.597241,18.971267,22.192152,5.244966,yes,1886,474,431,497,484
0,2881,4,0.511386,0.521138,0.001181,0.002030,28.323260,58.204438,-17.928287,-30.470974,112.160814,22.005514,49.256198,11.171281,yes,2503,641,589,639,634
0,2881,5,0.507578,0.517972,0.001124,0.001960,27.532203,42.805647,-17.795485,-24.956641,62.680132,14.291359,45.880452,10.922286,yes,3101,807,751,767,776
0,2881,6,0.505444,0.518438,0.001121,0.002003,41.245173,52.256757,-25.498008,-30.115913,83.275118,18.874115,59.540636,14.260887,yes,3674,956,888,901,929
0,2881,7,0.501537,0.514901,0.001076,0.001923,48.318845,50.754597,-24.833997,-25.715471,49.444383,12.680838,59.540636,14.891323,no,4229,1123,1058,998,1050
0,2881,8,0.498739,0.513917,0.001073,0.001942,57.358539,51.049896,-32.669323,-30.222207,68.255027,17.524393,82.424242,20.510703,no,4758,1274,1205,1099,1180
0,2881,9,0.496193,0.511828,0.001037,0.001890,49.932396,38.266314,-25.232404,-20.755207,40.317562,11.612288,60.106383,16.491623,no,5254,1428,1362,1179,1285
0,2881,10,0.495642,0.511955,0.001050,0.001906,49.738407,33.733408,-24.833997,-18.579185,73.188379,20.505361,60.676157,17.475086,yes,5736,1563,1490,1280,1403
0,2881,11,0.494677,0.510234,0.001049,0.001862,47.306100,29.375265,-20.584329,-14.207984,57.321248,17.690768,48.032787,15.144013,yes,6200,1720,1651,1347,1482
0,2881,12,0.493980,0.509111,0.001050,0.001832,48.632502,27.060690,-20.318725,-12.825801,58.272792,18.819793,53.050847,17.332061,yes,6644,1872,1805,1410,1557
0,2881,13,0.493348,0.508547,0.001053,0.001810,50.357485,25.531043,-24.966799,-14.797753,55.700882,19.209479,58.978873,20.199213,no,7066,2023,1955,1463,1625
0,2881,14,0.493435,0.508443,0.001068,0.001805,40.292324,18.977115,-20.982736,-11.385048,66.554600,23.850839,52.533784,19.367362,yes,7464,2168,2096,1515,1685
0,2881,15,0.493303,0.508041,0.001080,0.001799,45.477565,19.631497,-17.928287,-9.015128,60.639047,23.541606,46.590909,18.600543,yes,7839,2306,2233,1561,1739
0,2881,16,0.493102,0.507606,0.001089,0.001793,52.617357,20.872565,-13.944223,-6.512088,53.377608,22.553172,42.204724,18.224175,yes,8191,2436,2363,1603,1789
0,2881,17,0.492721,0.506964,0.001107,0.001801,62.452368,22.687677,-15.936255,-7.054201,63.538245,28.520322,43.789809,20.353990,yes,8518,2548,2478,1649,1843
0,2881,18,0.493085,0.507266,0.001138,0.001824,60.082515,20.600797,-19.389110,-8.222772,80.411200,38.554074,48.519737,24.432366,yes,8822,2653,2577,1697,1895
0,2881,19,0.494014,0.507928,0.001172,0.001848,58.181035,18.885834,-19.123506,-7.694754,84.148480,43.747378,47.308320,25.887943,yes,9105,2755,2669,1743,1938
0,2881,20,0.494873,0.508841,0.001204,0.001873,60.857046,18.548529,-16.069057,-6.077948,78.694283,46.079871,43.561208,26.625634,yes,9362,2849,2750,1784,1979
0,2881,21,0.495675,0.509326,0.001222,0.001874,65.002323,18.621771,-14.873838,-5.343290,54.376067,36.581145,40.873635,27.894570,yes,9595,2949,2841,1807,1998
0,2881,22,0.496738,0.509879,0.001247,0.001881,71.179611,19.126296,-12.483400,-4.248470,64.507934,48.731230,36.611195,28.246650,yes,9810,3045,2927,1828,2010
0,2881,23,0.497550,0.510031,0.001268,0.001881,82.500810,20.609871,-7.569721,-2.422140,55.656523,48.708266,30.869565,27.285982,yes,10001,3127,3004,1849,2021
0,2881,24,0.498082,0.510041,0.001287,0.001883,91.007526,21.315292,-10.225764,-3.169511,45.101142,46.424592,30.115274,30.953399,yes,10169,3200,3074,1865,2030
0,2881,25,0.498691,0.510242,0.001303,0.001883,101.020415,22.161891,-2.523240,-0.729992,39.539107,48.871722,22.357724,27.250439,yes,10313,3263,3132,1880,2038
0,2881,26,0.498898,0.509934,0.001310,0.001871,120.117463,24.300727,12.749004,3.363702,22.575257,33.837174,5.000000,7.235659,yes,10433,3311,3182,1894,2046
0,2881,27,0.498765,0.509354,0.001299,0.001849,181.163861,31.588491,14.209827,3.591169,1.695060,3.049657,4.032258,7.320646,no,10530,3349,3226,1903,2052
0,2881,28,0.498585,0.508814,0.001294,0.001837,171.197313,29.111025,15.139442,3.676266,4.114466,10.060151,4.032258,9.853665,yes,10602,3377,3260,1909,2056
0,2881,29,0.498216,0.508081,0.001291,0.001828,172.627363,28.056222,20.717131,4.751969,1.231599,4.505213,-3.215434,-11.099954,yes,10652,3395,3287,1912,2058
0,2881,30,0.498033,0.507757,0.001289,0.001823,190.864296,28.987821,20.185923,4.481150,0.973269,7.222565,0.221976,1.609264,yes,10678,3404,3300,1914,2060

2882 國泰金 tw tv1
win B&H
2882 國泰金 tw tv2
win B&H
2882 國泰金 tw tv3
win B&H
2882 國泰金 tw tv4
win B&H
2882 國泰金 tw tv5
win B&H
2882 國泰金 tw tv6
loss B&H
2882 國泰金 tw tv7
win B&H
2882 國泰金 tw tv8
win B&H
2882 國泰金 tw tv9
win B&H
2882 國泰金 tw tv10
win B&H
2882 國泰金 tw tv11
win B&H
2882 國泰金 tw tv12
loss B&H
2882 國泰金 tw tv13
win B&H
2882 國泰金 tw tv14
loss B&H
2882 國泰金 tw tv15
win B&H
2882 國泰金 tw tv16
win B&H
2882 國泰金 tw tv17
win B&H
2882 國泰金 tw tv18
win B&H
2882 國泰金 tw tv19
win B&H
2882 國泰金 tw tv20
win B&H
2882 國泰金 tw tv21
win B&H
2882 國泰金 tw tv22
win B&H
2882 國泰金 tw tv23
win B&H
2882 國泰金 tw tv24
win B&H
2882 國泰金 tw tv25
win B&H
2882 國泰金 tw tv26
win B&H
2882 國泰金 tw tv27
win B&H
2882 國泰金 tw tv28
win B&H
2882 國泰金 tw tv29
win B&H
2882 國泰金 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2882,1,0.494768,0.495708,0.001002,0.000858,12.646056,268.661138,2.759740,34.753152,88.197205,16.254242,3.957382,0.928703,yes,669,231,235,100,103
0,2882,2,0.495146,0.495736,0.001044,0.000893,21.032743,105.028299,-2.110390,-7.709169,99.109909,18.488673,11.601307,2.740714,yes,1339,465,473,198,203
0,2882,3,0.497238,0.495387,0.001061,0.000885,23.855828,69.651725,3.896104,9.903100,96.400162,18.787016,8.757962,2.164446,yes,1991,698,711,292,290
0,2882,4,0.497712,0.494606,0.001069,0.000905,22.435729,45.110788,-14.123377,-24.426673,96.343758,19.531388,30.592734,7.312978,yes,2622,917,937,388,380
0,2882,5,0.498142,0.494097,0.001120,0.000948,22.653214,34.872978,-13.311688,-18.884288,116.706251,23.651675,27.663551,6.934147,yes,3230,1130,1157,479,464
0,2882,6,0.496590,0.492499,0.001053,0.000919,31.568408,39.654247,-26.136364,-30.844192,44.050967,10.978550,50.275028,12.326404,no,3812,1346,1387,547,532
0,2882,7,0.496227,0.491725,0.001073,0.000946,40.056639,42.019934,-28.490260,-29.474328,90.836596,21.172529,55.051078,13.920887,yes,4373,1545,1597,625,606
0,2882,8,0.496130,0.492045,0.001088,0.000983,36.226385,32.478009,-34.253247,-31.717149,85.563359,21.150490,72.474747,18.431312,yes,4910,1732,1788,704,686
0,2882,9,0.495667,0.491547,0.001099,0.001004,48.493976,37.204093,-32.224026,-26.741063,77.234044,20.395398,61.084906,16.722055,yes,5423,1919,1985,769,750
0,2882,10,0.494984,0.491713,0.001115,0.001047,43.998326,30.022155,-34.821429,-26.522312,77.434009,21.500638,70.112080,19.774091,yes,5881,2047,2116,864,854
0,2882,11,0.494722,0.491917,0.001127,0.001071,44.365188,27.652059,-31.818182,-22.481571,78.419697,23.137485,59.953162,18.394808,yes,6347,2191,2263,949,944
0,2882,12,0.494187,0.491557,0.001122,0.001069,58.455294,32.070846,-29.464286,-19.017516,58.439063,18.866656,59.766082,19.239581,no,6795,2358,2439,1000,998
0,2882,13,0.493344,0.491478,0.001134,0.001098,50.760320,25.718438,-32.142857,-19.441605,69.533381,23.304812,62.619048,21.283985,yes,7212,2480,2566,1078,1088
0,2882,14,0.492843,0.490780,0.001134,0.001097,59.416657,27.042212,-29.383117,-16.352285,53.713749,19.753678,58.652729,21.352266,no,7615,2635,2734,1118,1128
0,2882,15,0.492681,0.490576,0.001139,0.001102,59.441263,24.991156,-27.597403,-14.308555,56.155234,21.991521,54.002255,21.238456,yes,7993,2785,2892,1153,1163
0,2882,16,0.492573,0.490186,0.001154,0.001116,60.372609,23.589076,-27.759740,-13.567547,66.475240,27.422316,52.625698,22.267141,yes,8348,2922,3039,1190,1197
0,2882,17,0.492327,0.489879,0.001174,0.001140,51.590166,19.161406,-27.516234,-12.681795,68.717711,30.580863,53.483146,24.426691,yes,8667,3025,3150,1242,1250
0,2882,18,0.491582,0.489262,0.001189,0.001162,59.161421,20.324064,-27.678571,-12.103093,60.047139,29.680253,53.483146,26.713537,yes,8969,3121,3258,1288,1302
0,2882,19,0.491245,0.488909,0.001211,0.001186,58.725734,19.040107,-27.191558,-11.282626,66.963716,35.616689,50.606395,27.555558,yes,9252,3218,3364,1327,1343
0,2882,20,0.491324,0.489092,0.001234,0.001210,59.613790,18.219733,-27.191558,-10.737854,67.453778,40.013451,52.285396,31.597729,yes,9509,3318,3466,1354,1371
0,2882,21,0.491374,0.489549,0.001260,0.001240,52.794698,15.552986,-27.759740,-10.495772,67.762107,44.983533,53.655793,36.123332,yes,9738,3396,3541,1389,1412
0,2882,22,0.491510,0.489796,0.001284,0.001266,62.503073,17.125810,-27.678571,-10.012963,63.014459,47.653457,51.777778,39.478670,yes,9953,3480,3625,1412,1436
0,2882,23,0.491424,0.489982,0.001300,0.001286,72.469031,18.504404,-21.185065,-7.147414,49.465393,43.392870,41.995842,36.949468,yes,10144,3546,3691,1439,1468
0,2882,24,0.491369,0.490001,0.001320,0.001309,77.567105,18.700954,-20.616883,-6.661458,45.967079,47.319805,34.448819,35.423030,yes,10312,3602,3749,1465,1496
0,2882,25,0.491344,0.490122,0.001338,0.001328,77.936006,17.963594,-8.766234,-2.595946,43.160100,53.497109,20.458554,24.895110,yes,10455,3647,3794,1490,1524
0,2882,26,0.491299,0.490282,0.001349,0.001340,96.009459,20.388233,-0.487013,-0.134512,28.517568,43.223567,9.630819,14.071277,yes,10574,3683,3829,1512,1550
0,2882,27,0.491051,0.490364,0.001348,0.001346,136.881595,25.734381,-1.785714,-0.477325,13.116118,24.640962,11.967213,22.387446,yes,10671,3715,3861,1525,1570
0,2882,28,0.490831,0.490111,0.001348,0.001347,148.409600,26.241358,2.597403,0.658857,10.614466,27.103250,8.240887,20.714810,yes,10743,3742,3893,1531,1577
0,2882,29,0.490456,0.489892,0.001348,0.001349,140.668035,24.179062,10.876623,2.578522,4.348254,16.559230,-1.443001,-5.098104,yes,10792,3756,3911,1537,1588
0,2882,30,0.490247,0.489913,0.001347,0.001351,148.246340,24.206481,9.253247,2.132310,2.794435,21.949816,1.335312,10.021563,yes,10817,3764,3919,1539,1595

2891 中信金 tw tv1
win B&H
2891 中信金 tw tv2
win B&H
2891 中信金 tw tv3
win B&H
2891 中信金 tw tv4
win B&H
2891 中信金 tw tv5
win B&H
2891 中信金 tw tv6
win B&H
2891 中信金 tw tv7
win B&H
2891 中信金 tw tv8
loss B&H
2891 中信金 tw tv9
loss B&H
2891 中信金 tw tv10
loss B&H
2891 中信金 tw tv11
loss B&H
2891 中信金 tw tv12
loss B&H
2891 中信金 tw tv13
loss B&H
2891 中信金 tw tv14
loss B&H
2891 中信金 tw tv15
loss B&H
2891 中信金 tw tv16
loss B&H
2891 中信金 tw tv17
loss B&H
2891 中信金 tw tv18
win B&H
2891 中信金 tw tv19
win B&H
2891 中信金 tw tv20
win B&H
2891 中信金 tw tv21
win B&H
2891 中信金 tw tv22
win B&H
2891 中信金 tw tv23
win B&H
2891 中信金 tw tv24
win B&H
2891 中信金 tw tv25
win B&H
2891 中信金 tw tv26
win B&H
2891 中信金 tw tv27
win B&H
2891 中信金 tw tv28
loss B&H
2891 中信金 tw tv29
loss B&H
2891 中信金 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2891,1,0.487616,0.504892,0.000878,0.001142,12.472845,262.497489,7.184466,113.865265,65.735838,12.787705,37.192982,7.822757,yes,646,258,253,57,78
0,2891,2,0.492272,0.508325,0.000972,0.001236,22.362086,113.627371,2.912621,11.403023,91.773381,17.397937,45.895522,9.751171,yes,1294,519,502,118,155
0,2891,3,0.494020,0.508553,0.001002,0.001256,24.876364,73.126264,13.980583,38.167432,85.678938,17.098355,36.000000,8.158469,yes,1923,773,747,177,226
0,2891,4,0.493910,0.509596,0.001063,0.001326,27.721007,56.841376,-1.165049,-2.132524,109.474654,21.595134,53.634578,12.024478,yes,2545,1009,971,248,317
0,2891,5,0.493325,0.509885,0.001070,0.001341,42.900265,68.710232,2.135922,3.144860,85.127894,18.419616,49.236641,11.617045,yes,3146,1238,1190,314,404
0,2891,6,0.492617,0.510616,0.001080,0.001373,34.733474,43.754800,-10.873786,-13.076526,87.052450,19.568238,70.370370,16.422714,yes,3725,1467,1406,368,484
0,2891,7,0.491355,0.510192,0.001083,0.001393,50.228049,52.775878,-11.067961,-11.497973,76.942358,18.480842,68.172043,16.704396,yes,4280,1677,1610,426,567
0,2891,8,0.490758,0.510425,0.001089,0.001424,49.927331,44.546337,-20.582524,-18.913431,77.569486,19.506127,94.527363,22.937299,no,4815,1885,1808,478,644
0,2891,9,0.490049,0.510654,0.001092,0.001449,55.838038,42.606322,-15.728155,-12.794074,68.558793,18.451618,77.727273,20.503961,no,5326,2085,1998,525,718
0,2891,10,0.489420,0.510892,0.001096,0.001469,57.745804,38.844802,-14.368932,-10.567663,69.991188,19.745176,78.538813,21.757047,no,5813,2275,2178,570,790
0,2891,11,0.488535,0.510599,0.001095,0.001477,65.176377,39.609589,-9.902913,-6.698885,62.323296,19.022499,68.534483,20.640059,no,6280,2457,2355,611,857
0,2891,12,0.488704,0.511473,0.001093,0.001501,56.877201,31.274400,-11.650485,-7.212326,56.959929,18.448678,72.246696,22.655934,no,6728,2608,2491,680,949
0,2891,13,0.488327,0.512177,0.001083,0.001521,71.208372,34.956980,-15.145631,-8.749702,44.815597,15.829620,80.184332,26.322701,no,7153,2755,2624,738,1036
0,2891,14,0.488551,0.513016,0.001082,0.001540,66.070595,29.736647,-9.514563,-5.001987,49.204103,18.267789,67.811159,24.241772,no,7555,2897,2750,794,1114
0,2891,15,0.488589,0.513463,0.001086,0.001549,76.702286,31.288249,-3.883495,-1.876199,51.408985,20.323602,58.299595,22.735875,no,7931,3051,2891,824,1165
0,2891,16,0.488835,0.514065,0.001090,0.001555,80.711324,30.386274,1.165049,0.520738,45.789706,19.632034,49.236641,20.968658,no,8285,3198,3023,852,1212
0,2891,17,0.489088,0.514806,0.001099,0.001567,76.907132,27.174795,-7.378641,-3.178474,49.351087,22.706463,66.382979,29.655932,no,8614,3338,3146,875,1255
0,2891,18,0.489796,0.515746,0.001116,0.001584,69.621170,23.411886,-4.854369,-1.961534,60.306271,29.796244,59.591837,29.476249,yes,8918,3472,3260,896,1290
0,2891,19,0.490652,0.516741,0.001135,0.001605,67.032381,21.353010,-4.077670,-1.558257,57.015155,30.754258,54.240631,29.376084,yes,9200,3596,3363,918,1323
0,2891,20,0.491540,0.517877,0.001154,0.001626,70.748302,21.108054,6.796117,2.381516,57.260464,34.388784,42.700730,26.129624,yes,9456,3708,3452,940,1356
0,2891,21,0.492155,0.518670,0.001171,0.001647,76.950213,21.483573,8.932039,2.960376,50.928288,34.384183,38.898757,26.604780,yes,9688,3806,3532,962,1388
0,2891,22,0.492830,0.519387,0.001194,0.001670,75.438116,20.083190,9.708738,3.062766,61.265259,46.388592,36.236934,27.966385,yes,9902,3898,3607,982,1415
0,2891,23,0.493262,0.519739,0.001211,0.001681,91.504211,22.432672,23.883495,6.898913,45.647895,40.104070,23.343849,20.701845,yes,10092,3976,3674,1002,1440
0,2891,24,0.493665,0.519923,0.001236,0.001702,77.444266,18.676430,20.970874,5.848983,53.516874,55.130257,14.160584,14.529935,yes,10260,4045,3735,1020,1460
0,2891,25,0.494137,0.520137,0.001240,0.001706,100.395624,22.052917,37.475728,9.553925,21.861413,26.634230,7.417582,8.921526,yes,10404,4094,3777,1047,1486
0,2891,26,0.494299,0.519724,0.001256,0.001709,105.341721,21.942038,55.533981,12.950556,35.663648,54.761751,-2.493766,-3.551302,yes,10524,4137,3823,1065,1499
0,2891,27,0.494210,0.519353,0.001258,0.001710,135.967763,25.605396,34.757282,8.243456,16.165232,30.709255,13.333333,25.069054,yes,10621,4173,3862,1076,1510
0,2891,28,0.494436,0.519516,0.001265,0.001720,132.138141,24.070001,26.407767,6.185205,17.354640,46.294178,19.571865,52.950878,no,10693,4206,3890,1081,1516
0,2891,29,0.494648,0.519602,0.001263,0.001723,138.541871,23.907652,40.194175,8.687598,5.709684,22.127422,6.830601,26.854074,no,10743,4228,3909,1086,1520
0,2891,30,0.494753,0.519603,0.001266,0.001726,159.399614,25.514724,45.048544,9.271398,6.204164,54.247848,2.894737,22.809159,yes,10769,4241,3921,1087,1520

6505 台塑化 tw tv1
win B&H
6505 台塑化 tw tv2
win B&H
6505 台塑化 tw tv3
win B&H
6505 台塑化 tw tv4
win B&H
6505 台塑化 tw tv5
win B&H
6505 台塑化 tw tv6
win B&H
6505 台塑化 tw tv7
win B&H
6505 台塑化 tw tv8
win B&H
6505 台塑化 tw tv9
win B&H
6505 台塑化 tw tv10
win B&H
6505 台塑化 tw tv11
win B&H
6505 台塑化 tw tv12
win B&H
6505 台塑化 tw tv13
win B&H
6505 台塑化 tw tv14
win B&H
6505 台塑化 tw tv15
win B&H
6505 台塑化 tw tv16
win B&H
6505 台塑化 tw tv17
win B&H
6505 台塑化 tw tv18
win B&H
6505 台塑化 tw tv19
win B&H
6505 台塑化 tw tv20
win B&H
6505 台塑化 tw tv21
win B&H
6505 台塑化 tw tv22
win B&H
6505 台塑化 tw tv23
win B&H
6505 台塑化 tw tv24
win B&H
6505 台塑化 tw tv25
win B&H
6505 台塑化 tw tv26
win B&H
6505 台塑化 tw tv27
win B&H
6505 台塑化 tw tv28
win B&H
6505 台塑化 tw tv29
win B&H
6505 台塑化 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,6505,1,0.504836,0.448980,0.001608,0.000175,5.025543,71.126951,0.313152,3.485053,122.050919,20.926058,-64.672802,-21.951192,yes,517,132,162,129,94
0,6505,2,0.499081,0.449527,0.001378,0.000104,2.788816,10.899788,-0.104384,-0.392044,86.644657,16.616615,-63.707983,-22.094814,yes,1088,285,349,258,196
0,6505,3,0.512869,0.463263,0.001620,0.000443,3.764883,9.560482,-3.444676,-8.295992,184.947212,30.614846,-62.363834,-22.061221,yes,1593,372,431,445,345
0,6505,4,0.520115,0.469979,0.001739,0.000614,6.884483,13.028013,-1.461378,-2.671582,176.630558,30.873232,-63.477801,-23.382541,yes,2088,454,512,632,490
0,6505,5,0.518307,0.466563,0.001721,0.000544,-0.544333,-0.796501,-0.835073,-1.221100,133.458744,26.205213,-63.707983,-24.288155,yes,2622,600,686,759,577
0,6505,6,0.518307,0.466563,0.001721,0.000544,0.000000,0.000000,-11.795407,-14.169536,0.000000,0.000000,-59.112426,-22.526750,yes,2622,600,686,759,577
0,6505,7,0.517286,0.464691,0.001723,0.000525,0.706035,0.735317,-14.405010,-14.953401,131.350348,28.306924,-57.762836,-22.595220,yes,3124,737,849,879,659
0,6505,8,0.516888,0.463012,0.001735,0.000505,3.063906,2.783569,-16.492693,-15.123189,135.537975,30.456940,-56.265823,-22.637474,yes,3612,870,1009,997,736
0,6505,9,0.515545,0.460222,0.001718,0.000454,18.018703,14.172279,-11.169102,-9.039835,101.109207,25.432582,-59.778813,-25.575642,yes,4085,995,1167,1111,812
0,6505,10,0.514644,0.458659,0.001719,0.000439,13.302720,9.408998,-16.179541,-11.933239,114.245637,29.534425,-56.649937,-24.714127,yes,4541,1115,1316,1222,888
0,6505,11,0.512347,0.455387,0.001690,0.000388,17.351463,11.225263,-13.256785,-9.022851,79.054953,23.294914,-59.160757,-27.525087,yes,4981,1230,1471,1322,958
0,6505,12,0.511469,0.452664,0.001687,0.000354,23.308840,13.498288,-11.169102,-6.907133,96.367518,28.844210,-58.672249,-28.241030,yes,5406,1334,1613,1431,1028
0,6505,13,0.510401,0.449608,0.001683,0.000320,27.561941,14.535961,-11.273486,-6.451112,90.923945,29.258634,-59.825581,-30.365054,yes,5817,1432,1753,1537,1095
0,6505,14,0.509659,0.447114,0.001684,0.000288,26.757165,12.940431,-10.125261,-5.331594,89.049374,30.607562,-59.448357,-31.508372,yes,6212,1526,1887,1640,1159
0,6505,15,0.509041,0.444659,0.001680,0.000241,37.210672,16.331122,-8.350731,-4.084033,78.094799,29.358475,-60.287356,-33.760790,yes,6581,1611,2012,1739,1219
0,6505,16,0.508511,0.442584,0.001681,0.000205,36.702173,15.048644,-17.223382,-8.126572,77.576360,31.394014,-56.321113,-32.553516,yes,6932,1692,2131,1833,1276
0,6505,17,0.506889,0.439851,0.001663,0.000156,37.926237,14.511170,-16.075157,-7.118950,47.231712,21.815093,-56.595477,-34.672082,yes,7258,1766,2249,1913,1330
0,6505,18,0.505161,0.436589,0.001644,0.000102,39.940594,14.314367,-15.866388,-6.646619,38.589202,19.763406,-56.973848,-37.253571,yes,7556,1828,2359,1989,1380
0,6505,19,0.503700,0.433993,0.001634,0.000059,42.752828,14.371125,-17.014614,-6.794031,45.303813,24.866994,-57.292954,-39.689736,yes,7838,1887,2461,2061,1429
0,6505,20,0.502718,0.431495,0.001633,0.000018,38.232637,12.287704,-14.196242,-5.333073,47.648625,28.967825,-57.762836,-43.031483,yes,8094,1940,2556,2129,1469
0,6505,21,0.501922,0.429527,0.001638,-0.000018,38.359550,11.708008,-17.536534,-6.363518,48.989232,33.142383,-55.818414,-44.370975,yes,8326,1990,2643,2189,1504
0,6505,22,0.502166,0.428151,0.001660,-0.000040,43.293794,12.425474,-22.964509,-8.143763,68.980458,51.947090,-53.373819,-45.581974,yes,8541,2035,2718,2254,1534
0,6505,23,0.502519,0.427160,0.001682,-0.000061,46.544619,12.641623,-28.914405,-10.085318,65.008741,56.696615,-49.635569,-45.941300,yes,8732,2076,2784,2312,1560
0,6505,24,0.502472,0.425485,0.001697,-0.000098,62.697529,15.641508,-25.678497,-8.479666,46.982436,48.369655,-52.410468,-53.264612,yes,8900,2107,2845,2365,1583
0,6505,25,0.502875,0.424423,0.001718,-0.000125,59.465172,14.314719,-29.645094,-9.589074,52.747968,65.853340,-48.586310,-54.820888,yes,9044,2134,2894,2414,1602
0,6505,26,0.503492,0.423516,0.001752,-0.000141,50.144901,11.857714,-31.732777,-9.990062,65.051067,104.922616,-47.412481,-60.156751,yes,9164,2154,2932,2460,1618
0,6505,27,0.503833,0.422283,0.001779,-0.000166,65.063130,14.234000,-33.611691,-10.307170,52.629491,112.914333,-45.245642,-65.920518,yes,9261,2168,2966,2498,1629
0,6505,28,0.504018,0.421500,0.001794,-0.000187,83.612975,16.838241,-47.077244,-15.037848,27.951419,79.673735,-32.519531,-60.744991,yes,9333,2180,2992,2524,1637
0,6505,29,0.504636,0.421276,0.001819,-0.000193,103.364426,19.127769,-48.538622,-15.109629,38.551433,223.444435,-29.417773,-71.469901,yes,9383,2186,3003,2549,1645
0,6505,30,0.505048,0.421205,0.001836,-0.000198,129.299997,21.877670,-54.123173,-16.953703,23.017715,344.392910,-20.756881,-81.270627,yes,9409,2189,3008,2563,1649

3231 緯創 tw tv1
loss B&H
3231 緯創 tw tv2
loss B&H
3231 緯創 tw tv3
loss B&H
3231 緯創 tw tv4
loss B&H
3231 緯創 tw tv5
loss B&H
3231 緯創 tw tv6
loss B&H
3231 緯創 tw tv7
loss B&H
3231 緯創 tw tv8
loss B&H
3231 緯創 tw tv9
loss B&H
3231 緯創 tw tv10
loss B&H
3231 緯創 tw tv11
loss B&H
3231 緯創 tw tv12
loss B&H
3231 緯創 tw tv13
loss B&H
3231 緯創 tw tv14
loss B&H
3231 緯創 tw tv15
loss B&H
3231 緯創 tw tv16
loss B&H
3231 緯創 tw tv17
loss B&H
3231 緯創 tw tv18
loss B&H
3231 緯創 tw tv19
loss B&H
3231 緯創 tw tv20
loss B&H
3231 緯創 tw tv21
loss B&H
3231 緯創 tw tv22
loss B&H
3231 緯創 tw tv23
win B&H
3231 緯創 tw tv24
loss B&H
3231 緯創 tw tv25
loss B&H
3231 緯創 tw tv26
loss B&H
3231 緯創 tw tv27
loss B&H
3231 緯創 tw tv28
loss B&H
3231 緯創 tw tv29
loss B&H
3231 緯創 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,3231,1,0.465517,0.458716,0.000517,0.000133,9.435487,168.557559,8.103448,134.835492,15.326795,3.454852,229.113924,32.808004,no,638,250,295,47,46
0,3231,2,0.463125,0.454039,0.000505,0.000085,14.059077,64.012318,1.724138,6.640746,12.864445,3.025950,250.758853,36.224219,no,1261,489,588,95,89
0,3231,3,0.462244,0.454892,0.000375,0.000036,11.807066,31.749069,1.379310,3.442343,-10.311120,-2.737490,254.344123,38.081915,no,1854,716,858,141,139
0,3231,4,0.460688,0.454236,0.000244,-0.000043,13.633670,26.502913,-4.137931,-7.478892,-25.021086,-7.331871,276.811594,42.018021,no,2442,933,1121,192,196
0,3231,5,0.459881,0.453645,0.000181,-0.000075,20.925383,32.098441,-1.034483,-1.511984,-21.096778,-6.297431,265.553603,42.736679,no,3016,1145,1379,242,250
0,3231,6,0.459021,0.452685,0.000141,-0.000096,19.852727,24.665216,-8.620690,-10.394113,-20.390611,-6.300747,295.437262,48.047269,no,3575,1349,1631,292,303
0,3231,7,0.458212,0.451066,0.000112,-0.000125,19.879955,20.781540,-5.862069,-6.096767,-20.408692,-6.558401,283.057090,49.048739,no,4116,1544,1879,342,351
0,3231,8,0.457192,0.449626,0.000163,-0.000100,19.256759,17.376243,-7.586207,-6.925836,13.537173,4.018795,295.437262,53.214526,no,4637,1745,2136,375,381
0,3231,9,0.456581,0.448437,0.000132,-0.000128,21.656814,16.979336,-5.172414,-4.159790,-22.824130,-8.059360,277.495463,53.853191,no,5136,1922,2364,423,427
0,3231,10,0.455728,0.446474,0.000159,-0.000137,24.706932,17.230665,5.172414,3.697748,4.428060,1.482405,245.514950,52.361603,no,5613,2102,2606,456,449
0,3231,11,0.454740,0.444663,0.000124,-0.000177,29.352010,18.663962,4.137931,2.732610,-27.283377,-10.821700,233.333333,54.158623,no,6076,2262,2825,501,488
0,3231,12,0.453221,0.442539,0.000130,-0.000194,44.632716,24.983224,14.310345,8.418164,-6.891879,-2.646179,219.508449,54.690206,no,6520,2426,3056,529,509
0,3231,13,0.451678,0.440178,0.000125,-0.000231,56.598154,28.409709,44.310345,22.690761,-14.671723,-6.102459,151.207729,44.129624,no,6943,2579,3280,557,527
0,3231,14,0.450313,0.438135,0.000077,-0.000303,86.026554,37.516934,72.413793,32.256739,-37.136603,-17.687085,116.216216,38.171680,no,7346,2716,3483,592,555
0,3231,15,0.448432,0.435568,0.000036,-0.000389,99.346723,39.080611,164.482759,59.214011,-35.128280,-17.553279,29.675810,12.288970,no,7718,2846,3688,615,569
0,3231,16,0.446263,0.432744,-0.000049,-0.000516,189.279608,61.010521,341.379310,94.595490,-57.449367,-33.387564,-22.676580,-11.509822,no,8067,2963,3884,637,583
0,3231,17,0.444021,0.429871,-0.000162,-0.000656,283.856371,76.267177,322.413793,83.522350,-65.032648,-41.492361,-6.306306,-3.268294,no,8396,3071,4073,657,595
0,3231,18,0.441903,0.427221,-0.000237,-0.000763,157.266010,45.671633,250.000000,64.662919,-57.020979,-37.291564,-6.306306,-3.535781,no,8701,3164,4242,681,614
0,3231,19,0.439866,0.424749,-0.000296,-0.000843,149.523674,41.191524,220.000000,55.083488,-49.759142,-33.575796,14.035088,8.118557,no,8980,3254,4407,696,623
0,3231,20,0.438102,0.422580,-0.000341,-0.000905,124.659423,33.607194,219.310345,51.525362,-41.839871,-29.800224,13.289760,8.487164,no,9233,3335,4557,710,631
0,3231,21,0.436193,0.420324,-0.000389,-0.000971,100.365868,26.742510,243.103448,52.258195,-42.671467,-32.930874,5.476673,3.902291,no,9466,3400,4689,729,648
0,3231,22,0.434432,0.418096,-0.000430,-0.001029,117.993444,28.881590,334.482759,61.328833,-39.692199,-33.187948,-15.102041,-12.239759,no,9677,3461,4817,743,656
0,3231,23,0.433509,0.416489,-0.000435,-0.001061,67.059266,17.333822,324.137931,56.843220,-13.510995,-12.205620,-14.754098,-13.338101,yes,9866,3511,4919,766,670
0,3231,24,0.432230,0.414918,-0.000458,-0.001090,88.644889,20.865291,289.655172,50.094336,-29.475143,-30.073266,-8.771930,-8.975980,no,10034,3560,5020,777,677
0,3231,25,0.431112,0.413643,-0.000469,-0.001105,57.645063,13.939123,286.206897,47.310971,-17.915103,-21.004289,-8.771930,-10.384952,no,10176,3602,5106,785,683
0,3231,26,0.430695,0.412900,-0.000466,-0.001112,50.154303,11.859645,275.862069,44.059457,-7.352299,-10.357648,-6.306306,-8.905034,no,10295,3636,5170,798,691
0,3231,27,0.430276,0.412400,-0.000479,-0.001123,70.351865,15.194693,235.517241,37.911260,-20.852609,-34.161119,1.463415,2.630515,no,10391,3665,5222,806,698
0,3231,28,0.429555,0.411817,-0.000496,-0.001136,61.744467,13.104715,248.275862,37.652865,-21.118254,-43.104720,0.970874,2.323566,no,10462,3687,5266,807,702
0,3231,29,0.429319,0.411470,-0.000504,-0.001144,46.460214,9.865765,281.034483,39.075768,-12.958358,-39.323927,-7.964602,-25.828404,no,10512,3702,5295,811,704
0,3231,30,0.429114,0.411112,-0.000518,-0.001162,59.487602,11.771801,329.310345,41.533549,-13.866279,-65.861290,-13.333333,-64.310943,no,10538,3707,5310,815,706

2207 和泰車 tw tv1
loss B&H
2207 和泰車 tw tv2
loss B&H
2207 和泰車 tw tv3
win B&H
2207 和泰車 tw tv4
loss B&H
2207 和泰車 tw tv5
loss B&H
2207 和泰車 tw tv6
loss B&H
2207 和泰車 tw tv7
loss B&H
2207 和泰車 tw tv8
loss B&H
2207 和泰車 tw tv9
loss B&H
2207 和泰車 tw tv10
loss B&H
2207 和泰車 tw tv11
win B&H
2207 和泰車 tw tv12
loss B&H
2207 和泰車 tw tv13
loss B&H
2207 和泰車 tw tv14
win B&H
2207 和泰車 tw tv15
win B&H
2207 和泰車 tw tv16
win B&H
2207 和泰車 tw tv17
win B&H
2207 和泰車 tw tv18
win B&H
2207 和泰車 tw tv19
win B&H
2207 和泰車 tw tv20
win B&H
2207 和泰車 tw tv21
win B&H
2207 和泰車 tw tv22
loss B&H
2207 和泰車 tw tv23
loss B&H
2207 和泰車 tw tv24
loss B&H
2207 和泰車 tw tv25
loss B&H
2207 和泰車 tw tv26
loss B&H
2207 和泰車 tw tv27
loss B&H
2207 和泰車 tw tv28
loss B&H
2207 和泰車 tw tv29
win B&H
2207 和泰車 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2207,1,0.450820,0.451835,-0.000087,0.000159,5.914732,87.687354,-2.272727,-22.266600,-12.289211,-3.074942,1.642036,0.388686,no,610,197,239,78,96
0,2207,2,0.451560,0.448399,-0.000072,0.000058,23.914302,123.999878,-5.519481,-19.228620,-7.609635,-1.930791,6.540448,1.572881,no,1218,378,465,172,203
0,2207,3,0.455000,0.448739,0.000079,0.000158,31.158378,95.445423,-6.168831,-14.556086,19.476048,4.643272,8.027923,1.989092,yes,1800,534,656,285,325
0,2207,4,0.452159,0.445367,0.000014,0.000070,51.047848,113.533572,-6.006494,-10.769001,-15.866443,-4.465604,7.093426,1.828682,no,2362,697,868,371,426
0,2207,5,0.450190,0.442768,-0.000022,0.000013,57.071077,93.777686,0.487013,0.714338,-13.615040,-3.937995,-1.589825,-0.438963,no,2901,851,1071,455,524
0,2207,6,0.449356,0.441788,-0.000034,-0.000008,49.776384,63.524639,-1.948052,-2.366494,-9.407757,-2.780323,2.995008,0.845754,no,3416,998,1261,537,620
0,2207,7,0.448531,0.439845,-0.000053,-0.000049,55.476330,58.337685,-5.681818,-5.909529,-12.728975,-3.965259,5.451448,1.589897,no,3915,1137,1448,619,711
0,2207,8,0.448205,0.438512,-0.000061,-0.000084,42.713118,38.204795,-6.168831,-5.628062,-9.887355,-3.179351,11.531532,3.445028,no,4402,1273,1630,700,799
0,2207,9,0.447887,0.437383,-0.000059,-0.000107,44.686732,34.382577,0.000000,0.000000,-8.486183,-2.835149,-0.322061,-0.104566,no,4874,1404,1806,779,885
0,2207,10,0.448114,0.437054,-0.000054,-0.000117,41.073853,28.115448,-3.409091,-2.466434,-3.491621,-1.199776,5.451448,1.819080,no,5329,1531,1972,857,969
0,2207,11,0.448509,0.436609,-0.000052,-0.000133,42.994943,26.845162,1.623377,1.076481,-5.972797,-2.189607,-6.354009,-2.332347,yes,5768,1653,2133,934,1048
0,2207,12,0.448409,0.435428,-0.000057,-0.000154,47.980779,26.723711,0.162338,0.098072,-8.948132,-3.459272,1.143791,0.428036,no,6193,1760,2282,1017,1134
0,2207,13,0.448213,0.434287,-0.000061,-0.000177,52.606195,26.574303,4.220779,2.331639,-6.794276,-2.753657,-2.056962,-0.821426,no,6604,1867,2432,1093,1212
0,2207,14,0.447921,0.433047,-0.000045,-0.000189,42.990508,20.146080,9.902597,4.965566,3.237698,1.345022,-7.749627,-3.325687,yes,6999,1963,2570,1172,1294
0,2207,15,0.447476,0.432029,-0.000072,-0.000240,84.712834,34.101346,33.603896,14.858723,-21.910706,-10.444161,-25.511432,-12.310073,yes,7368,2053,2699,1244,1372
0,2207,16,0.446820,0.430965,-0.000091,-0.000276,89.663601,33.243989,24.512987,10.330126,-17.224203,-8.595963,-20.231959,-10.190468,yes,7719,2135,2819,1314,1451
0,2207,17,0.446309,0.430404,-0.000096,-0.000285,71.541119,25.534724,12.337662,5.024744,-9.161440,-4.783381,-10.289855,-5.388600,yes,8046,2214,2930,1377,1525
0,2207,18,0.446108,0.430425,-0.000088,-0.000274,54.004630,18.756666,6.331169,2.474001,1.474771,0.812336,-4.915515,-2.747067,yes,8350,2289,3029,1436,1596
0,2207,19,0.446182,0.430517,-0.000081,-0.000259,54.032933,17.699978,0.162338,0.061210,2.907274,1.717855,-1.746032,-1.041441,yes,8631,2339,3094,1512,1686
0,2207,20,0.446208,0.430608,-0.000075,-0.000256,54.289408,16.792719,13.798701,4.735667,1.871692,1.217997,-12.198582,-8.142422,yes,8886,2386,3155,1579,1766
0,2207,21,0.446150,0.430420,-0.000074,-0.000256,61.357124,17.721568,9.577922,3.168144,-3.438954,-2.481146,-7.886905,-5.727597,yes,9118,2428,3213,1640,1837
0,2207,22,0.445992,0.430115,-0.000082,-0.000260,64.049058,17.487443,5.519481,1.764587,-9.468067,-7.625777,-5.783866,-4.640113,no,9332,2468,3270,1694,1900
0,2207,23,0.445810,0.429749,-0.000093,-0.000272,80.614615,20.220191,4.545455,1.394284,-11.846642,-10.692000,-4.769231,-4.287748,no,9522,2502,3320,1743,1957
0,2207,24,0.445557,0.429705,-0.000107,-0.000285,83.362795,19.844743,-1.136364,-0.340654,-13.562640,-13.869369,-0.482315,-0.494050,no,9689,2546,3379,1771,1993
0,2207,25,0.445077,0.429430,-0.000121,-0.000292,84.512267,19.197356,-0.324675,-0.093189,-14.069393,-16.564289,0.487013,0.581921,no,9832,2571,3416,1805,2040
0,2207,26,0.444478,0.428997,-0.000136,-0.000305,87.266220,18.883097,0.649351,0.178614,-15.763694,-21.778063,0.324149,0.464447,no,9951,2592,3450,1831,2078
0,2207,27,0.443416,0.428243,-0.000164,-0.000327,111.753896,22.045605,-2.435065,-0.652479,-26.106137,-41.766565,1.809211,3.256480,no,10047,2608,3482,1847,2110
0,2207,28,0.442380,0.427336,-0.000181,-0.000344,88.359814,17.604468,3.084416,0.781008,-17.699444,-37.066476,-3.582555,-8.307834,no,10118,2620,3511,1856,2131
0,2207,29,0.441975,0.426813,-0.000185,-0.000351,65.077747,13.155749,7.305195,1.753726,-5.048111,-17.012440,-7.196402,-23.575372,yes,10168,2636,3540,1858,2134
0,2207,30,0.441479,0.426171,-0.000190,-0.000358,65.887590,12.825161,3.571429,0.840124,-4.770478,-29.667583,-3.281250,-21.353960,no,10193,2638,3552,1862,2141

3661 世芯 tw tv1
loss B&H
3661 世芯 tw tv2
loss B&H
3661 世芯 tw tv3
loss B&H
3661 世芯 tw tv4
win B&H
3661 世芯 tw tv5
loss B&H
3661 世芯 tw tv6
win B&H
3661 世芯 tw tv7
loss B&H
3661 世芯 tw tv8
win B&H
3661 世芯 tw tv9
loss B&H
3661 世芯 tw tv10
loss B&H
3661 世芯 tw tv11
win B&H
3661 世芯 tw tv12
win B&H
3661 世芯 tw tv13
win B&H
3661 世芯 tw tv14
win B&H
3661 世芯 tw tv15
win B&H
3661 世芯 tw tv16
win B&H
3661 世芯 tw tv17
win B&H
3661 世芯 tw tv18
win B&H
3661 世芯 tw tv19
win B&H
3661 世芯 tw tv20
win B&H
3661 世芯 tw tv21
win B&H
3661 世芯 tw tv22
win B&H
3661 世芯 tw tv23
win B&H
3661 世芯 tw tv24
win B&H
3661 世芯 tw tv25
win B&H
3661 世芯 tw tv26
win B&H
3661 世芯 tw tv27
win B&H
3661 世芯 tw tv28
win B&H
3661 世芯 tw tv29
win B&H
3661 世芯 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,3661,1,0.522177,0.470886,0.002014,-0.001173,7.714948,125.752441,-6.406406,-51.587499,106.353710,18.832711,245.263158,34.331991,no,496,186,209,73,28
0,3661,2,0.524291,0.472681,0.002087,-0.001112,3.007255,11.788814,9.109109,38.804199,120.512725,21.506495,203.703704,31.475251,no,988,372,415,146,55
0,3661,3,0.524457,0.473276,0.002176,-0.001041,8.844256,23.290972,-7.407407,-17.315584,140.040704,25.024677,248.565356,37.504024,no,1472,549,611,223,89
0,3661,4,0.536045,0.480054,0.002820,-0.000646,2.475777,4.601243,-4.904905,-8.835933,652.936918,70.545250,247.826087,39.043719,yes,1942,710,769,331,132
0,3661,5,0.534201,0.480413,0.002788,-0.000587,3.624032,5.354093,-28.628629,-38.990750,151.088691,28.752738,335.013263,49.718406,no,2383,883,955,390,155
0,3661,6,0.539811,0.483811,0.003118,-0.000362,9.382418,11.535822,-29.329329,-34.466234,632.121288,76.499699,398.480243,58.162036,yes,2851,1046,1116,493,196
0,3661,7,0.539811,0.483811,0.003118,-0.000362,0.000000,0.000000,-7.407407,-7.701403,0.000000,0.000000,277.011494,48.345776,no,2851,1046,1116,493,196
0,3661,8,0.543913,0.486432,0.003328,-0.000207,19.954891,18.001187,-8.008008,-7.312390,543.223424,78.184909,296.135266,53.298406,yes,3302,1201,1268,595,238
0,3661,9,0.542133,0.484806,0.003196,-0.000275,48.836905,37.457520,-16.916917,-13.779590,111.989457,27.594411,289.086595,55.369711,no,3750,1372,1458,661,259
0,3661,10,0.541956,0.484234,0.003118,-0.000329,33.780406,23.311224,-11.411411,-8.354319,128.388718,32.377456,298.541920,59.931706,no,4183,1505,1603,762,313
0,3661,11,0.544188,0.484822,0.003225,-0.000256,51.215965,31.648480,-15.315315,-10.464161,373.009018,74.826157,279.629630,61.537034,yes,4594,1645,1748,855,346
0,3661,12,0.545855,0.484865,0.003320,-0.000197,51.881501,28.731966,-5.505506,-3.364267,370.936319,78.952148,216.908213,54.216206,yes,4994,1778,1889,948,379
0,3661,13,0.546875,0.484602,0.003381,-0.000163,78.184460,37.995676,24.124124,12.804625,301.418367,73.595236,171.074380,48.549547,yes,5376,1904,2025,1036,411
0,3661,14,0.547681,0.484509,0.003422,-0.000136,113.985114,47.762930,27.627628,13.337825,261.716284,71.444824,143.866171,45.322580,yes,5757,2033,2163,1120,441
0,3661,15,0.547896,0.483762,0.003413,-0.000156,176.171180,62.540633,76.176176,31.101186,157.554555,52.494771,82.222222,30.687127,yes,6107,2145,2289,1201,472
0,3661,16,0.548162,0.482855,0.003415,-0.000200,197.120292,62.952931,113.213213,40.423496,165.763689,59.160635,52.558140,22.241405,yes,6447,2253,2413,1281,500
0,3661,17,0.547820,0.481664,0.003390,-0.000255,267.249435,73.012415,149.749750,47.065395,108.395247,45.435864,34.979424,16.533900,yes,6765,2351,2530,1355,529
0,3661,18,0.548003,0.481110,0.003380,-0.000304,271.073895,68.540631,169.269269,48.340315,116.204553,53.128801,20.146520,10.675355,yes,7062,2445,2637,1425,555
0,3661,19,0.548352,0.480849,0.003371,-0.000346,288.568554,66.868370,182.282282,47.917096,103.205375,52.411622,14.886165,8.597418,yes,7342,2536,2738,1490,578
0,3661,20,0.547058,0.479635,0.003284,-0.000445,261.592599,58.422630,233.833834,53.957223,1.956677,1.273116,-6.552707,-4.328079,yes,7597,2626,2849,1530,592
0,3661,21,0.547138,0.478933,0.003289,-0.000486,316.922192,62.719499,273.873874,56.783386,87.621683,57.109772,-11.351351,-8.286923,yes,7828,2694,2931,1589,614
0,3661,22,0.547444,0.478299,0.003306,-0.000523,294.396500,56.323660,318.918919,59.424089,107.526420,79.001223,-19.607843,-15.974538,yes,8041,2755,3005,1647,634
0,3661,23,0.547752,0.477980,0.003333,-0.000518,282.665078,51.895723,245.345345,47.117274,115.320621,98.934561,-5.202312,-4.678189,yes,8230,2811,3070,1697,652
0,3661,24,0.547934,0.477702,0.003350,-0.000504,264.985268,47.191644,211.311311,40.364488,91.222557,94.270084,4.960000,5.084001,yes,8397,2860,3127,1741,669
0,3661,25,0.548361,0.477774,0.003409,-0.000440,166.280478,32.415945,187.287287,35.330119,153.955399,204.373614,13.691508,16.561921,yes,8540,2902,3172,1781,685
0,3661,26,0.549255,0.478353,0.003496,-0.000344,123.638923,24.845852,152.752753,29.130179,201.236765,384.963603,31.726908,48.372058,yes,8659,2939,3205,1817,698
0,3661,27,0.550149,0.478717,0.003569,-0.000266,219.034604,36.078789,124.224224,23.914229,148.288543,408.019082,45.454545,95.358254,yes,8754,2969,3233,1847,705
0,3661,28,0.550997,0.479027,0.003631,-0.000204,272.252377,40.020004,137.237237,24.762312,115.126086,517.917803,36.666667,110.144796,yes,8824,2992,3254,1870,708
0,3661,29,0.551386,0.479389,0.003670,-0.000141,362.931656,45.915038,98.198198,18.374310,61.781975,465.130149,60.391198,447.835174,yes,8874,3012,3271,1881,710
0,3661,30,0.551573,0.479695,0.003702,-0.000094,459.598235,50.765386,131.731732,22.184583,46.284913,1446.808910,45.777778,1408.611953,yes,8900,3024,3280,1885,711

2603 長榮 tw tv1
loss B&H
2603 長榮 tw tv2
loss B&H
2603 長榮 tw tv3
loss B&H
2603 長榮 tw tv4
loss B&H
2603 長榮 tw tv5
loss B&H
2603 長榮 tw tv6
loss B&H
2603 長榮 tw tv7
loss B&H
2603 長榮 tw tv8
loss B&H
2603 長榮 tw tv9
loss B&H
2603 長榮 tw tv10
loss B&H
2603 長榮 tw tv11
loss B&H
2603 長榮 tw tv12
loss B&H
2603 長榮 tw tv13
loss B&H
2603 長榮 tw tv14
loss B&H
2603 長榮 tw tv15
loss B&H
2603 長榮 tw tv16
loss B&H
2603 長榮 tw tv17
loss B&H
2603 長榮 tw tv18
loss B&H
2603 長榮 tw tv19
loss B&H
2603 長榮 tw tv20
loss B&H
2603 長榮 tw tv21
loss B&H
2603 長榮 tw tv22
loss B&H
2603 長榮 tw tv23
win B&H
2603 長榮 tw tv24
loss B&H
2603 長榮 tw tv25
win B&H
2603 長榮 tw tv26
loss B&H
2603 長榮 tw tv27
loss B&H
2603 長榮 tw tv28
loss B&H
2603 長榮 tw tv29
loss B&H
2603 長榮 tw tv30
loss B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2603,1,0.445988,0.410959,0.000047,-0.001835,11.798236,239.374033,-18.996416,-90.056834,-6.327030,-1.544736,81.451613,15.247899,no,648,120,172,169,187
0,2603,2,0.447022,0.411458,0.000169,-0.001870,4.641790,18.608259,14.695341,67.480101,3.623478,0.880651,36.778116,8.020345,no,1293,237,339,341,376
0,2603,3,0.446764,0.412178,0.000251,-0.001758,-3.919210,-9.405444,1.433692,3.579486,9.145303,2.257129,63.043478,13.279225,no,1916,352,502,504,558
0,2603,4,0.445378,0.411449,0.000203,-0.001815,9.031004,17.238457,-3.225806,-5.853125,-11.018233,-3.039741,56.250000,12.525633,no,2499,460,658,653,728
0,2603,5,0.444950,0.412473,0.000168,-0.001679,14.313783,21.652545,-29.247312,-39.764025,-5.594549,-1.567968,107.373272,22.166391,no,3079,582,829,788,880
0,2603,6,0.445239,0.412965,0.000183,-0.001576,4.167013,5.095617,-31.541219,-36.954674,2.814598,0.795310,132.919255,27.290798,no,3634,688,978,930,1038
0,2603,7,0.447854,0.415800,0.000272,-0.001411,-12.401073,-12.879030,-42.867384,-44.173808,44.406014,11.538276,181.250000,35.974272,no,4171,800,1124,1068,1179
0,2603,8,0.447599,0.416092,0.000254,-0.001344,3.937716,3.576050,11.469534,10.382497,-6.716888,-2.134746,44.230769,12.037343,no,4685,905,1270,1192,1318
0,2603,9,0.447084,0.415768,0.000224,-0.001308,21.601743,16.936971,11.469534,9.074931,-13.302661,-4.524100,45.161290,12.847556,no,5178,1002,1408,1313,1455
0,2603,10,0.446018,0.415101,0.000174,-0.001303,31.852214,22.028970,16.129032,11.367221,-24.988395,-9.303444,41.955836,12.635344,no,5650,1105,1557,1415,1573
0,2603,11,0.445355,0.415199,0.000136,-0.001284,58.848718,36.030285,9.318996,6.103333,-22.839169,-8.899511,49.501661,15.553439,no,6103,1202,1693,1516,1692
0,2603,12,0.444563,0.415252,0.000097,-0.001280,65.419337,35.548683,12.544803,7.403100,-24.693356,-10.103320,44.230769,14.745487,no,6539,1296,1825,1611,1807
0,2603,13,0.444125,0.415117,0.000080,-0.001263,45.962831,23.472063,13.620072,7.378522,-15.708796,-6.557024,42.405063,15.060598,no,6953,1384,1950,1704,1915
0,2603,14,0.443703,0.415068,0.000048,-0.001254,65.590059,29.543841,8.243728,4.149407,-22.991932,-10.375962,45.161290,16.913386,no,7345,1471,2073,1788,2013
0,2603,15,0.443278,0.415064,0.000020,-0.001247,64.422902,26.843584,15.770609,7.253467,-23.769310,-11.401203,38.888889,15.779650,no,7713,1554,2190,1865,2104
0,2603,16,0.442983,0.415416,-0.000002,-0.001221,58.697361,23.008514,-29.677419,-14.604001,-19.112405,-9.593332,122.772277,46.351820,no,8059,1633,2298,1937,2191
0,2603,17,0.443039,0.415936,-0.000014,-0.001196,16.736679,6.738596,-24.014337,-10.928296,-15.591714,-8.283505,113.270142,47.161525,no,8383,1707,2397,2007,2272
0,2603,18,0.443984,0.417212,-0.000007,-0.001167,25.451875,9.447079,-16.845878,-7.080815,-2.796467,-1.555216,98.237885,45.960295,no,8685,1784,2492,2072,2337
0,2603,19,0.445076,0.418620,0.000003,-0.001135,-3.543747,-1.351904,-20.788530,-8.416285,4.029979,2.375959,99.115044,50.580732,no,8967,1857,2579,2134,2397
0,2603,20,0.446444,0.420353,0.000032,-0.001086,0.914410,0.326361,-15.053763,-5.672826,21.419321,13.508208,84.426230,49.122190,no,9224,1929,2660,2189,2446
0,2603,21,0.447711,0.421509,0.000067,-0.001047,-6.779741,-2.365575,12.186380,3.999117,32.788528,22.580945,41.955836,28.599190,no,9457,1995,2738,2239,2485
0,2603,22,0.448718,0.422469,0.000102,-0.001008,-7.504437,-2.507862,6.093190,1.944400,34.678624,26.797765,51.006711,38.913305,no,9672,2057,2812,2283,2520
0,2603,23,0.449660,0.423301,0.000133,-0.000983,-5.758574,-1.830530,21.863799,6.352965,33.346550,29.444412,29.682997,26.250524,yes,9863,2111,2876,2324,2552
0,2603,24,0.450439,0.423998,0.000146,-0.000976,2.929714,0.865907,34.050179,9.143850,13.273863,13.618734,17.493473,17.956368,no,10028,2159,2933,2358,2578
0,2603,25,0.451140,0.424937,0.000171,-0.000952,-3.306559,-0.959351,50.896057,12.518792,28.239316,34.589473,4.408353,5.287240,yes,10172,2205,2984,2384,2599
0,2603,26,0.451516,0.425915,0.000181,-0.000921,13.158091,3.466968,31.899642,7.932567,9.161376,13.372543,28.205128,42.725282,no,10292,2245,3026,2402,2619
0,2603,27,0.452113,0.427261,0.000195,-0.000881,-7.761125,-2.122432,24.014337,5.881669,19.889107,38.292239,25.000000,49.005011,no,10389,2282,3059,2415,2633
0,2603,28,0.452442,0.428148,0.000206,-0.000851,2.733592,0.693059,33.691756,7.719688,12.304533,31.768748,21.951220,60.285918,no,10461,2309,3084,2424,2644
0,2603,29,0.452478,0.428335,0.000204,-0.000846,17.348744,4.023550,46.236559,9.824372,-1.655946,-5.834203,9.223301,37.383657,no,10511,2328,3107,2428,2648
0,2603,30,0.452406,0.428205,0.000200,-0.000852,30.921844,6.634301,63.440860,12.426176,-6.715973,-39.380486,-1.960784,-13.288088,no,10537,2338,3122,2429,2648

2408 南亞科 tw tv1
win B&H
2408 南亞科 tw tv2
win B&H
2408 南亞科 tw tv3
win B&H
2408 南亞科 tw tv4
win B&H
2408 南亞科 tw tv5
win B&H
2408 南亞科 tw tv6
win B&H
2408 南亞科 tw tv7
win B&H
2408 南亞科 tw tv8
win B&H
2408 南亞科 tw tv9
win B&H
2408 南亞科 tw tv10
win B&H
2408 南亞科 tw tv11
win B&H
2408 南亞科 tw tv12
win B&H
2408 南亞科 tw tv13
win B&H
2408 南亞科 tw tv14
win B&H
2408 南亞科 tw tv15
win B&H
2408 南亞科 tw tv16
win B&H
2408 南亞科 tw tv17
win B&H
2408 南亞科 tw tv18
win B&H
2408 南亞科 tw tv19
win B&H
2408 南亞科 tw tv20
win B&H
2408 南亞科 tw tv21
win B&H
2408 南亞科 tw tv22
win B&H
2408 南亞科 tw tv23
win B&H
2408 南亞科 tw tv24
win B&H
2408 南亞科 tw tv25
win B&H
2408 南亞科 tw tv26
win B&H
2408 南亞科 tw tv27
win B&H
2408 南亞科 tw tv28
win B&H
2408 南亞科 tw tv29
win B&H
2408 南亞科 tw tv30
win B&H

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2408,1,0.455621,0.402667,-0.000669,-0.002545,0.531784,5.983224,-5.511811,-46.269199,-34.287657,-9.517166,-61.714660,-20.441884,yes,507,151,224,80,52
0,2408,2,0.463271,0.399433,-0.000540,-0.002779,1.131992,4.324623,-0.787402,-2.929524,-25.650147,-7.040907,-61.360634,-20.882726,yes,1021,282,424,191,124
0,2408,3,0.459264,0.396750,-0.000699,-0.002899,11.538411,30.968333,-16.141732,-35.268843,-44.793375,-14.060646,-54.153605,-18.038055,yes,1522,415,631,284,192
0,2408,4,0.459285,0.396825,-0.000658,-0.002866,11.923230,23.022534,-12.335958,-21.508084,-27.979506,-8.313080,-55.948795,-19.489518,yes,2014,550,836,375,253
0,2408,5,0.461198,0.397741,-0.000551,-0.002795,7.856929,11.718788,-22.703412,-31.428781,-11.238941,-3.219790,-51.086957,-17.824183,yes,2487,669,1013,478,327
0,2408,6,0.463862,0.399797,-0.000449,-0.002727,-1.821579,-2.213163,-31.364829,-36.756864,-2.914801,-0.840668,-43.965517,-15.235989,yes,2947,788,1183,579,397
0,2408,7,0.467747,0.401254,-0.000288,-0.002650,-2.919108,-3.037882,-31.627297,-32.693079,27.993794,7.610168,-42.759295,-15.277799,yes,3395,896,1337,692,470
0,2408,8,0.465653,0.399606,-0.000316,-0.002640,-3.833788,-3.493898,-34.120735,-31.591958,-25.678400,-8.798659,-41.206030,-15.196530,yes,3814,1013,1522,763,516
0,2408,9,0.465248,0.398510,-0.000358,-0.002703,16.361446,12.887872,-21.391076,-17.514525,-31.789018,-11.668642,-51.005025,-20.657002,yes,4230,1123,1695,845,567
0,2408,10,0.466523,0.398052,-0.000303,-0.002701,17.072159,12.017690,-29.527559,-22.272642,1.192521,0.403423,-43.750000,-17.749991,yes,4630,1226,1854,934,616
0,2408,11,0.466401,0.397001,-0.000308,-0.002733,7.256220,4.767877,-24.278215,-16.882396,-18.690619,-7.168197,-51.492537,-22.900345,yes,5015,1324,2011,1015,665
0,2408,12,0.468298,0.396518,-0.000252,-0.002742,20.037216,11.668818,-23.359580,-14.851700,12.192855,4.415476,-48.952880,-22.316996,yes,5394,1412,2149,1114,719
0,2408,13,0.471266,0.396515,-0.000162,-0.002741,8.336858,4.565525,-12.729659,-7.310218,42.047008,14.945702,-55.948795,-27.772180,yes,5725,1479,2251,1219,776
0,2408,14,0.472090,0.396165,-0.000143,-0.002754,13.726971,6.824600,-15.091864,-8.053741,-0.132536,-0.055594,-54.439252,-28.080486,yes,6073,1570,2393,1297,813
0,2408,15,0.472591,0.395604,-0.000138,-0.002782,21.940813,9.949847,0.000000,0.000000,-5.498916,-2.491074,-61.155378,-34.410501,yes,6403,1656,2530,1370,847
0,2408,16,0.474589,0.395478,-0.000084,-0.002800,20.961729,8.907864,-7.611549,-3.487621,29.976702,13.276502,-58.392603,-34.093785,yes,6690,1714,2620,1461,895
0,2408,17,0.476450,0.395396,-0.000035,-0.002817,19.748089,7.890387,-14.304462,-6.298126,30.681760,14.626162,-55.000000,-33.457937,yes,6964,1769,2705,1549,941
0,2408,18,0.477924,0.394874,0.000004,-0.002847,25.946516,9.618672,-13.910761,-5.788728,25.010230,13.129319,-56.730769,-37.057915,yes,7225,1818,2786,1635,986
0,2408,19,0.479529,0.394497,0.000053,-0.002866,14.121010,5.109245,-13.910761,-5.493919,37.546664,20.861048,-55.748865,-38.403101,yes,7474,1864,2861,1720,1029
0,2408,20,0.480373,0.393689,0.000072,-0.002914,18.759048,6.347500,-5.380577,-1.960286,12.106353,7.745981,-59.487535,-44.561130,yes,7719,1909,2940,1799,1071
0,2408,21,0.481491,0.393340,0.000089,-0.002958,18.766400,6.040219,-9.711286,-3.423613,8.512881,6.040984,-59.090909,-47.361132,yes,7942,1949,3006,1875,1112
0,2408,22,0.482390,0.393097,0.000106,-0.002986,8.385902,2.656509,-13.517060,-4.618153,11.602373,9.148570,-56.081081,-48.116891,yes,8149,1993,3077,1938,1141
0,2408,23,0.483263,0.392995,0.000122,-0.003011,8.807225,2.664129,-8.661417,-2.782606,12.521839,11.160128,-57.299270,-53.379661,yes,8335,2031,3137,1997,1170
0,2408,24,0.484175,0.392878,0.000148,-0.003028,-0.620596,-0.185701,-13.779528,-4.330243,23.196444,23.824871,-56.666667,-57.541553,yes,8499,2063,3188,2052,1196
0,2408,25,0.484175,0.392878,0.000148,-0.003028,0.000000,0.000000,-15.354331,-4.666608,0.000000,0.000000,-54.439252,-60.893345,yes,8499,2063,3188,2052,1196
0,2408,26,0.485204,0.392675,0.000179,-0.003052,-5.683757,-1.600427,-3.018373,-0.841457,29.461492,44.732132,-60.738255,-73.779662,yes,8617,2080,3217,2101,1219
0,2408,27,0.486511,0.392790,0.000209,-0.003068,5.077190,1.323787,-33.070866,-10.113723,26.562154,52.349466,-44.811321,-65.435878,yes,8711,2092,3234,2146,1239
0,2408,28,0.487758,0.392971,0.000234,-0.003080,2.547709,0.646369,-39.238845,-11.978827,24.195842,67.388727,-37.231760,-66.951225,yes,8781,2102,3247,2181,1251
0,2408,29,0.488391,0.392691,0.000254,-0.003092,13.695616,3.215525,-41.469816,-12.372259,19.141431,87.856456,-33.823529,-77.377898,yes,8829,2106,3257,2206,1260
0,2408,30,0.488706,0.392518,0.000273,-0.003092,8.535857,1.972023,-52.362205,-16.204584,19.423625,258.963084,-18.296089,-76.657440,yes,8854,2109,3264,2218,1263

    tv Ann_Train_RTN Ann_Train_B&H Ann_Test_RTN Ann_Test_B&H  Win B&H    Diff
0    1       124.46%        -0.21%        9.99%        8.70%     True   1.29%
1    2        43.76%        -0.05%       10.78%        9.40%     True   1.38%
2    3        34.35%        -7.58%       12.75%       11.01%     True   1.74%
3    4        27.13%       -15.35%       13.68%       12.97%     True   0.70%
4    5        23.73%       -16.88%       11.09%       14.71%    False  -3.62%
5    6        17.42%       -19.17%       13.46%       17.55%    False  -4.08%
6    7        15.74%       -17.84%       14.88%       18.48%    False  -3.60%
7    8        15.51%       -15.57%       19.29%       20.55%    False  -1.26%
8    9        18.27%       -11.70%       13.26%       18.58%    False  -5.32%
9   10        16.37%       -10.46%       15.27%       20.71%    False  -5.43%
10  11        16.48%        -8.62%       16.70%       19.43%    False  -2.73%
11  12        16.40%        -6.26%       21.04%       19.58%     True   1.46%
12  13        16.41%        -2.41%       21.77%       18.59%     True   3.18%
13  14        17.51%        -1.08%       20.27%       18.62%     True   1.65%
14  15        20.44%         6.93%       19.24%       11.27%     True   7.97%
15  16        22.09%         8.60%       20.52%       11.57%     True   8.95%
16  17        21.91%         8.84%       18.48%       13.41%     True   5.06%
17  18        19.76%         6.78%       22.74%       13.88%     True   8.86%
18  19        17.40%         5.37%       26.79%       16.73%     True  10.06%
19  20        15.52%         7.27%       26.24%       14.77%     True  11.46%
20  21        15.36%         8.11%       31.93%       14.28%     True  17.65%
21  22        14.83%         9.17%       38.05%       13.28%     True  24.77%
22  23        15.66%        10.72%       36.17%        6.65%     True  29.52%
23  24        15.91%         9.25%       35.11%        8.08%     True  27.03%
24  25        13.91%        10.40%       43.74%        2.80%     True  40.94%
25  26        14.84%        11.79%       57.97%       -3.51%     True  61.48%
26  27        18.51%         8.16%       49.99%       11.98%     True  38.01%
27  28        18.22%         7.93%       60.56%       19.40%     True  41.16%
28  29        18.88%         9.29%       62.03%       18.75%     True  43.28%
29  30        19.55%         9.00%      137.48%       92.50%     True  44.98%

# TV-2 Usable Exp DayTrade

In [5]:
from TV_usableexp_dt_stock import TV_UsableExpFactorDT
import pandas as pd
from joblib import Parallel, delayed
from datetime import datetime

avgs = pd.DataFrame()
selected_columns = ['accuracy', 'precision', 'ev', 'precision_ev', 'avail_count', 'tp', 'fp', 'tn', 'fn']

def process_stock(stock, i):
    stock_avg_list = []  # 存放該支股票所有 TV 的結果
    
    for date_range in data_range_tv:
        env = {
            "stock_id": stock[0],
            "stock_name": stock[1],
            "country": stock[2],
            "start_date": date_range[0],
            "end_date": date_range[1],
            "tv": date_range[2],
            "run_count": str(i)
        }
        print(env['stock_id'], env['stock_name'], env['country'], f"tv{date_range[2]}")
        
        eval_module = TV_UsableExpFactorDT(env)
        eval_module.run()
        train_datarange, test_datarange = eval_module.split_exp(date_range[2])
        
        mode = 1
        eval_module.training(mode, train_datarange, test_datarange)
        
        result = eval_module.get_result(1)  # Test 結果
        result_test = result["test"]  # Test 結果
        
        # Training & Test 報酬計算
        train_date, train_bnh_balance, train_stag_rtn = eval_module.get_return_list('train')
        train_stag_balance = get_balance_list(train_stag_rtn, train_bnh_balance[0])
        
        list_date, list_bnh_balance, list_stag_rtn = eval_module.get_return_list('test')
        list_stag_balance = get_balance_list(list_stag_rtn, list_bnh_balance[0])
        
        # 計算天數
        train_N_days = (datetime.strptime(sorted(train_datarange.keys())[-1], '%Y%m%d') - 
                        datetime.strptime(sorted(train_datarange.keys())[0], '%Y%m%d')).days
        test_N_days = (datetime.strptime(sorted(test_datarange.keys())[-1], '%Y%m%d') - 
                       datetime.strptime(sorted(test_datarange.keys())[0], '%Y%m%d')).days

        stock_avg = cacl_avg(pd.DataFrame([result_test]).loc[:, selected_columns])
        stock_avg['stock_id'] = stock[0]
        stock_avg['tv'] = date_range[2]
        stock_avg['Train_RTN'] = (train_stag_balance[-1] / train_bnh_balance[0] - 1) * 100
        stock_avg['Train_B&H'] = (train_bnh_balance[-1] / train_bnh_balance[0] - 1) * 100
        stock_avg['Ann_Train_RTN'] = ((1 + stock_avg['Train_RTN'] / 100) ** (252 / train_N_days) - 1) * 100
        stock_avg['Ann_Train_B&H'] = ((1 + stock_avg['Train_B&H'] / 100) ** (252 / train_N_days) - 1) * 100
        stock_avg['RTN'] = (list_stag_balance[-1] / list_bnh_balance[0] - 1) * 100
        stock_avg['B&H'] = (list_bnh_balance[-1] / list_bnh_balance[0] - 1) * 100
        stock_avg['Ann_RTN'] = ((1 + stock_avg['RTN'] / 100) ** (252 / test_N_days) - 1) * 100
        stock_avg['Ann_B&H'] = ((1 + stock_avg['B&H'] / 100) ** (252 / test_N_days) - 1) * 100
        stock_avg['win B&H'] = "yes" if list_stag_balance[-1] > list_bnh_balance[-1] else "no"

        stock_avg_list.append(stock_avg)
    
    return pd.concat(stock_avg_list) if stock_avg_list else None

def runAll_parallel(i):
    results = Parallel(n_jobs=-1)(delayed(process_stock)(stock, i) for stock in data)
    return pd.concat([res for res in results if res is not None])

# 迭代執行
for i in range(1):
    print(i+1)
    avgs = pd.concat([avgs, runAll_parallel(i+1)])
    
tv_avg_df = avgs.groupby("tv")[["RTN", "B&H", "Ann_RTN", "Ann_B&H", "Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H"]].mean().reset_index()
tv_avg_df["Test_RTN"] = tv_avg_df["RTN"]
tv_avg_df["Test_B&H"] = tv_avg_df["B&H"]
tv_avg_df["Ann_Test_RTN"] = tv_avg_df["Ann_RTN"]
tv_avg_df["Ann_Test_B&H"] = tv_avg_df["Ann_B&H"]
tv_avg_df["Win B&H"] = tv_avg_df["Ann_Test_RTN"] > tv_avg_df["Ann_Test_B&H"]
tv_avg_df["Diff"] = tv_avg_df["Ann_Test_RTN"] - tv_avg_df["Ann_Test_B&H"]
tv_avg_df[["Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H", "RTN", "B&H", "Ann_Test_RTN", "Ann_Test_B&H", "Diff"]] = tv_avg_df[["Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H", "RTN", "B&H", "Ann_Test_RTN", "Ann_Test_B&H", "Diff"]].map(lambda x: f"{x:.2f}%")

display(tv_avg_df.loc[:, ["tv", "Ann_Train_RTN", "Ann_Train_B&H", "Ann_Test_RTN", "Ann_Test_B&H", "Win B&H", "Diff"]])

1
2330 台積電 tw tv1
2308 台達電 tw tv1
2317 鴻海 tw tv1
2382 廣達 tw tv1
2412 中華電 tw tv1
2454 聯發科 tw tv1
2881 富邦金 tw tv1
2882 國泰金 tw tv1
Processing for date 20230209	20230208 news found
Processing for date 20230609	20230608 news found
Processing for date 20220504	20220503 news found
Processing for date 20230310	20230309 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
2330 台積電 tw tv2
2454 聯發科 tw tv2
2308 台達電 tw tv2

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2317 鴻海 tw tv2
Ungenerated list ['11', '12', '13', '14', '15', '16']
Processing for date 20230210	20230209 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['13', '14', '15', '16']
Processing for date 20230313	20230312 news found
Start Running Genetic Algorithm
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230612	20230611 news found
Ungenerated list ['8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Start Running Genetic Algorithm
2454 聯發科 tw tv3
2330 台積電 tw tv3
2317 鴻海 tw tv3
2308 台達電 tw tv3
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230213	20230212 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230314	20230313 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230613	20230612 news found
2330 台積電 tw tv4
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230315	20230314 news found
2454 聯發科 tw tv4
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230214	20230213 news found
2317 鴻海 tw tv4
2308 台達電 tw tv4
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230316	20230315 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230215	20230214 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230317	20230316 news found
2330 台積電 tw tv5
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230216	20230215 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230614	20230613 news found
Start Running Genetic Algorithm
2454 聯發科 tw tv5
2317 鴻海 tw tv5

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2308 台達電 tw tv5
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230320	20230319 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230615	20230614 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230217	20230216 news found
2317 鴻海 tw tv6
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230321	20230320 news found
2308 台達電 tw tv6
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Start Running Genetic Algorithm
2454 聯發科 tw tv6
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230616	20230615 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2330 台積電 tw tv6
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230619	20230618 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230322	20230321 news found
Start Running Genetic Algorithm
2317 鴻海 tw tv7
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Start Running Genetic Algorithm
2454 聯發科 tw tv7
2308 台達電 tw tv7

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230220	20230219 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230620	20230619 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230323	20230322 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230221	20230220 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230324	20230323 news found
2317 鴻海 tw tv8
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230621	20230620 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230327	20230326 news found
2454 聯發科 tw tv8
2308 台達電 tw tv8
Start Running Genetic Algorithm
2330 台積電 tw tv7
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230626	20230625 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230222	20230221 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230328	20230327 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230223	20230222 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230329	20230328 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230627	20230626 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230330	20230329 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230628	20230627 news found
2454 聯發科 tw tv9
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230224	20230223 news found
2330 台積電 tw tv8
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230629	20230628 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230331	20230330 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230301	20230228 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
2308 台達電 tw tv9
Start Running Genetic Algorithm
2317 鴻海 tw tv9
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230630	20230629 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230302	20230301 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230406	20230405 news found
2330 台積電 tw tv9
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230703	20230702 news found
2454 聯發科 tw tv10
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230303	20230302 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230704	20230703 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230407	20230406 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230306	20230305 news found
2317 鴻海 tw tv10
2308 台達電 tw tv10
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230705	20230704 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230307	20230306 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	 no news found in 20220525
Processing for date 20220527	20220526 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230410	20230409 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230411	20230410 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230706	20230705 news found
2330 台積電 tw tv10
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230308	20230307 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Start Running Genetic Algorithm
2454 聯發科 tw tv11
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230707	20230706 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230412	20230411 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230309	20230308 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230413	20230412 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230710	20230709 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230310	20230309 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230711	20230710 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230712	20230711 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230313	20230312 news found
2330 台積電 tw tv11
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230414	20230413 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230713	20230712 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230314	20230313 news found
2454 聯發科 tw tv12
2308 台達電 tw tv11
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230714	20230713 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230417	20230416 news found
2317 鴻海 tw tv11
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230717	20230716 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230315	20230314 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230418	20230417 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230718	20230717 news found
2330 台積電 tw tv12
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230419	20230418 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230719	20230718 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230316	20230315 news found
2308 台達電 tw tv12
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Start Running Genetic Algorithm
2317 鴻海 tw tv12
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230720	20230719 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230317	20230316 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2454 聯發科 tw tv13
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230420	20230419 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230721	20230720 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230421	20230420 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230320	20230319 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230424	20230423 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230724	20230723 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230321	20230320 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230725	20230724 news found
2317 鴻海 tw tv13
2330 台積電 tw tv13
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230322	20230321 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230425	20230424 news found
2308 台達電 tw tv13
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
2454 聯發科 tw tv14
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230726	20230725 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230426	20230425 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230323	20230322 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230727	20230726 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230427	20230426 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230324	20230323 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230428	20230427 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230728	20230727 news found
2317 鴻海 tw tv14
2330 台積電 tw tv14
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230327	20230326 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230502	20230501 news found
2308 台達電 tw tv14
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230731	20230730 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230328	20230327 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230503	20230502 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230801	20230731 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230329	20230328 news found
2454 聯發科 tw tv15
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230504	20230503 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
2330 台積電 tw tv15
Start Running Genetic Algorithm
2317 鴻海 tw tv15
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230330	20230329 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230802	20230801 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230505	20230504 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
2308 台達電 tw tv15
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230804	20230803 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230508	20230507 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230331	20230330 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230807	20230806 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230406	20230405 news found
2454 聯發科 tw tv16
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230808	20230807 news found
Start Running Genetic Algorithm
2317 鴻海 tw tv16
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230407	20230406 news found
2330 台積電 tw tv16
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230509	20230508 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
2308 台達電 tw tv16
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230809	20230808 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230410	20230409 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230810	20230809 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230510	20230509 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230811	20230810 news found
2454 聯發科 tw tv17
2317 鴻海 tw tv17
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230511	20230510 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230411	20230410 news found
2330 台積電 tw tv17
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230814	20230813 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230412	20230411 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230512	20230511 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
2308 台達電 tw tv17
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230515	20230514 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230413	20230412 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230815	20230814 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230816	20230815 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230516	20230515 news found
2454 聯發科 tw tv18
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230817	20230816 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230414	20230413 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230517	20230516 news found
2317 鴻海 tw tv18
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230417	20230416 news found
2330 台積電 tw tv18
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230518	20230517 news found
Processing for date 20230818	20230817 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230821	20230820 news found
2308 台達電 tw tv18
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230418	20230417 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230519	20230518 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230822	20230821 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230522	20230521 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230823	20230822 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230419	20230418 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230523	20230522 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230824	20230823 news found
2454 聯發科 tw tv19
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Start Running Genetic Algorithm
2330 台積電 tw tv19
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230420	20230419 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230524	20230523 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230825	20230824 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230421	20230420 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230525	20230524 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
2308 台達電 tw tv19
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230424	20230423 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230828	20230827 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
2454 聯發科 tw tv20
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230526	20230525 news found
Start Running Genetic Algorithm
2317 鴻海 tw tv19
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230425	20230424 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230829	20230828 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230529	20230528 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230530	20230529 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230426	20230425 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230830	20230829 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230531	20230530 news found
2330 台積電 tw tv20
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230427	20230426 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230601	20230531 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230602	20230601 news found
2454 聯發科 tw tv21
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230831	20230830 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230428	20230427 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230502	20230501 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

Start Running Genetic Algorithm
Start Running Genetic Algorithm
2330 台積電 tw tv25
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230704	20230703 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230928	20230927 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230705	20230704 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230530	20230529 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231002	20231001 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
2454 聯發科 tw tv26
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230531	20230530 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231003	20231002 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230706	20230705 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230601	20230531 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231004	20231003 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231005	20231004 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230602	20230601 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230707	20230706 news found
2317 鴻海 tw tv24
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230605	20230604 news found
2308 台達電 tw tv25
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230710	20230709 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231006	20231005 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230606	20230605 news found
2330 台積電 tw tv26
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231011	20231010 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230607	20230606 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231012	20231011 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230711	20230710 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
2454 聯發科 tw tv27
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230608	20230607 news found
2317 鴻海 tw tv25
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230712	20230711 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231013	20231012 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231016	20231015 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230609	20230608 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231017	20231016 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230713	20230712 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230612	20230611 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231018	20231017 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230613	20230612 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231019	20231018 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
2308 台達電 tw tv26
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230714	20230713 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230614	20230613 news found
Start Running Genetic Algorithm
2330 台積電 tw tv27
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231020	20231019 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230717	20230716 news found
2454 聯發科 tw tv28
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230615	20230614 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231023	20231022 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
2317 鴻海 tw tv26
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230616	20230615 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230718	20230717 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231024	20231023 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230619	20230618 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231025	20231024 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230620	20230619 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230719	20230718 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231026	20231025 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230621	20230620 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230720	20230719 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231027	20231026 news found
2330 台積電 tw tv28
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230721	20230720 news found
Start Running Genetic Algorithm
2308 台達電 tw tv27
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230626	20230625 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231030	20231029 news found
2317 鴻海 tw tv27
Start Running Genetic Algorithm
2454 聯發科 tw tv29
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231031	20231030 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230724	20230723 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230627	20230626 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231101	20231031 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated listUngenerated list  ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']

Processing for date 20230628	20230627 news found
Processing for date 20231102	20231101 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230725	20230724 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231103	20231102 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230629	20230628 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231106	20231105 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230726	20230725 news found
2308 台達電 tw tv28
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230630	20230629 news found
2330 台積電 tw tv29
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231107	20231106 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230727	20230726 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230703	20230702 news found
2317 鴻海 tw tv28
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230728	20230727 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230704	20230703 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	20220929 news found
2454 聯發科 tw tv30
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231108	20231107 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230731	20230730 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	20221002 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230705	20230704 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230801	20230731 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231109	20231108 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221004	20221003 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230802	20230801 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231110	20231109 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230706	20230705 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	20221004 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230804	20230803 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231113	20231112 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230707	20230706 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230807	20230806 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221006	20221005 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221007	20221006 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230808	20230807 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231114	20231113 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230710	20230709 news found
2330 台積電 tw tv30
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221011	20221010 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230809	20230808 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231115	20231114 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230711	20230710 news found
2308 台達電 tw tv29
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221012	20221011 news found
Start Running Genetic Algorithm
2891 中信金 tw tv1
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230712	20230711 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230810	20230809 news found
Start Running Genetic Algorithm

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2603 長榮 tw tv3
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240403	20240402 news found
3231 緯創 tw tv30
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231215	20231214 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230301	20230228 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231124	20231123 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240408	20240407 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2603 長榮 tw tv4
Start Running Genetic Algorithm
3661 世芯 tw tv7
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230302	20230301 news found
2207 和泰車 tw tv29
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240409	20240408 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231127	20231126 news found
2603 長榮 tw tv5
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231218	20231217 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230303	20230302 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240410	20240409 news found
3661 世芯 tw tv8
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230306	20230305 news found
2603 長榮 tw tv6
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231219	20231218 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231128	20231127 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240411	20240410 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231220	20231219 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231129	20231128 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240412	20240411 news found
3661 世芯 tw tv9
2603 長榮 tw tv7
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240415	20240414 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230307	20230306 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231130	20231129 news found
2408 南亞科 tw tv1
2603 長榮 tw tv8
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230308	20230307 news found
3661 世芯 tw tv10
Start Running Genetic Algorithm
2408 南亞科 tw tv2
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240416	20240415 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231201	20231130 news found
2408 南亞科 tw tv3
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240417	20240416 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230309	20230308 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231204	20231203 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231221	20231220 news found
3661 世芯 tw tv11
2408 南亞科 tw tv4
Start Running Genetic Algorithm
Start Running Genetic Algorithm
2207 和泰車 tw tv30
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230310	20230309 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240418	20240417 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231205	20231204 news found
2408 南亞科 tw tv5
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240419	20240418 news found
2603 長榮 tw tv9
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231206	20231205 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231222	20231221 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230313	 no news found in 20230312
Processing for date 20230314	20230313 news found
3661 世芯 tw tv12
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231207	20231206 news found
Start Running Genetic Algorithm
2408 南亞科 tw tv6
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231225	20231224 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230315	20230314 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231208	20231207 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240422	20240421 news found
2603 長榮 tw tv10
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230316	20230315 news found
2408 南亞科 tw tv7
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231226	20231225 news found
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240423	20240422 news found
3661 世芯 tw tv13
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231227	20231226 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231211	20231210 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240424	20240423 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230317	20230316 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231228	20231227 news found
2603 長榮 tw tv11
2408 南亞科 tw tv8
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240425	20240424 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231212	20231211 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231229	20231228 news found
3661 世芯 tw tv14
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230320	20230319 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240426	20240425 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231213	20231212 news found
2408 南亞科 tw tv9
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230321	20230320 news found
Start Running Genetic Algorithm
2603 長榮 tw tv12
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240102	20240101 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240429	20240428 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230322	20230321 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240103	20240102 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240430	20240429 news found
2408 南亞科 tw tv10
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231214	20231213 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230323	20230322 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240104	20240103 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240502	20240501 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231215	20231214 news found
2603 長榮 tw tv13
Start Running Genetic Algorithm
3661 世芯 tw tv15
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240105	20240104 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231218	20231217 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230324	20230323 news found
2408 南亞科 tw tv11
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240503	20240502 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240108	20240107 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231219	20231218 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230327	20230326 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240506	20240505 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240109	20240108 news found
2408 南亞科 tw tv12
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230328	20230327 news found
2603 長榮 tw tv14
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240110	20240109 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240507	20240506 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231220	20231219 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240111	20240110 news found
3661 世芯 tw tv16
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240508	20240507 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231221	20231220 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230329	20230328 news found
2408 南亞科 tw tv13
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240509	20240508 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240112	20240111 news found
2603 長榮 tw tv15
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230330	20230329 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240510	20240509 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240115	20240114 news found
3661 世芯 tw tv17
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240513	20240512 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230331	20230330 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240116	20240115 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231222	20231221 news found
2408 南亞科 tw tv14
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230406	20230405 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240514	20240513 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240117	20240116 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231225	20231224 news found
2603 長榮 tw tv16
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230407	20230406 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240118	20240117 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240515	20240514 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231226	20231225 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230410	20230409 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240119	20240118 news found
3661 世芯 tw tv18
Start Running Genetic Algorithm
2408 南亞科 tw tv15
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231227	20231226 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240516	20240515 news found
2603 長榮 tw tv17
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240122	20240121 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230411	20230410 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240123	20240122 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231228	20231227 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230412	20230411 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240517	20240516 news found
3661 世芯 tw tv19
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230413	20230412 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231229	20231228 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240520	20240519 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230414	20230413 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240124	20240123 news found
2603 長榮 tw tv18
2408 南亞科 tw tv16
Start Running Genetic Algorithm
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240102	20240101 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230417	20230416 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240103	20240102 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230418	20230417 news found
3661 世芯 tw tv20
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240521	20240520 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240125	20240124 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2408 南亞科 tw tv26
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240226	20240225 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240327	20240326 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230605	20230604 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240708	20240707 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240227	20240226 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240328	20240327 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240709	20240708 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230606	20230605 news found
3661 世芯 tw tv29
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240329	20240328 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240229	20240228 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240710	20240709 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230607	20230606 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240401	20240331 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240301	20240229 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230608	20230607 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240711	20240710 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240402	20240401 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240304	20240303 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230609	20230608 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240712	20240711 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240403	20240402 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240305	20240304 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230612	20230611 news found
2603 長榮 tw tv29
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240715	20240714 news found
2408 南亞科 tw tv27
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240408	20240407 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230613	20230612 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240306	20240305 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240716	20240715 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240409	20240408 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240307	20240306 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240717	20240716 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230614	20230613 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240410	20240409 news found
3661 世芯 tw tv30
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240308	20240307 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240411	20240410 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240718	20240717 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240311	20240310 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240719	20240718 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230615	20230614 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240412	20240411 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240312	20240311 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240722	20240721 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230616	20230615 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240415	20240414 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240723	20240722 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240313	20240312 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230619	20230618 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240416	20240415 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240726	20240725 news found
2603 長榮 tw tv30
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240314	20240313 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230620	20230619 news found
2408 南亞科 tw tv28
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240729	20240728 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240417	20240416 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240730	20240729 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240418	20240417 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240315	20240314 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240731	20240730 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230621	20230620 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240419	20240418 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230626	20230625 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240422	20240421 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240801	20240731 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240318	20240317 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230627	20230626 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240802	20240801 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240319	20240318 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240423	20240422 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230628	20230627 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240320	20240319 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240805	20240804 news found
2408 南亞科 tw tv29

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240424	20240423 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230629	20230628 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230630	20230629 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240425	20240424 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240806	20240805 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240426	20240425 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240321	20240320 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230703	20230702 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240429	20240428 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230704	20230703 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240807	20240806 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240430	20240429 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230705	20230704 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240808	20240807 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240322	20240321 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2408 南亞科 tw tv30
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240502	20240501 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230706	20230705 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240809	20240808 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240325	20240324 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240503	20240502 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240812	20240811 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240326	20240325 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240506	20240505 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240813	20240812 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230707	20230706 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240507	20240506 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240327	20240326 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230710	20230709 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240814	20240813 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240508	20240507 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230711	20230710 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240815	20240814 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240509	20240508 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230712	20230711 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240328	20240327 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240510	20240509 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240816	20240815 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230713	20230712 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240513	20240512 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240329	20240328 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230714	20230713 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240514	20240513 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240819	20240818 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240401	20240331 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230717	20230716 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240820	20240819 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230718	20230717 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240402	20240401 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240515	20240514 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240403	20240402 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240821	20240820 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240516	20240515 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240408	20240407 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240822	20240821 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230719	20230718 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240517	20240516 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240409	20240408 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240520	20240519 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230720	20230719 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240823	20240822 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240521	20240520 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230721	20230720 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240826	20240825 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240522	20240521 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240410	20240409 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230724	20230723 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240827	20240826 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240411	20240410 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230725	20230724 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240523	20240522 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240412	20240411 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240828	20240827 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240524	20240523 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230726	20230725 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240415	20240414 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240829	20240828 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240527	20240526 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230727	20230726 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240416	20240415 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240528	20240527 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230728	20230727 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240417	20240416 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240529	20240528 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240830	20240829 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240418	20240417 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230731	20230730 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240530	20240529 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240419	20240418 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240902	20240901 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240531	20240530 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240422	20240421 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240603	20240602 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230801	20230731 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240604	20240603 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240903	20240902 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230802	20230801 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240423	20240422 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230804	20230803 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240605	20240604 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230807	20230806 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240424	20240423 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240606	20240605 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240904	20240903 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240425	20240424 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240607	20240606 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240905	20240904 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230808	20230807 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240426	20240425 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240611	20240610 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230809	20230808 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240429	20240428 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240906	20240905 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230810	20230809 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240612	20240611 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240430	20240429 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240909	20240908 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230811	20230810 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240502	20240501 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240613	20240612 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240910	20240909 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230814	20230813 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240503	20240502 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240614	20240613 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240911	20240910 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230815	20230814 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240506	20240505 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240912	20240911 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240507	20240506 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230816	20230815 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240913	20240912 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240508	20240507 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240617	20240616 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230817	20230816 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240509	20240508 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240916	20240915 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240618	20240617 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240918	20240917 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230818	20230817 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240510	20240509 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240619	20240618 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240919	20240918 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240513	20240512 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240920	20240919 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230821	20230820 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2382 廣達 tw tv5
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231204	20231203 news found
2382 廣達 tw tv6
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241008	20241007 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240820	20240819 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231205	20231204 news found
2382 廣達 tw tv7
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241009	20241008 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240821	20240820 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231206	20231205 news found
2382 廣達 tw tv8
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241011	20241010 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240822	20240821 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231207	20231206 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241014	20241013 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231208	20231207 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2382 廣達 tw tv9
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240823	20240822 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241015	20241014 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231211	20231210 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241016	20241015 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231212	20231211 news found
2382 廣達 tw tv10
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240826	20240825 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241017	20241016 news found
2382 廣達 tw tv11
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241018	20241017 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231213	20231212 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240827	20240826 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231214	20231213 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2382 廣達 tw tv12
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240828	20240827 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240829	20240828 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231215	20231214 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241021	20241020 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2382 廣達 tw tv13
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240830	20240829 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240902	20240901 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231218	20231217 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241022	20241021 news found

/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:16: RuntimeWarning: invalid value encountered in scalar divide
/var/folders/xc/rjj8m66j6xs5pgcp1hc7g2kr0000gn/T/ipykernel_89752/3705918672.py:17: RuntimeWarning: invalid value encountered in scalar divide

2382 廣達 tw tv14
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231219	20231218 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240903	20240902 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231220	20231219 news found
2382 廣達 tw tv15
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231221	20231220 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241023	20241022 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240904	20240903 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231222	20231221 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240905	20240904 news found
2382 廣達 tw tv16
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231225	20231224 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241024	20241023 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240906	20240905 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231226	20231225 news found
2382 廣達 tw tv17
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240909	20240908 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231227	20231226 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241025	20241024 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240910	20240909 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231228	20231227 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240911	20240910 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241028	20241027 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20231229	20231228 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240912	20240911 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241029	20241028 news found
2382 廣達 tw tv18
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240102	20240101 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241030	20241029 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240913	20240912 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240103	20240102 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240916	20240915 news found
2382 廣達 tw tv19
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240104	20240103 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240918	20240917 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240919	20240918 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241101	20241031 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240105	20240104 news found
2382 廣達 tw tv20
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240920	20240919 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240108	20240107 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241104	20241103 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240923	20240922 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240109	20240108 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241105	20241104 news found
2382 廣達 tw tv21
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240924	20240923 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241106	20241105 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240925	20240924 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241107	20241106 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240110	20240109 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241108	20241107 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240111	20240110 news found
2382 廣達 tw tv22
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240926	20240925 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241111	20241110 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240112	20240111 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241112	20241111 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240115	20240114 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240927	20240926 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241113	20241112 news found
2382 廣達 tw tv23
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240116	20240115 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241114	20241113 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240930	20240929 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240117	20240116 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241115	20241114 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240118	20240117 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241118	20241117 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241001	20240930 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240119	20240118 news found
2382 廣達 tw tv24
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241004	20241003 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241119	20241118 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240122	20240121 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241007	20241006 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241120	20241119 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240123	20240122 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241008	20241007 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240124	20240123 news found
2382 廣達 tw tv25
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241121	20241120 news found
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241122	20241121 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241009	20241008 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240125	20240124 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241011	20241010 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240126	20240125 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241125	20241124 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240129	20240128 news found
2382 廣達 tw tv26
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241126	20241125 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240130	20240129 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241127	20241126 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241014	20241013 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241128	20241127 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241129	20241128 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240131	20240130 news found
2382 廣達 tw tv27
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241202	20241201 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240201	20240131 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241015	20241014 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241203	20241202 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240202	20240201 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241016	20241015 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241204	20241203 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241205	20241204 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241017	20241016 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240205	20240204 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241206	20241205 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241209	20241208 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240215	20240214 news found
2382 廣達 tw tv28
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241018	20241017 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241210	20241209 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241021	20241020 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240216	20240215 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241211	20241210 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241022	20241021 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240219	20240218 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241212	20241211 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241023	20241022 news found
2382 廣達 tw tv29
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241213	20241212 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241024	20241023 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240220	20240219 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241216	20241215 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241025	20241024 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241217	20241216 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241028	20241027 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240221	20240220 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241218	20241217 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240222	20240221 news found
2382 廣達 tw tv30
Start Running Genetic Algorithm
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241219	20241218 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240223	20240222 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241029	20241028 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241220	20241219 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240226	20240225 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241223	20241222 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20241030	20241029 news found
Ungenerated list ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20240227	20240226 news found

    tv Ann_Train_RTN Ann_Train_B&H Ann_Test_RTN Ann_Test_B&H  Win B&H    Diff
0    1       105.68%        -0.21%       10.39%        8.70%     True   1.69%
1    2        42.68%        -0.05%       15.14%        9.40%     True   5.74%
2    3        32.20%        -7.58%       15.66%       11.01%     True   4.65%
3    4        24.77%       -15.35%        9.31%       12.97%    False  -3.67%
4    5        23.31%       -16.88%        9.62%       14.71%    False  -5.09%
5    6        17.49%       -19.17%       14.83%       17.55%    False  -2.72%
6    7        15.17%       -17.84%       18.54%       18.48%     True   0.06%
7    8        17.34%       -15.57%       15.57%       20.55%    False  -4.98%
8    9        18.91%       -11.70%       17.71%       18.58%    False  -0.87%
9   10        20.34%       -10.46%       14.22%       20.71%    False  -6.49%
10  11        17.90%        -8.62%       17.90%       19.43%    False  -1.53%
11  12        19.20%        -6.26%       13.26%       19.58%    False  -6.32%
12  13        17.22%        -2.41%       15.30%       18.59%    False  -3.29%
13  14        19.78%        -1.08%       18.60%       18.62%    False  -0.02%
14  15        20.90%         6.93%       20.23%       11.27%     True   8.96%
15  16        22.44%         8.60%       18.35%       11.57%     True   6.78%
16  17        22.57%         8.84%       17.18%       13.41%     True   3.77%
17  18        21.25%         6.78%       18.57%       13.88%     True   4.69%
18  19        19.14%         5.37%       21.30%       16.73%     True   4.58%
19  20        17.26%         7.27%       25.03%       14.77%     True  10.25%
20  21        16.77%         8.11%       31.25%       14.28%     True  16.97%
21  22        15.33%         9.17%       28.60%       13.28%     True  15.32%
22  23        16.12%        10.72%       36.92%        6.65%     True  30.27%
23  24        16.00%         9.25%       43.79%        8.08%     True  35.71%
24  25        14.40%        10.40%       59.98%        2.80%     True  57.18%
25  26        14.85%        11.79%       75.99%       -3.51%     True  79.51%
26  27        18.78%         8.16%       70.30%       11.98%     True  58.31%
27  28        18.19%         7.93%       47.95%       19.40%     True  28.55%
28  29        19.73%         9.29%       59.93%       18.75%     True  41.18%
29  30        20.42%         9.00%      157.39%       92.50%     True  64.89%

# TV-3 Usable Exp Threshold DayTrade

In [5]:
from TV_usableexp_dt_thres_stock import TV_UsableExpThresDT
import pandas as pd
from joblib import Parallel, delayed
from datetime import datetime

avgs = pd.DataFrame()
selected_columns = ['accuracy', 'precision', 'ev', 'precision_ev', 'avail_count', 'tp', 'fp', 'tn', 'fn']

def process_stock(stock, i):
    stock_avg_list = []  # 存放該支股票所有 TV 的結果
    
    for date_range in data_range_tv:
        env = {
            "stock_id": stock[0],
            "stock_name": stock[1],
            "country": stock[2],
            "start_date": date_range[0],
            "end_date": date_range[1],
            "tv": date_range[2],
            "run_count": str(i)
        }
        print(env['stock_id'], env['stock_name'], env['country'], f"tv{date_range[2]}")
        
        eval_module = TV_UsableExpThresDT(env)
        eval_module.run()
        train_datarange, test_datarange = eval_module.split_exp(date_range[2])
        
        mode = 1
        eval_module.training(mode, train_datarange, test_datarange)
        
        result = eval_module.get_result(1)  # Test 結果
        result_test = result["test"]  # Test 結果
        
        # Training & Test 報酬計算
        train_date, train_bnh_balance, train_stag_rtn = eval_module.get_return_list('train')
        train_stag_balance = get_balance_list(train_stag_rtn, train_bnh_balance[0])
        
        list_date, list_bnh_balance, list_stag_rtn = eval_module.get_return_list('test')
        list_stag_balance = get_balance_list(list_stag_rtn, list_bnh_balance[0])
        
        # 計算天數
        train_N_days = (datetime.strptime(sorted(train_datarange.keys())[-1], '%Y%m%d') - 
                        datetime.strptime(sorted(train_datarange.keys())[0], '%Y%m%d')).days
        test_N_days = (datetime.strptime(sorted(test_datarange.keys())[-1], '%Y%m%d') - 
                       datetime.strptime(sorted(test_datarange.keys())[0], '%Y%m%d')).days

        stock_avg = cacl_avg(pd.DataFrame([result_test]).loc[:, selected_columns])
        stock_avg['stock_id'] = stock[0]
        stock_avg['tv'] = date_range[2]
        stock_avg['Train_RTN'] = (train_stag_balance[-1] / train_bnh_balance[0] - 1) * 100
        stock_avg['Train_B&H'] = (train_bnh_balance[-1] / train_bnh_balance[0] - 1) * 100
        stock_avg['Ann_Train_RTN'] = ((1 + stock_avg['Train_RTN'] / 100) ** (252 / train_N_days) - 1) * 100
        stock_avg['Ann_Train_B&H'] = ((1 + stock_avg['Train_B&H'] / 100) ** (252 / train_N_days) - 1) * 100
        stock_avg['RTN'] = (list_stag_balance[-1] / list_bnh_balance[0] - 1) * 100
        stock_avg['B&H'] = (list_bnh_balance[-1] / list_bnh_balance[0] - 1) * 100
        stock_avg['Ann_RTN'] = ((1 + stock_avg['RTN'] / 100) ** (252 / test_N_days) - 1) * 100
        stock_avg['Ann_B&H'] = ((1 + stock_avg['B&H'] / 100) ** (252 / test_N_days) - 1) * 100
        stock_avg['win B&H'] = "yes" if list_stag_balance[-1] > list_bnh_balance[-1] else "no"

        stock_avg_list.append(stock_avg)
    
    return pd.concat(stock_avg_list) if stock_avg_list else None

def runAll_parallel(i):
    results = Parallel(n_jobs=-1)(delayed(process_stock)(stock, i) for stock in data)
    return pd.concat([res for res in results if res is not None])

# 迭代執行
for i in range(1):
    print(i+1)
    avgs = pd.concat([avgs, runAll_parallel(i+1)])
    
tv_avg_df = avgs.groupby("tv")[["RTN", "B&H", "Ann_RTN", "Ann_B&H", "Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H"]].mean().reset_index()
tv_avg_df["Test_RTN"] = tv_avg_df["RTN"]
tv_avg_df["Test_B&H"] = tv_avg_df["B&H"]
tv_avg_df["Ann_Test_RTN"] = tv_avg_df["Ann_RTN"]
tv_avg_df["Ann_Test_B&H"] = tv_avg_df["Ann_B&H"]
tv_avg_df["Win B&H"] = tv_avg_df["Ann_Test_RTN"] > tv_avg_df["Ann_Test_B&H"]
tv_avg_df["Diff"] = tv_avg_df["Ann_Test_RTN"] - tv_avg_df["Ann_Test_B&H"]
# 計算 tv_avg_df 中 Diff 的總平均
avg_diff = tv_avg_df["Diff"].mean()
tv_avg_df[["Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H", "RTN", "B&H", "Ann_Test_RTN", "Ann_Test_B&H", "Diff"]] = tv_avg_df[["Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H", "RTN", "B&H", "Ann_Test_RTN", "Ann_Test_B&H", "Diff"]].map(lambda x: f"{x:.2f}%")

display(tv_avg_df.loc[:, ["tv", "Ann_Train_RTN", "Ann_Train_B&H", "Ann_Test_RTN", "Ann_Test_B&H", "Win B&H", "Diff"]])

# 計算 tv_avg_df 中 Win B&H True 的比例
wincount = tv_avg_df["Win B&H"].sum()
ttl_count = tv_avg_df["Win B&H"].count()
print(f"Win B&H: {wincount / ttl_count:.2f}, Avg Diff: {avg_diff:.2f}%")

1
2330 台積電 tw tv1
2308 台達電 tw tv1
2412 中華電 tw tv1
2881 富邦金 tw tv1
2382 廣達 tw tv1
2454 聯發科 tw tv1
2317 鴻海 tw tv1
2882 國泰金 tw tv1
2330 台積電 tw tv2
2308 台達電 tw tv2
2412 中華電 tw tv2
2382 廣達 tw tv2
2881 富邦金 tw tv2
2454 聯發科 tw tv2
2317 鴻海 tw tv2
2882 國泰金 tw tv2
2330 台積電 tw tv3
2308 台達電 tw tv3
2412 中華電 tw tv3
2382 廣達 tw tv3
2881 富邦金 tw tv3
2454 聯發科 tw tv3
2317 鴻海 tw tv3
2882 國泰金 tw tv3
2330 台積電 tw tv4
2308 台達電 tw tv4
2382 廣達 tw tv4
2412 中華電 tw tv4
2881 富邦金 tw tv4
2454 聯發科 tw tv4
2317 鴻海 tw tv4
2882 國泰金 tw tv4
2330 台積電 tw tv5
2308 台達電 tw tv5
2881 富邦金 tw tv5
2382 廣達 tw tv5
2412 中華電 tw tv5
2454 聯發科 tw tv5
2882 國泰金 tw tv5
2317 鴻海 tw tv5
2330 台積電 tw tv6
2308 台達電 tw tv6
2382 廣達 tw tv6
2454 聯發科 tw tv6
2881 富邦金 tw tv6
2412 中華電 tw tv6
2882 國泰金 tw tv6
2317 鴻海 tw tv6
2330 台積電 tw tv7
2382 廣達 tw tv7
2308 台達電 tw tv7
2454 聯發科 tw tv7
2412 中華電 tw tv7
2882 國泰金 tw tv7
2881 富邦金 tw tv7
2317 鴻海 tw tv7
2330 台積電 tw tv8
2382 廣達 tw tv8
2308 台達電 tw tv8
2454 聯發科 tw tv8
2412 中華電 tw tv8
2882 國泰金 tw tv8
2317 鴻海 tw tv8
2881 富邦金 tw tv8
2330 台積電 tw tv9
2454 聯發科 tw tv9
2382 廣達 tw tv9
2308 台達電 tw tv9
2412 中華電 tw tv9
2882 國泰金 tw tv9
2317 鴻海 tw tv9
2881 富邦金 tw tv9
2330 台積電 tw tv10
2382 廣達 tw tv10
2454 聯發科 tw tv10
2308 台達電 tw tv10
2882 國泰金 tw tv10
2412 中華電 tw tv10
2317 鴻海 tw tv10
2881 富邦金 tw tv10
2330 台積電 tw tv11
2382 廣達 tw tv11
2454 聯發科 tw tv11
2308 台達電 tw tv11
2882 國泰金 tw tv11
2412 中華電 tw tv11
2317 鴻海 tw tv11
2881 富邦金 tw tv11
2330 台積電 tw tv12
2382 廣達 tw tv12
2454 聯發科 tw tv12
2308 台達電 tw tv12
2412 中華電 tw tv12
2882 國泰金 tw tv12
2317 鴻海 tw tv12
2881 富邦金 tw tv12
2330 台積電 tw tv13
2382 廣達 tw tv13
2454 聯發科 tw tv13
2308 台達電 tw tv13
2412 中華電 tw tv13
2317 鴻海 tw tv13
2882 國泰金 tw tv13
2881 富邦金 tw tv13
2330 台積電 tw tv14
2382 廣達 tw tv14
2454 聯發科 tw tv14
2308 台達電 tw tv14
2412 中華電 tw tv14
2881 富邦金 tw tv14
2882 國泰金 tw tv14
2317 鴻海 tw tv14
2330 台積電 tw tv15
2382 廣達 tw tv15
2454 聯發科 tw tv15
2308 台達電 tw tv15
2412 中華電 tw tv15
2317 鴻海 tw tv15
2881 富邦金 tw tv15
2882 國泰金 tw tv15
2330 台積電 tw tv16
2382 廣達 tw tv16
2454 聯發科 tw tv16
2308 台達電 tw tv16
2412 中華電 tw tv16
2881 富邦金 tw tv16
2317 鴻海 tw tv16
2882 國泰金 tw tv16
2330 台積電 tw tv17
2382 廣達 tw tv17
2454 聯發科 tw tv17
2308 台達電 tw tv17
2317 鴻海 tw tv17
2412 中華電 tw tv17
2330 台積電 tw tv18
2881 富邦金 tw tv17
2882 國泰金 tw tv17
2382 廣達 tw tv18
2454 聯發科 tw tv18
2308 台達電 tw tv18
2412 中華電 tw tv18
2317 鴻海 tw tv18
2330 台積電 tw tv19
2881 富邦金 tw tv18
2382 廣達 tw tv19
2882 國泰金 tw tv18
2454 聯發科 tw tv19
2308 台達電 tw tv19
2317 鴻海 tw tv19
2412 中華電 tw tv19
2881 富邦金 tw tv19
2882 國泰金 tw tv19
2330 台積電 tw tv20
2382 廣達 tw tv20
2454 聯發科 tw tv20
2308 台達電 tw tv20
2317 鴻海 tw tv20
2412 中華電 tw tv20
2881 富邦金 tw tv20
2330 台積電 tw tv21
2382 廣達 tw tv21
2882 國泰金 tw tv20
2454 聯發科 tw tv21
2308 台達電 tw tv21
2412 中華電 tw tv21
2317 鴻海 tw tv21
2881 富邦金 tw tv21
2330 台積電 tw tv22
2882 國泰金 tw tv21
2382 廣達 tw tv22
2454 聯發科 tw tv22
2308 台達電 tw tv22
2412 中華電 tw tv22
2317 鴻海 tw tv22
2881 富邦金 tw tv22
2382 廣達 tw tv23
2882 國泰金 tw tv22
2330 台積電 tw tv23
2454 聯發科 tw tv23
2308 台達電 tw tv23
2412 中華電 tw tv23
2881 富邦金 tw tv23
2882 國泰金 tw tv23
2317 鴻海 tw tv23
2330 台積電 tw tv24
2382 廣達 tw tv24
2454 聯發科 tw tv24
2308 台達電 tw tv24
2412 中華電 tw tv24
2317 鴻海 tw tv24
2881 富邦金 tw tv24
2882 國泰金 tw tv24
2330 台積電 tw tv25
2382 廣達 tw tv25
2454 聯發科 tw tv25
2412 中華電 tw tv25
2308 台達電 tw tv25
2317 鴻海 tw tv25
2881 富邦金 tw tv25
2330 台積電 tw tv26
2882 國泰金 tw tv25
2382 廣達 tw tv26
2454 聯發科 tw tv26
2412 中華電 tw tv26
2308 台達電 tw tv26
2881 富邦金 tw tv26
2317 鴻海 tw tv26
2882 國泰金 tw tv26
2330 台積電 tw tv27
2382 廣達 tw tv27
2454 聯發科 tw tv27
2412 中華電 tw tv27
2881 富邦金 tw tv27
2308 台達電 tw tv27
2317 鴻海 tw tv27
2882 國泰金 tw tv27
2330 台積電 tw tv28
2382 廣達 tw tv28
2454 聯發科 tw tv28
2412 中華電 tw tv28
2881 富邦金 tw tv28
2317 鴻海 tw tv28
2308 台達電 tw tv28
2882 國泰金 tw tv28
2330 台積電 tw tv29
2382 廣達 tw tv29
2454 聯發科 tw tv29
2412 中華電 tw tv29
2308 台達電 tw tv29
2317 鴻海 tw tv29
2881 富邦金 tw tv29
2330 台積電 tw tv30
2882 國泰金 tw tv29
2382 廣達 tw tv30
2454 聯發科 tw tv30
2412 中華電 tw tv30
2881 富邦金 tw tv30
2308 台達電 tw tv30
2317 鴻海 tw tv30
2882 國泰金 tw tv30
2891 中信金 tw tv1
6505 台塑化 tw tv1
2891 中信金 tw tv2
6505 台塑化 tw tv2
6505 台塑化 tw tv3
2891 中信金 tw tv3
6505 台塑化 tw tv4
2891 中信金 tw tv4
6505 台塑化 tw tv5
2891 中信金 tw tv5
6505 台塑化 tw tv6
2891 中信金 tw tv6
6505 台塑化 tw tv7
2891 中信金 tw tv7
6505 台塑化 tw tv8
2891 中信金 tw tv8
6505 台塑化 tw tv9
2891 中信金 tw tv9
6505 台塑化 tw tv10
2891 中信金 tw tv10
6505 台塑化 tw tv11
2891 中信金 tw tv11
6505 台塑化 tw tv12
2891 中信金 tw tv12
6505 台塑化 tw tv13
2891 中信金 tw tv13
6505 台塑化 tw tv14
2891 中信金 tw tv14
6505 台塑化 tw tv15
2891 中信金 tw tv15
6505 台塑化 tw tv16
6505 台塑化 tw tv17
2891 中信金 tw tv16
6505 台塑化 tw tv18
2891 中信金 tw tv17
6505 台塑化 tw tv19
2891 中信金 tw tv18
6505 台塑化 tw tv20
2891 中信金 tw tv19
6505 台塑化 tw tv21
2891 中信金 tw tv20
6505 台塑化 tw tv22
2891 中信金 tw tv21
6505 台塑化 tw tv23
2891 中信金 tw tv22
6505 台塑化 tw tv24
2891 中信金 tw tv23
6505 台塑化 tw tv25
2891 中信金 tw tv24
6505 台塑化 tw tv26
2891 中信金 tw tv25
6505 台塑化 tw tv27
2891 中信金 tw tv26
6505 台塑化 tw tv28
2891 中信金 tw tv27
6505 台塑化 tw tv29
2891 中信金 tw tv28
6505 台塑化 tw tv30
2891 中信金 tw tv29
2891 中信金 tw tv30

    tv Ann_Train_RTN Ann_Train_B&H Ann_Test_RTN Ann_Test_B&H  Win B&H    Diff
0    1       115.12%         7.22%       15.12%        6.82%     True   8.30%
1    2        40.70%        -9.15%       16.07%        8.46%     True   7.60%
2    3        29.56%        -5.36%       15.22%        9.23%     True   5.99%
3    4        17.60%       -17.58%       18.20%       11.87%     True   6.34%
4    5        12.41%       -14.22%       19.47%       12.43%     True   7.04%
5    6        14.62%       -16.67%       21.30%       14.41%     True   6.88%
6    7        16.98%       -17.10%       19.76%       15.76%     True   4.00%
7    8        16.06%       -19.25%       24.61%       20.14%     True   4.47%
8    9        16.15%       -14.92%       20.26%       17.74%     True   2.51%
9   10        15.12%       -13.89%       22.04%       20.16%     True   1.87%
10  11        15.99%       -11.19%       25.82%       18.54%     True   7.28%
11  12        15.82%        -9.16%       25.41%       19.19%     True   6.22%
12  13        17.17%        -7.41%       24.79%       19.97%     True   4.82%
13  14        13.39%        -6.28%       28.95%       21.03%     True   7.91%
14  15        16.33%        -0.85%       30.18%       15.70%     True  14.48%
15  16        16.14%         0.17%       30.51%       16.08%     True  14.43%
16  17        16.80%         1.42%       31.66%       17.96%     True  13.70%
17  18        16.35%        -0.09%       33.09%       19.49%     True  13.60%
18  19        16.06%        -0.85%       35.54%       22.30%     True  13.24%
19  20        14.81%         0.64%       42.29%       22.10%     True  20.19%
20  21        15.61%         0.89%       45.36%       24.31%     True  21.05%
21  22        15.32%         1.77%       47.10%       24.13%     True  22.96%
22  23        16.48%         5.19%       42.48%       14.92%     True  27.57%
23  24        17.92%         4.38%       47.95%       16.52%     True  31.43%
24  25        17.19%         6.55%       54.44%        9.08%     True  45.35%
25  26        18.21%         9.63%       41.08%       -6.15%     True  47.23%
26  27        22.68%         6.54%       39.06%        9.49%     True  29.57%
27  28        21.27%         6.00%       37.47%       19.35%     True  18.12%
28  29        21.93%         8.27%       43.42%       -7.72%     True  51.14%
29  30        23.17%         7.42%       46.79%       15.45%     True  31.34%

Win B&H: 1.00, Avg Diff: 16.55%

# Reserch

In [5]:
from TV_usableexp_dt_thres_stock import TV_UsableExpThresDT
import json

length = 24
ttl_indiv = [0] * length

for stock in data:
    print(stock[0], stock[1])
    for date_range in data_range_tv:
        env = {
            "stock_id" : stock[0],
            "stock_name" : stock[1],
            "country" : stock[2],
            "start_date" : date_range[0],
            "end_date" : date_range[1],
            "tv" : date_range[2],
            "run_count" : str(1)
        }

        eval_module = TV_UsableExpThresDT(env)
        indiv, text = eval_module.get_individual_with_factors(1)

        for idx, e in enumerate(indiv):
            if idx < length:
                if e == 1:
                    ttl_indiv[idx] += 1
                
ttl_indiv = [(i+1, ttl_indiv[i]) for i in range(len(ttl_indiv))]
ttl_indiv.sort(key=lambda x: x[1], reverse=True)

with open("/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Factors/UsableExp.json", "r") as f:
    factors = json.load(f)
for e in ttl_indiv:
    # 刪除因子中 '：' 之後的字串
    factors[str(e[0])] = factors[str(e[0])].split("：")[0]
    print(e,factors[str(e[0])])

2330 台積電
2308 台達電
2317 鴻海
2382 廣達
2412 中華電
2454 聯發科
2881 富邦金
2882 國泰金
2891 中信金
6505 台塑化
(8, 293) 內部重組與裁員動向
(4, 289) 競爭壓力
(7, 286) 供應鏈與生產挑戰
(21, 167) 勞動力短缺或薪資調整
(6, 160) 市場情緒與分析師預測
(11, 159) 產業景氣循環
(10, 158) 貨幣政策與利率變動
(20, 157) 物流成本上升
(23, 154) 原物料短期價格波動
(24, 153) 關鍵零件缺貨或供應短缺
(15, 152) ESG（環境、社會、治理）影響
(3, 149) 市場情緒或經濟影響
(14, 148) 市場黑天鵝事件
(16, 148) 股利政策與回購計畫
(18, 143) 工廠稼動率變動
(12, 133) 企業併購與合作
(13, 133) 法律與監管風險
(22, 133) 內部成本控制策略
(9, 128) 資金流動與外資動向
(19, 116) 短期訂單波動
(5, 115) 產品創新與新技術發布
(17, 111) 供應鏈備貨與庫存調整
(1, 110) 外部利好或政策支持
(2, 107) 營收或財務表現

In [ ]:
# def calculate_cagr(total_return: float, years: int) -> float:
#     """
#     計算年化報酬率（CAGR）
#     :param total_return: 總報酬率（以小數表示，例如 180.74% = 1.8074）
#     :param years: 投資期間（年數）
#     :return: 年化報酬率（CAGR，以小數表示）
#     """
#     return (1 + total_return) ** (1 / years) - 1

# # 三年的數據
# rtn_total = 1.8074  # 180.74% 轉換為小數
# bh_total = 0.2644  # 26.44% 轉換為小數
# years = 3

# # 計算年化報酬率
# rtn_cagr = calculate_cagr(rtn_total, years)
# bh_cagr = calculate_cagr(bh_total, years)

# print(f"策略年化報酬率 (CAGR): {rtn_cagr:.2%}")
# print(f"B&H 年化報酬率 (CAGR): {bh_cagr:.2%}")

# Danger Zone

In [6]:
# # Delete folders named in the directory tree
# import os
# import shutil

# # Set the root directory for the project
# root_dir = r"/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Training_result_TV/UsableExpThresDT_F16"

# # Walk the directory tree and delete folders named 
# for dirpath, dirnames, filenames in os.walk(root_dir, topdown=False):
#     for dirname in dirnames:
#         if dirname.lower() == "2382":
#             full_path = os.path.join(dirpath, dirname)
#             print(f"Deleting folder: {full_path}")
#             shutil.rmtree(full_path)

In [12]:
# # 合併 Usable 跟 F42 變成 F24
# import json
# import os

# new_expands = {}

# for stock in data:
#     exp2_exist = False
#     print(f"stock: {stock[0]}")
#     if not os.path.exists(f"out_stock/Expands/F42/{stock[0]}/expand.json"):
#         print(f"{stock[0]} Not exist")
#         continue
    
#     with open(f"out_stock/Expands/F42/{stock[0]}/expand.json", "r") as f:
#         expand = json.load(f)
#     new_expands["model"] = expand["model"]
#     new_expands["temperature"] = expand["temperature"]
#     new_expands["stock_id"] = expand["stock_id"]
#     new_expands["output_data"] = {}
    
#     if os.path.exists(f"out_stock/Expands/FactorUsable/{stock[0]}/expand.json"):
#         exp2_exist = True
#         with open(f"out_stock/Expands/FactorUsable/{stock[0]}/expand.json", "r") as f:
#             expand2 = json.load(f)
    
#     date = expand["output_data"].keys()
#     for d in date:
#         # print(d)
#         new_expands["output_data"][d] = {"skeleton": {}}  # Ensure the structure exists

#         if exp2_exist:
#             # print("usable exist")
#             factors2 = expand2["output_data"][d]["skeleton"].keys()
#             for factor in factors2:
#                 new_expands["output_data"][d]["skeleton"][factor] = expand2["output_data"][d]['skeleton'][factor]
#         else:
#             print("usable not exist")
        
#         factors = expand["output_data"][d]["skeleton"].keys()
#         for factor in factors:
#             new_factor = str(int(factor) + 8)
#             if int(new_factor) > 24:
#                 continue
#             new_expands["output_data"][d]["skeleton"][new_factor] = expand["output_data"][d]['skeleton'][factor]


#     # print(new_expands["output_data"]["20230403"]['skeleton'])
#     os.makedirs(f"out_stock/Expands/F24/{stock[0]}", exist_ok=True)
#     with open(f"out_stock/Expands/F24/{stock[0]}/expand.json", "w") as f:
#         json.dump(new_expands, f, indent=4)
#     # break

In [ ]:
# # rename path1 to path2
# import os

# for stock in data:
#     path1 = f"/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Expands/FactorUsable/{stock[0]}/expand.json"
#     path2 = f"/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Expands/UsableExp/{stock[0]}_expand.json"


#     os.rename(path1, path2)