# Setting TV

In [6]:
import pandas as pd
from datetime import datetime

# 買進賣出需要的手續費
fee = {
    "tax_stock": 0.003,  # 賣出0.003
    "tax_future": 0.00002 * 2,  # 買進與賣出各0.00002
    "fee_stock": 0.001425 * 2,  # 券商手續費公道價，買進與賣出各0.001425
    "fee_future": 0.00002 * 2,  # 各家不大相同，以交易稅計算
    "sliding_price": 0.00001,  # 滑價
}

# 股票清單
# tw_index_fee = 0
tw_stock_fee = 0
# tw_stock_fee = fee["tax_stock"] + fee["fee_stock"] + fee["sliding_price"]
tw_index_fee = fee["tax_future"] + fee["fee_future"] + fee["sliding_price"]

data = [
    ["2330", "台積電", "tw"],
    ["2308", "台達電", "tw", tw_stock_fee],
    ["2317", "鴻海", "tw", tw_stock_fee],
    ["2382", "廣達", "tw", tw_stock_fee],
    ["2412", "中華電", "tw", tw_stock_fee],
    ["2454", "聯發科", "tw", tw_stock_fee],
    ["2881", "富邦金", "tw", tw_stock_fee],
    ["2882", "國泰金", "tw", tw_stock_fee],
    ["2891", "中信金", "tw", tw_stock_fee],
    ["6505", "台塑化", "tw", tw_stock_fee],
    ["3231", "緯創", "tw"],
    ["2207", "和泰車", "tw"],
    ["3661", "世芯", "tw"],
    ["2603", "長榮", "tw"],
    ["2408", "南亞科", "tw"],
    
    # ["6214", "精誠", "tw"],
    # ["3045", "台灣大", "tw"],
    # ["2379", "瑞昱", "tw"],
    # ["2357", "華碩", "tw"],
    # ["2345", "智邦", "tw"],
    
    # # old us
    # ["AAPL", "Apple Inc.", "us"],
    # ["MSFT", "Microsoft", "us"],    # 20
    # ["NVDA", "Nvidia", "us"],
    # ["AMZN", "Amazon inc.", "us"],
    # ["JPM", "JPMorgan Chase", "us"],
    # ["BA", "Boeing", "us"],
    # ["UNH", "UnitedHealth Group", "us"],
    # ["CSCO", "Cisco", "us"],
    # ["CVX", "Chevron", "us"],
    # ["PG", "Procter & Gamble", "us"],
    # ["DIS", "Disney", "us"],
    
    # ["META", "Meta Platforms", "us"],
    # ["GOOGL", "Google", "us"],
    # ["TSLA", "Tesla", "us"],
    # ["AVGO", "Broadcom", "us"],
    # ["BRK", "Berkshire Hathaway", "us"],
    # ["MRNA", "Moderna", "us"],
    # ["PYPL", "PayPal", "us"],
    # ["BAC", "Bank of America", "us"],
    # ["HD", "Home Depot", "us"],
    # ["WMT", "Walmart", "us"],
    # ["INTC", "Intel", "us"],
    # ["ADBE", "Adobe", "us"],
    
    # # DJIA 
    # ["AAPL", "Apple Inc.", "us"],
    # ["AMGN", "Amgen", "us"],
    # ["AMZN", "Amazon inc.", "us"],
    # ["AXP", "American Express", "us"],
    # ["BA", "Boeing", "us"],
    # ["CSCO", "Cisco", "us"],
    # ["CVX", "Chevron", "us"],
    # ["KO", "Coca-Cola", "us"],
    # ["CAT", "Caterpillar Inc.", "us"],
    # ["CRM", "Salesforce", "us"],    # 10
    # ["DIS", "Disney", "us"],
    # ["GS", "Goldman Sachs", "us"],
    # ["HD", "Home Depot", "us"],
    # ["HON", "Honeywell", "us"],
    # ["IBM", "IBM", "us"],
    # ["JNJ", "Johnson & Johnson", "us"],
    # ["JPM", "JPMorgan Chase", "us"],
    # ["MCD", "McDonald's", "us"],
    # ["MRK", "Merck", "us"],
    # ["MSFT", "Microsoft", "us"],    # 20
    # ["MMM", "3M", "us"],
    # ["NKE", "Nike", "us"],
    # ["NVDA", "Nvidia", "us"],
    # ["PG", "Procter & Gamble", "us"],
    # ["SHW", "Sherwin-Williams", "us"],
    # ["TRV", "Travelers", "us"],
    # ["UNH", "UnitedHealth Group", "us"],
    # ["VZ", "Verizon", "us"],
    # ["V", "Visa", "us"],
    # ["WMT", "Walmart", "us"],   # 30
    
    # Removed from DJIA in past 3 years
    # ["INTC", "Intel", "us"],
    # ["DOW", "Dow Inc.", "us"],
    # ["WBA", "Walgreens Boots Alliance", "us"],
    
    # Not in DJIA
    # ["ADBE", "Adobe", "us"],
    # ["AVGO", "Broadcom", "us"],
    # ["BRK", "Berkshire Hathaway", "us"],
    # ["GOOGL", "Google", "us"],
    # ["META", "Meta Platforms", "us"],
    # ["MRNA", "Moderna", "us"],
    # ["NVDA", "Nvidia", "us"],
    # ["PYPL", "PayPal", "us"],
    # ["TSLA", "Tesla", "us"],
    # ["BAC", "Bank of America", "us"],
]

# 指數
index_twii = [
    ["2308", "台達電", "tw"],
    ["2317", "鴻海", "tw"],
    ["2330", "台積電", "tw"],
    ["2382", "廣達", "tw"],
    ["2412", "中華電", "tw"],
    ["2454", "聯發科", "tw"],
    ["2881", "富邦金", "tw"],
    ["2882", "國泰金", "tw"],
    ["2891", "中信金", "tw"],
    ["6505", "台塑化", "tw"],
]

index_spx = [
    ["AAPL", "Apple Inc.", "us"],
    ["MSFT", "Microsoft", "us"],
    ["NVDA", "Nvidia", "us"],
    ["AMZN", "Amazon inc.", "us"],
    ["META", "Meta Platforms", "us"],
    ["GOOGL", "Google", "us"],
    ["TSLA", "Tesla", "us"],
    ["AVGO", "Broadcom", "us"],
    ["BRK", "Berkshire Hathaway", "us"],
    ["JPM", "JPMorgan Chase", "us"],
]

index_djia = [
    ["GS", "Goldman Sachs", "us"],
    ["UNH", "UnitedHealth Group", "us"],
    ["MSFT", "Microsoft", "us"],
    ["HD", "Home Depot", "us"],
    ["CAT", "Caterpillar", "us"],
    ["V", "Visa", "us"],
    ["CRM", "Salesforce", "us"],
    ["AXP", "American Express", "us"],
    ["MCD", "McDonald's", "us"],
]


market_index = [
    ["twii", "台灣加權指數", "tw", index_twii, tw_index_fee],
    # ["spx", "S&P 500", "us", index_spx],
    # ["djia", "道瓊指數", "us", index_spx],
    
    # ["tx", "台灣指數期貨", "tw", index_twii, tw_index_fee],
]

data_range_tv = [
    # ["20220101", "20220110", 15.5], # test
    ["20220101", "20241231", 1], # tv1
    ["20220101", "20241231", 2], # tv2
    ["20220101", "20241231", 3], # tv3
    ["20220101", "20241231", 4], # tv4
    ["20220101", "20241231", 5], # tv5
    ["20220101", "20241231", 6], # tv6
    ["20220101", "20241231", 7], # tv7
    ["20220101", "20241231", 8], # tv8
    ["20220101", "20241231", 9], # tv9
    ["20220101", "20241231", 10], # tv10
    ["20220101", "20241231", 11], # tv11
    ["20220101", "20241231", 12], # tv12
    ["20220101", "20241231", 13], # tv13
    ["20220101", "20241231", 14], # tv14
    ["20220101", "20241231", 15], # tv15
    ["20220101", "20241231", 16], # tv16
    ["20220101", "20241231", 17], # tv17
    ["20220101", "20241231", 18], # tv18
    ["20220101", "20241231", 19], # tv19
    ["20220101", "20241231", 20], # tv20    
    ["20220101", "20241231", 21], # tv21
    ["20220101", "20241231", 22], # tv22
    ["20220101", "20241231", 23], # tv23
    ["20220101", "20241231", 24], # tv24
    ["20220101", "20241231", 25], # tv25
    ["20220101", "20241231", 26], # tv26
    ["20220101", "20241231", 27], # tv27
    ["20220101", "20241231", 28], # tv28
    ["20220101", "20241231", 29], # tv29
    ["20220101", "20241231", 30], # tv30
]

In [7]:
def get_balance_list(list_rtn, start_price):
    balance = start_price
    list_balance = [start_price]
    for rtn in list_rtn[1:]:
        balance = balance * (1 + float(rtn))
        list_balance.append(balance)
    return list_balance

In [8]:
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from math import ceil, sqrt

def display_all_plots(all_plots):
    # 計算需要的子圖行數與列數（接近正方形排列）
    num_plots = len(all_plots)
    cols = ceil(sqrt(num_plots))  # 列數
    rows = ceil(num_plots / cols)  # 行數

    # 創建一個大的畫布
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 5, rows * 4))
    # fig.suptitle("Trading Results for All Stocks", fontsize=16, y=0.95)

    # 確保 axes 是一個 2D 陣列
    if rows == 1 and cols == 1:
        axes = [[axes]]
    elif rows == 1 or cols == 1:
        axes = [axes] if rows == 1 else [[ax] for ax in axes]
    else:
        axes = axes.reshape(rows, cols)

    # 在每個子圖中顯示單獨的圖表
    for idx, single_fig in enumerate(all_plots):
        row, col = divmod(idx, cols)
        ax = axes[row][col]
        
        # 從單個圖表中提取並繪製數據
        for line in single_fig.axes[0].get_lines():
            ax.plot(line.get_xdata(), line.get_ydata(), label=line.get_label())
        
        # 設定標題、標籤與圖例
        ax.set_title(single_fig.axes[0].get_title())
        ax.set_xlabel(single_fig.axes[0].get_xlabel())
        ax.set_ylabel(single_fig.axes[0].get_ylabel())
        ax.legend()
        
        ax.xaxis.set_major_locator(MaxNLocator(nbins=5))  # 設置最多顯示 5 個標籤


    # 移除多餘的空白子圖
    for idx in range(num_plots, rows * cols):
        row, col = divmod(idx, cols)
        fig.delaxes(axes[row][col])

    # 調整整體佈局
    plt.tight_layout()
    plt.subplots_adjust(top=0.92)  # 調整總標題的位置
    plt.show()

In [9]:
def cacl_avg(df_stocks_results, wincount=None, ttl_count=None):
    '''
        only return average row
    '''
    
    average_row = pd.DataFrame()
    average_row['tp'] = [df_stocks_results['tp'].sum()]
    average_row['fp'] = [df_stocks_results['fp'].sum()]
    average_row['tn'] = [df_stocks_results['tn'].sum()]
    average_row['fn'] = [df_stocks_results['fn'].sum()]
    average_row['accuracy'] = (average_row['tp'] + average_row['tn']) / (average_row['tp'] + average_row['tn'] + average_row['fp'] + average_row['fn'])
    average_row['precision'] = average_row['tp'] / (average_row['tp'] + average_row['fp'])
    # EV 算法 每個ev成上avail_count 總和後再除上 avail_count 的平均
    average_row['avail_count'] = [df_stocks_results['avail_count'].sum()]
    average_row['pci_avl_count'] = [df_stocks_results['tp'].sum() + df_stocks_results['fp'].sum()]
    average_row['ev'] = (df_stocks_results['ev'].astype(float) * df_stocks_results['avail_count']).sum() / df_stocks_results['avail_count'].sum()
    average_row['precision_ev'] = (df_stocks_results['precision_ev'].astype(float) * (df_stocks_results['tp'] + df_stocks_results['fp'])).sum() / (df_stocks_results['tp'].sum() + df_stocks_results['fp'].sum())
    if ttl_count is None:
        average_row['win B&H'] = None
    else:
        average_row['win B&H'] = round(wincount / ttl_count, 2)
        
    if 'B&H' in df_stocks_results.columns:
        average_row['B&H'] = df_stocks_results['B&H'].mean()
    if 'RTN' in df_stocks_results.columns:
        average_row['RTN'] = df_stocks_results['RTN'].mean()
    
    return average_row

# TV-1 Stock - Usable DayTrade

In [ ]:
from TV_usable_dt_stock import TV_UsableFactorDT
import pandas as pd

avgs = pd.DataFrame()
selected_columns = ['accuracy', 'precision', 'ev', 'precision_ev', 'avail_count', 'tp', 'fp', 'tn', 'fn']
# 修改 runAll(i) 函數
def runAll(i):
    stock_results = []
    index = []
    wincount = 0
    ttl_count = 0
    stocks_avg = pd.DataFrame()

    for stock in data:
        list_stock = []
        stock_avg_list = []  # 存放該支股票所有 TV 的結果

        for date_range in data_range_tv:
            env = {
                "stock_id" : stock[0],
                "stock_name" : stock[1],
                "country" : stock[2],
                "start_date" : date_range[0],
                "end_date" : date_range[1],
                "tv" : date_range[2],
                "run_count" : str(i)
            }
            print(env['stock_id'], env['stock_name'], env['country'], f"tv{date_range[2]}")

            eval_module = TV_UsableFactorDT(env)
            eval_module.run()
            train_datarange, test_datarange = eval_module.split_exp(date_range[2])
            
            mode = 1
            eval_module.training(mode, train_datarange, test_datarange)

            # 繪圖
            result = eval_module.get_result(1)   # Test 結果
            result_train = result["train"]  # Training 結果
            result_test = result["test"]  # Test 結果
            index.append(f"{stock[0]} - {date_range[2]}")
            stock_results.append(result_test)
            list_stock.append(result_test)
            
            # Training 報酬計算
            train_date, train_bnh_balance, train_stag_rtn = eval_module.get_return_list('train')
            train_stag_balance = get_balance_list(train_stag_rtn, train_bnh_balance[0])

            # Test 報酬計算
            list_date, list_bnh_balance, list_stag_rtn = eval_module.get_return_list('test')
            list_stag_balance = get_balance_list(list_stag_rtn, list_bnh_balance[0])
            
            ttl_count += 1
            if list_stag_balance[-1] > list_bnh_balance[-1]:
                print(f"win B&H")
                wincount += 1
            else:
                print(f"loss B&H")
            
            st = sorted(train_datarange.keys())[0]
            et = sorted(train_datarange.keys())[-1]
            train_N_days = (datetime.strptime(et, '%Y%m%d') - datetime.strptime(st, '%Y%m%d')).days
            
            st = sorted(test_datarange.keys())[0]
            et = sorted(test_datarange.keys())[-1]
            test_N_days = (datetime.strptime(et, '%Y%m%d') - datetime.strptime(st, '%Y%m%d')).days

            # 計算該 TV 的結果 (Test)
            stock_avg = cacl_avg(pd.DataFrame(list_stock).loc[:, selected_columns])
            stock_avg['stock_id'] = stock[0]  # 加入個股代碼
            stock_avg['tv'] = date_range[2]  # 加入 TV
            
            # 計算該 TV 的結果 (Training)
            stock_avg['Train_RTN'] = (train_stag_balance[-1] / train_bnh_balance[0] - 1) * 100
            stock_avg['Train_B&H'] = (train_bnh_balance[-1] / train_bnh_balance[0] - 1) * 100
            stock_avg['Ann_Train_RTN'] = ((1 + stock_avg['Train_RTN'] / 100) ** (252 / train_N_days) - 1) * 100  # 年化 Training 報酬率
            stock_avg['Ann_Train_B&H'] = ((1 + stock_avg['Train_B&H'] / 100) ** (252 / train_N_days) - 1) * 100  # 年化 Training B&H

            # 計算該 TV 的結果 (Test)
            stock_avg['RTN'] = (list_stag_balance[-1] / list_bnh_balance[0] - 1) * 100
            stock_avg['B&H'] = (list_bnh_balance[-1] / list_bnh_balance[0] - 1) * 100
            stock_avg['Ann_RTN'] = ((1 + stock_avg['RTN'] / 100) ** (252 / test_N_days) - 1) * 100  # 年化報酬率
            stock_avg['Ann_B&H'] = ((1 + stock_avg['B&H'] / 100) ** (252 / test_N_days) - 1) * 100  # 年化 B&H
            stock_avg['win B&H'] = ("yes" if list_stag_balance[-1] > list_bnh_balance[-1] else "no")

            stock_avg_list.append(stock_avg)  # 收集該股票的 TV 結果

        if stock_avg_list:
            stock_avg_df = pd.concat(stock_avg_list)
            display(stock_avg_df.loc[:, ['stock_id', 'tv', 'accuracy', 'precision', 'ev', 'precision_ev', 'Train_RTN', 'Ann_Train_RTN', 'Train_B&H', 'Ann_Train_B&H', 'RTN', 'Ann_RTN', 'B&H', 'Ann_B&H', 'win B&H', 'avail_count', 'tp', 'fp', 'tn', 'fn']])
            stocks_avg = pd.concat([stocks_avg, stock_avg_df])

    return stocks_avg

# 迭代執行
for i in range(1):
    print(i+1)
    avgs = pd.concat([avgs, runAll(i+1)])

# 計算 **所有 TV 的 RTN 與 B&H 總平均**
tv_avg_df = avgs.groupby("tv")[["RTN", "B&H", "Ann_RTN", "Ann_B&H", "Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H"]].mean().reset_index()
tv_avg_df["Train_RTN"] = tv_avg_df["Train_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Train_B&H"] = tv_avg_df["Train_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Train_RTN"] = tv_avg_df["Ann_Train_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Train_B&H"] = tv_avg_df["Ann_Train_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Test_RTN"] = tv_avg_df["RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Test_B&H"] = tv_avg_df["B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Test_RTN"] = tv_avg_df["Ann_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Test_B&H"] = tv_avg_df["Ann_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Win B&H"] = tv_avg_df["RTN"] > tv_avg_df["B&H"]
tv_avg_df["Diff"] = tv_avg_df["RTN"] - tv_avg_df["B&H"]
tv_avg_df["Diff"] = tv_avg_df["Diff"].apply(lambda x: f"{x:.2f}%")

display(tv_avg_df.loc[:, ["tv", "Ann_Train_RTN", "Ann_Train_B&H", "Ann_Test_RTN",  "Ann_Test_B&H", "Win B&H", "Diff"]])

# TV-2 Usable Exp DayTrade

In [10]:
from TV_usableexp_dt_stock import TV_UsableExpFactorDT
import pandas as pd

avgs = pd.DataFrame()
selected_columns = ['accuracy', 'precision', 'ev', 'precision_ev', 'avail_count', 'tp', 'fp', 'tn', 'fn']
# 修改 runAll(i) 函數
def runAll(i):
    stock_results = []
    index = []
    wincount = 0
    ttl_count = 0
    stocks_avg = pd.DataFrame()

    for stock in data:
        list_stock = []
        stock_avg_list = []  # 存放該支股票所有 TV 的結果

        for date_range in data_range_tv:
            env = {
                "stock_id" : stock[0],
                "stock_name" : stock[1],
                "country" : stock[2],
                "start_date" : date_range[0],
                "end_date" : date_range[1],
                "tv" : date_range[2],
                "run_count" : str(i)
            }
            print(env['stock_id'], env['stock_name'], env['country'], f"tv{date_range[2]}")

            eval_module = TV_UsableExpFactorDT(env)
            eval_module.run()
            train_datarange, test_datarange = eval_module.split_exp(date_range[2])
            
            mode = 1
            eval_module.training(mode, train_datarange, test_datarange)

            # 繪圖
            result = eval_module.get_result(1)   # Test 結果
            result_train = result["train"]  # Training 結果
            result_test = result["test"]  # Test 結果
            index.append(f"{stock[0]} - {date_range[2]}")
            stock_results.append(result_test)
            list_stock.append(result_test)
            
            # Training 報酬計算
            train_date, train_bnh_balance, train_stag_rtn = eval_module.get_return_list('train')
            train_stag_balance = get_balance_list(train_stag_rtn, train_bnh_balance[0])

            # Test 報酬計算
            list_date, list_bnh_balance, list_stag_rtn = eval_module.get_return_list('test')
            list_stag_balance = get_balance_list(list_stag_rtn, list_bnh_balance[0])
            
            ttl_count += 1
            if list_stag_balance[-1] > list_bnh_balance[-1]:
                print(f"win B&H")
                wincount += 1
            else:
                print(f"loss B&H")
            
            st = sorted(train_datarange.keys())[0]
            et = sorted(train_datarange.keys())[-1]
            train_N_days = (datetime.strptime(et, '%Y%m%d') - datetime.strptime(st, '%Y%m%d')).days
            
            st = sorted(test_datarange.keys())[0]
            et = sorted(test_datarange.keys())[-1]
            test_N_days = (datetime.strptime(et, '%Y%m%d') - datetime.strptime(st, '%Y%m%d')).days

            # 計算該 TV 的結果 (Test)
            stock_avg = cacl_avg(pd.DataFrame(list_stock).loc[:, selected_columns])
            stock_avg['stock_id'] = stock[0]  # 加入個股代碼
            stock_avg['tv'] = date_range[2]  # 加入 TV
            
            # 計算該 TV 的結果 (Training)
            stock_avg['Train_RTN'] = (train_stag_balance[-1] / train_bnh_balance[0] - 1) * 100
            stock_avg['Train_B&H'] = (train_bnh_balance[-1] / train_bnh_balance[0] - 1) * 100
            stock_avg['Ann_Train_RTN'] = ((1 + stock_avg['Train_RTN'] / 100) ** (252 / train_N_days) - 1) * 100  # 年化 Training 報酬率
            stock_avg['Ann_Train_B&H'] = ((1 + stock_avg['Train_B&H'] / 100) ** (252 / train_N_days) - 1) * 100  # 年化 Training B&H

            # 計算該 TV 的結果 (Test)
            stock_avg['RTN'] = (list_stag_balance[-1] / list_bnh_balance[0] - 1) * 100
            stock_avg['B&H'] = (list_bnh_balance[-1] / list_bnh_balance[0] - 1) * 100
            stock_avg['Ann_RTN'] = ((1 + stock_avg['RTN'] / 100) ** (252 / test_N_days) - 1) * 100  # 年化報酬率
            stock_avg['Ann_B&H'] = ((1 + stock_avg['B&H'] / 100) ** (252 / test_N_days) - 1) * 100  # 年化 B&H
            stock_avg['win B&H'] = ("yes" if list_stag_balance[-1] > list_bnh_balance[-1] else "no")

            stock_avg_list.append(stock_avg)  # 收集該股票的 TV 結果

        if stock_avg_list:
            stock_avg_df = pd.concat(stock_avg_list)
            display(stock_avg_df.loc[:, ['stock_id', 'tv', 'accuracy', 'precision', 'ev', 'precision_ev', 'Train_RTN', 'Ann_Train_RTN', 'Train_B&H', 'Ann_Train_B&H', 'RTN', 'Ann_RTN', 'B&H', 'Ann_B&H', 'win B&H', 'avail_count', 'tp', 'fp', 'tn', 'fn']])
            stocks_avg = pd.concat([stocks_avg, stock_avg_df])

    return stocks_avg

# 迭代執行
for i in range(1):
    print(i+1)
    avgs = pd.concat([avgs, runAll(i+1)])

# 計算 **所有 TV 的 RTN 與 B&H 總平均**
tv_avg_df = avgs.groupby("tv")[["RTN", "B&H", "Ann_RTN", "Ann_B&H", "Train_RTN", "Train_B&H", "Ann_Train_RTN", "Ann_Train_B&H"]].mean().reset_index()
tv_avg_df["Train_RTN"] = tv_avg_df["Train_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Train_B&H"] = tv_avg_df["Train_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Train_RTN"] = tv_avg_df["Ann_Train_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Train_B&H"] = tv_avg_df["Ann_Train_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Test_RTN"] = tv_avg_df["RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Test_B&H"] = tv_avg_df["B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Test_RTN"] = tv_avg_df["Ann_RTN"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Ann_Test_B&H"] = tv_avg_df["Ann_B&H"].apply(lambda x: f"{x:.2f}%")
tv_avg_df["Win B&H"] = tv_avg_df["RTN"] > tv_avg_df["B&H"]
tv_avg_df["Diff"] = tv_avg_df["RTN"] - tv_avg_df["B&H"]
tv_avg_df["Diff"] = tv_avg_df["Diff"].apply(lambda x: f"{x:.2f}%")

display(tv_avg_df.loc[:, ["tv", "Ann_Train_RTN", "Ann_Train_B&H", "Ann_Test_RTN",  "Ann_Test_B&H", "Win B&H", "Diff"]])

1
2330 台積電 tw tv1
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2330,1,0.502907,0.480843,0.001545,0.000960,1.567350,18.577335,0.792393,9.032580,182.912803,28.108218,69.291339,13.359370,yes,688,251,271,95,71
0,2330,2,0.504438,0.483971,0.001507,0.001014,-1.695412,-6.228994,-8.874802,-29.499449,156.753710,26.147318,87.937063,16.815014,yes,1352,468,499,214,171
0,2330,3,0.504767,0.483562,0.001522,0.001001,0.088781,0.219485,-10.935024,-24.881553,160.222081,27.625654,91.622103,18.043148,yes,1993,706,754,300,233
0,2330,4,0.508046,0.486430,0.001612,0.001068,-3.736764,-6.765446,-16.006339,-27.446592,215.701980,35.526106,103.598485,20.683715,yes,2610,932,984,394,300
0,2330,5,0.511083,0.489070,0.001671,0.001123,-3.781274,-5.490956,-22.900158,-31.684347,202.389561,35.494073,115.646941,23.485456,yes,3203,1141,1192,496,374
0,2330,6,0.511801,0.490040,0.001723,0.001166,5.451402,6.675267,-19.334390,-23.015499,203.957969,37.337930,113.293651,24.132998,yes,3771,1353,1408,577,433
0,2330,7,0.511358,0.489943,0.001716,0.001153,12.602995,13.156656,-23.137876,-23.969167,140.019932,29.717336,121.193416,26.606467,yes,4314,1559,1623,647,485
0,2330,8,0.510656,0.489505,0.001731,0.001170,21.138942,19.060360,-30.586371,-28.261087,159.120916,34.378056,167.745953,35.750549,no,4833,1749,1824,719,541
0,2330,9,0.509855,0.488878,0.001735,0.001179,31.518980,24.506134,-29.477021,-24.375151,126.561287,30.375313,123.958333,29.887617,yes,5327,1934,2022,782,589
0,2330,10,0.510352,0.489199,0.001754,0.001193,29.799496,20.658123,-26.069731,-19.545184,149.388791,36.391841,134.972678,33.661367,yes,5796,2106,2199,852,639
0,2330,11,0.511289,0.490108,0.001773,0.001204,22.317614,14.333134,-20.285261,-13.993301,142.744955,37.548634,97.974217,27.828233,yes,6245,2279,2371,914,681
0,2330,12,0.511687,0.490468,0.001790,0.001219,27.219292,15.659975,-19.017433,-11.968218,125.553335,35.726887,105.938697,31.167751,yes,6674,2444,2539,971,720
0,2330,13,0.512147,0.490844,0.001800,0.001226,40.773049,21.004889,-15.530903,-8.980922,118.495704,36.366612,102.830189,32.399301,yes,7080,2600,2697,1026,757
0,2330,14,0.512126,0.491062,0.001806,0.001236,47.654045,22.141484,-19.175911,-10.350802,106.516690,35.537997,113.717694,37.499936,no,7463,2747,2847,1075,794
0,2330,15,0.513427,0.492494,0.001830,0.001260,42.846053,18.591796,-6.497623,-3.161507,124.553555,43.448136,81.895093,30.582433,yes,7820,2887,2975,1128,830
0,2330,16,0.514580,0.493793,0.001853,0.001284,37.889560,15.495663,-7.923930,-3.634082,121.836926,46.059328,85.664940,34.206473,yes,8162,3023,3099,1177,863
0,2330,17,0.515559,0.495132,0.001876,0.001311,41.745305,15.836778,-10.618067,-4.620199,118.189295,48.883376,96.886447,41.281665,yes,8484,3153,3215,1221,895
0,2330,18,0.516731,0.496666,0.001899,0.001338,45.910888,16.231546,-17.115689,-7.200959,110.829082,51.012964,101.688555,47.358938,yes,8786,3277,3321,1263,925
0,2330,19,0.517428,0.497578,0.001918,0.001358,55.031204,17.987163,-13.312203,-5.246574,97.677974,49.933864,95.810565,49.090431,yes,9066,3390,3423,1301,952
0,2330,20,0.517811,0.498072,0.001940,0.001381,57.337502,17.613453,-9.667195,-3.573879,96.016112,55.175305,87.282230,50.625783,yes,9320,3488,3515,1338,979
0,2330,21,0.517906,0.498188,0.001961,0.001400,59.690016,17.305397,-7.448494,-2.604986,89.417778,58.188119,83.447099,54.592092,yes,9550,3575,3601,1371,1003
0,2330,22,0.518484,0.498772,0.001992,0.001432,58.039791,16.068576,8.240887,2.611771,103.124467,75.966763,58.554572,44.422958,yes,9765,3656,3674,1407,1028
0,2330,23,0.518783,0.499196,0.002014,0.001454,73.274507,18.676524,24.405705,7.039074,79.296732,68.811871,37.820513,33.332577,yes,9956,3727,3739,1438,1052
0,2330,24,0.519261,0.499868,0.002033,0.001476,77.653728,18.718241,23.930269,6.615596,67.074199,69.178902,35.220126,36.218930,yes,10124,3792,3794,1465,1073
0,2330,25,0.519673,0.500651,0.002051,0.001500,92.522342,20.658447,30.110935,7.838182,59.549221,74.710787,27.068558,33.123288,yes,10268,3848,3838,1488,1094
0,2330,26,0.519734,0.500965,0.002064,0.001513,117.304334,23.860696,59.270998,13.692377,40.229753,62.273807,3.864734,5.579438,yes,10388,3892,3877,1507,1112
0,2330,27,0.519409,0.500765,0.002061,0.001509,161.931027,29.135748,48.019017,10.975362,17.752897,33.919205,14.361702,27.104548,yes,10485,3926,3914,1520,1125
0,2330,28,0.519466,0.501014,0.002062,0.001510,164.109995,28.238393,50.079239,10.957147,17.781806,47.563310,13.516367,35.174184,yes,10557,3953,3937,1531,1136
0,2330,29,0.519280,0.501073,0.002058,0.001507,191.393473,30.175505,71.949287,14.299394,7.011133,27.627499,0.000000,0.000000,yes,10607,3970,3953,1538,1146
0,2330,30,0.518950,0.500881,0.002055,0.001503,198.292159,29.765619,63.232964,12.392065,2.753996,21.604819,6.435644,56.684866,no,10633,3979,3965,1539,1150

2308 台達電 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	 no news found in 20220821
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2308,1,0.494964,0.492147,0.000971,0.001021,-2.694279,-25.862513,-4.964539,-42.759419,82.494962,15.405394,58.856089,11.654481,yes,695,282,291,62,60
0,2308,2,0.500365,0.494903,0.001121,0.001167,-1.478825,-5.449571,-7.092199,-24.170523,125.264713,22.146331,67.184466,13.496067,yes,1371,534,545,152,140
0,2308,3,0.501239,0.497006,0.001066,0.001241,-1.315181,-3.217914,-11.524823,-26.104553,73.026998,15.009442,73.939394,15.163824,no,2017,747,756,264,250
0,2308,4,0.500566,0.497215,0.001124,0.001314,-19.049046,-32.207443,-19.680851,-33.177500,118.519536,22.961959,91.333333,18.717125,yes,2649,982,993,344,330
0,2308,5,0.499232,0.497304,0.001087,0.001320,-15.565613,-21.955499,-15.248227,-21.525307,65.833061,14.895197,82.029598,17.872239,no,3255,1199,1212,426,418
0,2308,6,0.501433,0.499473,0.001156,0.001372,-12.161093,-14.602540,-8.510638,-10.262720,131.422417,27.056803,66.537718,15.669176,yes,3839,1423,1426,502,488
0,2308,7,0.504316,0.502290,0.001247,0.001443,-20.695477,-21.451714,-9.574468,-9.949751,170.868722,34.463022,68.493151,16.770571,yes,4402,1645,1630,575,552
0,2308,8,0.506073,0.503943,0.001292,0.001473,-7.067206,-6.450423,-2.482270,-2.260791,132.749242,29.975614,62.759924,16.319537,yes,4940,1853,1824,647,616
0,2308,9,0.507244,0.505147,0.001327,0.001500,-6.912581,-5.569391,1.241135,0.991682,117.741374,28.707091,46.928328,13.291256,yes,5453,2061,2019,705,668
0,2308,10,0.507405,0.505066,0.001353,0.001520,2.326687,1.669812,2.836879,2.034538,118.327535,30.367377,52.120141,15.312061,yes,5942,2243,2198,772,729
0,2308,11,0.507253,0.504499,0.001374,0.001543,5.248975,3.460086,1.418440,0.940904,110.369125,30.649470,49.220104,15.475160,yes,6411,2411,2368,841,791
0,2308,12,0.506560,0.503925,0.001380,0.001564,15.609752,9.161275,1.595745,0.961313,78.693955,24.360395,48.704663,16.069477,yes,6860,2568,2528,907,857
0,2308,13,0.506176,0.503987,0.001379,0.001581,9.030107,4.938045,6.737589,3.702104,70.795027,23.668156,46.179966,16.261470,yes,7286,2718,2675,970,923
0,2308,14,0.506242,0.504314,0.001396,0.001613,-4.824605,-2.505964,7.801418,3.930766,85.381589,29.539029,42.786070,16.107414,yes,7690,2864,2815,1029,982
0,2308,15,0.506321,0.504797,0.001421,0.001650,8.699901,4.069626,25.177305,11.335748,94.934334,34.677588,16.351351,6.988038,yes,8068,2999,2942,1086,1041
0,2308,16,0.506470,0.505168,0.001435,0.001675,9.438888,4.127279,26.595745,11.153869,79.028700,31.903879,20.757363,9.382440,yes,8423,3128,3064,1138,1093
0,2308,17,0.506683,0.505597,0.001452,0.001701,12.091248,4.927602,26.595745,10.448518,82.395948,35.878094,24.602026,11.874062,yes,8753,3252,3180,1183,1138
0,2308,18,0.506734,0.506243,0.001468,0.001732,23.412800,8.735383,15.070922,5.747635,68.498489,33.420975,28.315946,14.772884,yes,9058,3365,3282,1225,1186
0,2308,19,0.507012,0.507314,0.001484,0.001770,26.957785,9.422094,5.851064,2.168299,69.114761,36.652417,41.611842,22.971498,yes,9341,3468,3368,1268,1237
0,2308,20,0.506564,0.507646,0.001496,0.001803,33.876574,11.008053,10.815603,3.744504,58.626739,35.149885,38.647343,23.778986,yes,9598,3552,3445,1310,1291
0,2308,21,0.506764,0.508536,0.001515,0.001845,29.037827,9.082394,4.078014,1.372333,65.591330,43.634167,45.685279,31.015920,yes,9831,3634,3512,1348,1337
0,2308,22,0.506669,0.509261,0.001535,0.001887,30.634871,9.090439,3.368794,1.084586,63.375060,47.913869,47.431507,36.284176,yes,10046,3712,3577,1378,1379
0,2308,23,0.506594,0.509836,0.001535,0.001901,62.208708,16.261840,26.950355,7.716322,35.047648,30.924340,22.127660,19.633988,yes,10237,3784,3638,1402,1413
0,2308,24,0.506968,0.511014,0.001551,0.001937,51.603379,13.228494,11.702128,3.359429,48.414044,49.850196,34.112150,35.075661,yes,10405,3851,3685,1424,1445
0,2308,25,0.507252,0.512118,0.001565,0.001976,55.090071,13.406622,15.248227,4.152545,41.629177,51.538730,27.744807,33.969862,yes,10549,3909,3724,1442,1474
0,2308,26,0.507264,0.512917,0.001576,0.002007,72.748825,16.267409,37.234043,9.118847,27.556763,41.692929,7.089552,10.304300,yes,10669,3951,3752,1461,1505
0,2308,27,0.507152,0.513273,0.001580,0.002021,81.616607,17.170116,37.411348,8.805510,22.178082,43.046551,7.894737,14.545805,yes,10766,3983,3777,1477,1529
0,2308,28,0.507566,0.514095,0.001593,0.002045,78.291220,15.961485,36.524823,8.299728,27.403951,77.851468,11.673152,30.014390,yes,10838,4012,3792,1489,1545
0,2308,29,0.507807,0.514745,0.001605,0.002067,90.209750,17.179575,41.843972,9.001587,21.766275,103.187632,6.427689,25.140149,yes,10888,4032,3801,1497,1558
0,2308,30,0.507880,0.515163,0.001610,0.002080,104.562207,18.605293,39.539007,8.267216,9.957183,98.066009,11.096774,113.329263,no,10914,4043,3805,1500,1566

2317 鴻海 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	 no news found in 20220605
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	 no news found in 20220717
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	 no news found in 20220814
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	 no news found in 20220828
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2317,1,0.432706,0.410550,0.001418,0.001091,7.861002,129.129009,-0.970874,-10.137885,149.873707,24.374450,78.640777,14.820138,yes,691,179,257,120,135
0,2317,2,0.430454,0.406818,0.001458,0.001078,4.726006,18.967686,0.485437,1.838094,160.692924,26.621342,79.512195,15.502680,yes,1366,358,522,230,256
0,2317,3,0.430129,0.404569,0.001471,0.001033,9.850047,26.124834,0.000000,0.000000,151.997206,26.584429,79.512195,16.093897,yes,2018,549,808,319,342
0,2317,4,0.429758,0.402079,0.001486,0.001001,4.458493,8.354124,3.883495,7.259556,148.361577,27.195407,70.370370,15.129627,yes,2648,735,1093,403,417
0,2317,5,0.428791,0.399384,0.001491,0.000985,2.470683,3.640546,6.796117,10.112613,135.641032,26.527966,65.765766,14.882397,yes,3251,907,1364,487,493
0,2317,6,0.428534,0.399626,0.001501,0.000994,10.263266,12.630225,5.825243,7.135837,135.713221,27.724708,68.807339,16.116884,yes,3834,1069,1606,574,585
0,2317,7,0.428214,0.398765,0.001495,0.000979,5.429730,5.660335,4.368932,4.553517,114.622671,25.476956,70.370370,17.155675,yes,4395,1227,1850,655,663
0,2317,8,0.429353,0.399884,0.001532,0.001004,9.852065,8.924399,4.368932,3.966910,156.411801,33.940463,76.923077,19.370945,yes,4933,1378,2068,740,747
0,2317,9,0.431142,0.400524,0.001571,0.001027,-0.307077,-0.245738,-1.456311,-1.166755,158.402893,36.056115,81.280788,21.280162,yes,5446,1528,2287,820,811
0,2317,10,0.433097,0.401980,0.001609,0.001057,8.796977,6.258607,-1.456311,-1.050695,153.499349,37.151223,84.000000,23.009351,yes,5934,1665,2477,905,887
0,2317,11,0.434083,0.403128,0.001629,0.001074,1.489399,0.987858,-4.757282,-3.188914,133.278151,35.595645,87.563710,25.369905,yes,6402,1804,2671,975,952
0,2317,12,0.434954,0.404068,0.001660,0.001106,13.552634,7.983298,-1.941748,-1.177979,139.490875,38.817857,80.392157,24.802938,yes,6849,1927,2842,1052,1028
0,2317,13,0.436684,0.405128,0.001708,0.001143,1.476966,0.820770,0.970874,0.540126,175.198726,49.442407,77.777778,25.650428,yes,7273,2054,3016,1122,1081
0,2317,14,0.437581,0.406145,0.001744,0.001175,8.323596,4.188841,3.398058,1.729828,150.879635,47.060593,72.769953,25.768158,yes,7674,2168,3170,1190,1146
0,2317,15,0.438882,0.407216,0.001781,0.001202,7.368870,3.458309,9.223301,4.308943,150.052617,50.497419,65.022422,25.033966,yes,8050,2280,3319,1253,1198
0,2317,16,0.439367,0.407325,0.001810,0.001223,-4.739921,-2.153861,5.339806,2.360041,131.085159,48.923528,70.370370,28.831283,yes,8403,2391,3479,1301,1232
0,2317,17,0.440728,0.408502,0.001864,0.001272,-5.813255,-2.492241,6.310680,2.612349,177.588124,68.340380,70.370370,31.231798,yes,8731,2489,3604,1359,1279
0,2317,18,0.442218,0.410159,0.001922,0.001329,3.718154,1.463971,0.970874,0.385386,185.200844,78.455817,76.076555,36.704379,yes,9034,2584,3716,1411,1323
0,2317,19,0.443490,0.411530,0.001973,0.001382,0.846800,0.318613,-5.825243,-2.238713,168.415760,79.828115,92.066806,47.389634,yes,9317,2677,3828,1455,1357
0,2317,20,0.445060,0.413154,0.002026,0.001435,-8.942955,-3.297857,-1.456311,-0.523750,164.217843,88.572290,82.178218,47.932991,yes,9574,2764,3926,1497,1387
0,2317,21,0.446563,0.414357,0.002078,0.001488,5.526721,1.851311,-2.427184,-0.834383,155.004143,95.830380,84.000000,54.926467,yes,9806,2840,4014,1539,1413
0,2317,22,0.448059,0.415466,0.002136,0.001542,9.573247,3.021307,-1.456311,-0.476495,163.826676,116.764588,78.640777,58.835126,yes,10021,2912,4097,1578,1434
0,2317,23,0.449080,0.415990,0.002166,0.001563,40.103755,11.075550,41.262136,11.360809,101.465798,87.416095,26.460481,23.433431,yes,10212,2971,4171,1615,1455
0,2317,24,0.449807,0.416472,0.002187,0.001574,51.472749,13.199355,50.485437,12.978546,75.435166,77.856899,16.088328,16.511492,yes,10380,3024,4237,1645,1474
0,2317,25,0.450779,0.417063,0.002214,0.001589,44.426082,11.113982,66.990291,15.835911,77.840633,98.891039,4.249292,5.095701,yes,10524,3070,4291,1674,1489
0,2317,26,0.450864,0.416745,0.002216,0.001579,97.379113,20.619586,108.252427,22.416184,26.476413,39.977784,-18.763797,-25.736082,yes,10644,3101,4340,1698,1505
0,2317,27,0.451168,0.416722,0.002221,0.001573,107.609802,21.406753,63.592233,13.962801,25.862079,50.846616,4.545455,8.268677,yes,10741,3130,4381,1716,1514
0,2317,28,0.451309,0.416512,0.002222,0.001569,124.671489,23.035539,70.873786,14.706390,15.776904,41.661600,1.657459,3.985444,yes,10813,3148,4410,1732,1523
0,2317,29,0.451625,0.416425,0.002224,0.001563,130.468401,22.860146,103.883495,19.202672,10.846673,44.877714,-14.617169,-43.384679,yes,10863,3159,4427,1747,1530
0,2317,30,0.451465,0.415954,0.002222,0.001553,163.733118,26.011482,104.368932,18.578566,1.137435,8.484058,-9.135802,-49.831845,yes,10889,3160,4437,1756,1536

2382 廣達 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	 no news found in 20220327
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	 no news found in 20220424
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	 no news found in 20220605
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	 no news found in 20220724
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2382,1,0.493488,0.485981,0.000969,0.000615,0.950847,10.925382,-0.853789,-8.966915,64.887258,12.649888,206.296692,30.554525,no,691,260,275,81,75
0,2382,2,0.487142,0.481905,0.000799,0.000496,5.816798,23.695721,-1.814301,-6.654825,29.525250,6.580255,211.956522,32.346458,no,1361,506,544,157,154
0,2382,3,0.487599,0.483439,0.000825,0.000505,1.784996,4.468032,-8.324440,-19.324044,51.727086,11.219795,236.854460,36.310659,no,2016,759,811,224,222
0,2382,4,0.485812,0.482460,0.000809,0.000494,-0.374292,-0.687397,-20.490928,-34.411931,37.407129,8.766094,280.132450,42.347914,no,2643,1004,1077,280,282
0,2382,5,0.484587,0.481439,0.000746,0.000433,7.874080,11.744816,-14.194237,-20.091334,13.003796,3.412862,255.198020,41.615099,no,3244,1245,1341,327,331
0,2382,6,0.484301,0.481397,0.000742,0.000427,8.761550,10.765579,-9.711846,-11.695001,30.935656,7.995894,266.071429,44.822638,no,3822,1475,1589,376,382
0,2382,7,0.482987,0.480808,0.000777,0.000446,3.517168,3.665137,-16.862327,-17.494343,49.870297,12.776175,262.373737,46.610304,no,4379,1691,1826,424,438
0,2382,8,0.484656,0.482461,0.000846,0.000497,1.410119,1.282040,-20.170758,-18.531044,82.893185,20.606759,293.150685,52.939027,no,4888,1898,2036,471,483
0,2382,9,0.486842,0.484019,0.000941,0.000563,-8.768020,-7.078186,-22.091782,-18.103260,119.325549,29.010047,296.408840,56.312040,no,5396,2105,2244,522,525
0,2382,10,0.486914,0.484103,0.000953,0.000575,-6.420946,-4.665822,-22.732124,-16.946247,49.425576,14.614261,308.831909,61.322319,no,5884,2284,2434,581,585
0,2382,11,0.487640,0.484308,0.001008,0.000608,-6.437303,-4.327750,-19.957311,-13.758194,92.991202,26.662153,276.146789,61.002705,no,6351,2469,2629,628,625
0,2382,12,0.488016,0.484344,0.001039,0.000623,-7.551549,-4.634215,-14.514408,-9.041819,63.979442,20.410973,259.649123,61.720580,no,6801,2645,2816,674,666
0,2382,13,0.487339,0.483394,0.001043,0.000615,2.779261,1.540097,-4.909285,-2.767486,40.198118,14.349611,219.243604,58.511617,no,7227,2809,3002,713,703
0,2382,14,0.487354,0.482568,0.001089,0.000625,5.108393,2.590026,-2.027748,-1.045906,85.476447,29.566818,212.977099,61.350009,no,7631,2962,3176,757,736
0,2382,15,0.487077,0.481671,0.001105,0.000613,19.510111,8.896326,49.413020,21.168235,47.457703,18.912819,95.238095,34.771151,no,8009,3101,3337,800,771
0,2382,16,0.486370,0.480369,0.001097,0.000572,40.760308,16.567723,111.312700,39.860854,16.181848,7.391871,36.018957,15.750467,no,8364,3230,3494,838,802
0,2382,17,0.485852,0.479083,0.001067,0.000505,91.728164,31.560395,180.149413,54.359059,3.743101,1.892248,17.622951,8.632436,no,8694,3344,3636,880,834
0,2382,18,0.484943,0.477550,0.001030,0.000440,112.139907,34.905532,155.602988,45.296025,-11.251052,-6.383294,12.770138,6.867122,no,8999,3446,3770,918,865
0,2382,19,0.484163,0.476133,0.001013,0.000402,76.446414,23.889239,114.514408,33.364568,8.861662,5.175903,43.500000,23.943370,no,9282,3541,3896,953,892
0,2382,20,0.483594,0.474987,0.001002,0.000374,68.345071,20.495121,116.648879,31.882007,12.815868,8.190684,40.686275,24.964341,no,9539,3627,4009,986,917
0,2382,21,0.483217,0.474102,0.000982,0.000339,66.193704,18.913145,146.531483,36.028220,2.043105,1.462655,26.710817,18.526363,no,9772,3707,4112,1015,938
0,2382,22,0.482728,0.473276,0.000964,0.000312,95.734261,24.440372,165.208111,37.376353,1.676425,1.334642,18.840580,14.757750,no,9987,3781,4208,1040,958
0,2382,23,0.482413,0.472540,0.000970,0.000307,61.775783,16.165096,174.813234,37.011912,25.209668,22.337995,12.549020,11.184208,yes,10178,3846,4293,1064,975
0,2382,24,0.482119,0.471926,0.000975,0.000305,65.162950,16.161968,174.813234,35.234366,19.296817,19.811320,9.751434,10.000794,yes,10346,3900,4364,1088,994
0,2382,25,0.481888,0.471369,0.000984,0.000307,49.195962,12.153883,192.422625,36.019262,22.517552,27.448982,1.592920,1.905377,yes,10490,3943,4422,1112,1013
0,2382,26,0.481904,0.471048,0.000992,0.000305,69.085018,15.582246,232.977588,39.327116,17.304653,25.674400,-10.172144,-14.238361,yes,10610,3978,4467,1135,1030
0,2382,27,0.481367,0.470450,0.000985,0.000297,87.732493,18.205150,166.808965,29.770028,-1.843202,-3.270301,7.490637,13.780193,no,10707,4004,4507,1150,1046
0,2382,28,0.480935,0.469922,0.000975,0.000289,107.551253,20.563273,171.611526,29.161498,-3.755559,-8.698488,12.992126,33.694808,no,10779,4023,4538,1161,1057
0,2382,29,0.480561,0.469397,0.000965,0.000279,102.053944,18.938022,229.775880,34.208493,-8.503892,-27.381138,-10.031348,-31.651597,yes,10829,4034,4560,1170,1065
0,2382,30,0.480147,0.468997,0.000960,0.000271,104.408510,18.584041,219.103522,31.868976,-2.966616,-19.493217,-3.367003,-21.854635,yes,10855,4039,4573,1173,1070

2412 中華電 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	 no news found in 20220417
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2412,1,0.374644,0.375000,0.000027,0.000223,2.168267,26.494383,1.731602,20.695350,-0.059781,-0.014242,4.219409,0.989238,no,702,207,345,56,94
0,2412,2,0.366207,0.367837,-0.000026,0.000174,3.385499,13.340589,6.060606,24.771083,-6.386098,-1.612450,0.406504,0.099983,no,1379,398,684,107,190
0,2412,3,0.366502,0.366483,-0.000046,0.000124,9.217593,24.338393,12.121212,32.665517,-6.835110,-1.789604,-5.000000,-1.299770,no,2030,597,1032,147,254
0,2412,4,0.367193,0.366713,-0.000022,0.000128,8.376222,15.946643,7.792208,14.799957,2.172663,0.569979,0.000000,0.000000,yes,2658,791,1366,185,316
0,2412,5,0.364532,0.363366,-0.000053,0.000087,12.236147,18.426886,11.688312,17.580933,-11.013513,-3.152379,-3.891051,-1.083554,no,3248,976,1710,208,354
0,2412,6,0.364111,0.363406,-0.000048,0.000090,4.170883,5.100370,5.194805,6.359347,-1.815188,-0.521433,1.229508,0.349359,no,3834,1148,2011,248,427
0,2412,7,0.364816,0.364191,-0.000031,0.000101,0.855957,0.891484,4.761905,4.963484,2.733053,0.804499,1.229508,0.363805,yes,4394,1314,2294,289,497
0,2412,8,0.365131,0.365198,-0.000012,0.000120,0.473826,0.430970,-4.329004,-3.946117,7.357338,2.227672,13.302752,3.952095,no,4927,1467,2550,332,578
0,2412,9,0.364606,0.365655,-0.000006,0.000133,-0.689987,-0.552371,-5.194805,-4.177895,2.410913,0.775633,13.302752,4.133748,no,5436,1614,2800,368,654
0,2412,10,0.363345,0.365348,-0.000018,0.000132,4.239726,3.034804,-3.463203,-2.505778,-8.177119,-2.855707,10.762332,3.532466,no,5920,1746,3033,405,736
0,2412,11,0.363651,0.366189,-0.000012,0.000140,4.881167,3.219543,-1.298701,-0.865406,3.010691,1.072036,7.860262,2.757435,no,6388,1891,3273,432,792
0,2412,12,0.363716,0.366612,-0.000008,0.000147,1.419484,0.855425,0.000000,0.000000,2.127688,0.793824,7.391304,2.714256,no,6835,2027,3502,459,847
0,2412,13,0.363774,0.366933,-0.000005,0.000151,6.112600,3.363129,3.463203,1.916260,0.608668,0.241108,2.489627,0.980688,no,7260,2155,3718,486,901
0,2412,14,0.363352,0.366290,-0.000008,0.000145,10.320914,5.170428,9.523810,4.779735,-2.321059,-0.979863,-1.984127,-0.836790,no,7662,2271,3929,513,949
0,2412,15,0.362732,0.365662,-0.000009,0.000138,12.630145,5.852260,8.658009,4.050446,-1.928159,-0.864633,-1.593625,-0.713949,no,8039,2379,4127,537,996
0,2412,16,0.362326,0.365351,-0.000007,0.000138,15.635262,6.730758,-0.432900,-0.194344,0.859469,0.407736,6.926407,3.235504,no,8393,2480,4308,561,1044
0,2412,17,0.361687,0.364949,-0.000013,0.000134,18.333129,7.351312,1.731602,0.726083,-5.028883,-2.597755,6.008584,3.021295,no,8723,2578,4486,577,1082
0,2412,18,0.361099,0.364878,-0.000017,0.000133,14.460508,5.523958,0.432900,0.172116,-4.148813,-2.314479,6.008584,3.277152,no,9028,2672,4651,588,1117
0,2412,19,0.361293,0.365673,-0.000015,0.000136,7.310924,2.697598,2.164502,0.811109,1.103990,0.654684,5.106383,3.004222,no,9311,2759,4786,605,1161
0,2412,20,0.360995,0.365734,-0.000016,0.000138,8.175414,2.852884,4.329004,1.528548,-1.619728,-1.060434,2.916667,1.894629,no,9568,2837,4920,617,1194
0,2412,21,0.361086,0.366029,-0.000015,0.000142,12.422887,4.073829,3.896104,1.311879,0.721717,0.517630,2.489627,1.781214,no,9801,2907,5035,632,1227
0,2412,22,0.361022,0.366145,-0.000014,0.000144,8.545157,2.705594,5.627706,1.798558,0.844373,0.672787,1.229508,0.979279,no,10016,2972,5145,644,1255
0,2412,23,0.360929,0.365986,-0.000014,0.000142,8.387635,2.540643,7.359307,2.236608,-1.932006,-1.734357,-0.803213,-0.720618,no,10207,3030,5249,654,1274
0,2412,24,0.360675,0.365668,-0.000017,0.000140,12.367387,3.542843,6.926407,2.019723,-3.456291,-3.539082,-0.803213,-0.822723,no,10375,3076,5336,666,1297
0,2412,25,0.360300,0.365096,-0.000018,0.000136,12.232004,3.363673,10.822511,2.989837,-1.496730,-1.784953,-2.755906,-3.282534,yes,10519,3115,5417,675,1312
0,2412,26,0.360090,0.364647,-0.000017,0.000133,14.704994,3.855024,3.896104,1.059374,-0.381390,-0.545631,3.781513,5.458333,no,10639,3148,5485,683,1323
0,2412,27,0.359724,0.364001,-0.000020,0.000127,12.756187,3.239406,5.627706,1.464480,-2.813017,-4.971741,1.646091,2.960989,no,10736,3173,5544,689,1330
0,2412,28,0.359548,0.363667,-0.000022,0.000122,13.868342,3.381938,7.792208,1.940215,-2.008424,-4.708869,-1.200000,-2.829290,no,10808,3193,5587,693,1335
0,2412,29,0.359458,0.363595,-0.000021,0.000121,14.785920,3.458709,6.060606,1.461438,-0.008196,-0.029501,0.406504,1.471165,no,10858,3208,5615,695,1340
0,2412,30,0.359335,0.363441,-0.000021,0.000121,10.088140,2.317845,6.926407,1.609465,-0.409729,-2.912846,-0.403226,-2.867188,no,10884,3215,5631,696,1342

2454 聯發科 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	 no news found in 20220112
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	 no news found in 20220405
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	 no news found in 20220418
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	 no news found in 20220508
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	 no news found in 20220608
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	 no news found in 20220710
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	 no news found in 20220724
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	 no news found in 20220828
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2454,1,0.460983,0.439716,0.000868,0.000233,6.080028,90.921731,-6.521739,-52.237141,67.720851,13.108001,28.636364,6.181495,yes,692,248,316,71,57
0,2454,2,0.458486,0.438675,0.000793,0.000242,1.120551,4.280240,-16.260870,-48.699815,49.499156,10.412823,49.894068,10.484598,no,1361,490,627,134,110
0,2454,3,0.460159,0.439241,0.000829,0.000329,4.081751,10.388913,-27.652174,-55.053254,60.766049,12.873522,69.867947,14.470187,no,2008,694,886,230,198
0,2454,4,0.462006,0.438124,0.000834,0.000345,9.184459,17.542152,-26.434783,-43.146750,55.291991,12.342785,67.852906,14.677315,no,2632,878,1126,338,290
0,2454,5,0.462419,0.436743,0.000890,0.000415,5.721241,8.492699,-41.739130,-54.684167,81.915867,17.852018,108.702065,22.380782,no,3233,1046,1349,449,389
0,2454,6,0.462871,0.435665,0.000933,0.000477,-0.208041,-0.253210,-40.608696,-46.968711,80.405588,18.339946,103.890490,22.545967,no,3811,1202,1557,562,490
0,2454,7,0.462560,0.434976,0.000916,0.000485,5.344918,5.571827,-46.086957,-47.445874,39.185710,10.324507,124.247227,27.123400,no,4367,1368,1777,652,570
0,2454,8,0.463878,0.435817,0.000989,0.000574,-8.383441,-7.656586,-50.782609,-47.530645,112.075444,26.277101,155.877034,33.853708,no,4900,1521,1969,752,658
0,2454,9,0.463315,0.435285,0.001034,0.000614,3.941657,3.141088,-39.391304,-33.007228,100.902244,25.390703,95.983380,24.386661,yes,5411,1695,2199,812,705
0,2454,10,0.463456,0.435484,0.001092,0.000662,3.656106,2.619128,-42.956522,-33.247380,117.354652,30.169790,119.040248,30.511756,no,5897,1863,2415,870,749
0,2454,11,0.463146,0.435203,0.001138,0.000698,-3.785058,-2.532949,-39.739130,-28.592496,108.176066,30.158207,91.474966,26.303516,yes,6363,2025,2628,922,788
0,2454,12,0.464092,0.435717,0.001197,0.000752,1.103646,0.665503,-37.130435,-24.456999,115.431339,33.406535,78.887484,24.410960,yes,6809,2169,2809,991,840
0,2454,13,0.463506,0.435753,0.001191,0.000749,13.469238,7.299025,-31.565217,-19.059996,53.432681,18.517254,87.915007,28.446334,no,7234,2323,3008,1030,873
0,2454,14,0.463795,0.436287,0.001224,0.000777,1.992400,1.017666,-41.130435,-23.809791,98.096186,33.192724,111.826347,36.988397,no,7637,2472,3194,1070,901
0,2454,15,0.463938,0.436528,0.001253,0.000799,10.589413,4.930774,-32.173913,-16.942744,90.419604,33.277350,84.725849,31.484954,yes,8014,2610,3369,1108,927
0,2454,16,0.464030,0.436813,0.001273,0.000820,4.107562,1.821392,-39.478261,-20.162049,74.621323,30.349810,104.479769,40.509422,no,8368,2741,3534,1142,951
0,2454,17,0.464988,0.438037,0.001324,0.000872,1.071014,0.449940,-39.913043,-19.317946,123.820375,50.831241,103.890490,43.823560,yes,8697,2856,3664,1188,989
0,2454,18,0.465674,0.438931,0.001355,0.000901,7.662566,2.982897,-36.086957,-16.323337,86.785413,41.238367,89.932886,42.548696,no,9002,2972,3799,1220,1011
0,2454,19,0.466020,0.439383,0.001379,0.000921,11.825272,4.306527,-24.521739,-10.069118,75.334097,39.617370,62.643678,33.520094,yes,9285,3077,3926,1250,1032
0,2454,20,0.466569,0.439850,0.001416,0.000953,8.014050,2.797939,-18.000000,-6.857203,93.381621,53.810536,50.371945,30.515866,yes,9542,3170,4037,1282,1053
0,2454,21,0.466701,0.440070,0.001445,0.000984,14.916069,4.855188,-19.478261,-7.121273,77.571195,51.020769,53.470716,36.005598,yes,9775,3253,4139,1309,1074
0,2454,22,0.466767,0.440360,0.001467,0.001013,21.067578,6.422223,-15.652174,-5.391309,64.116266,48.448774,46.936656,35.919262,yes,9990,3330,4232,1333,1095
0,2454,23,0.466752,0.440451,0.001479,0.001031,47.528270,12.876597,-2.173913,-0.682295,43.143347,37.941562,26.339286,23.327340,yes,10181,3395,4313,1357,1116
0,2454,24,0.466808,0.440816,0.001485,0.001051,54.712904,13.916988,-12.608696,-3.944179,36.820571,37.870758,39.408867,40.543148,no,10349,3456,4384,1375,1134
0,2454,25,0.466978,0.441258,0.001496,0.001077,56.713177,13.745621,7.391304,2.065394,35.717811,44.015715,11.417323,13.782699,yes,10493,3508,4442,1392,1151
0,2454,26,0.466974,0.441348,0.001497,0.001090,66.349634,15.063662,17.391304,4.520000,10.696243,15.661883,-0.352113,-0.503778,yes,10613,3548,4491,1408,1166
0,2454,27,0.467040,0.441651,0.001492,0.001099,82.086388,17.250520,-2.173913,-0.581934,5.305486,9.679431,20.425532,39.400067,no,10710,3584,4531,1418,1177
0,2454,28,0.467353,0.442134,0.001503,0.001113,75.526184,15.498240,-2.173913,-0.561293,21.619738,59.252087,25.221239,70.692962,no,10782,3614,4560,1425,1183
0,2454,29,0.467134,0.442118,0.001491,0.001109,112.574620,20.435977,15.652174,3.650683,-5.709217,-19.073778,8.015267,31.991669,no,10832,3632,4583,1428,1189
0,2454,30,0.466937,0.442137,0.001481,0.001104,124.964199,21.324237,11.304348,2.586210,-7.085877,-41.090074,10.546875,105.842281,no,10858,3641,4594,1429,1194

2881 富邦金 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	 no news found in 20220224
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	 no news found in 20220313
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	 no news found in 20220612
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	 no news found in 20220711
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2881,1,0.513869,0.522346,0.001339,0.002078,9.711798,176.081004,0.398406,4.452763,135.241339,22.599605,17.120623,3.835882,yes,685,187,171,165,162
0,2881,2,0.503709,0.507304,0.001242,0.001837,16.900786,79.917959,-3.452855,-12.380241,105.429804,19.404236,24.209078,5.485605,yes,1348,382,371,297,298
0,2881,3,0.498489,0.502258,0.001054,0.001660,28.142987,84.531117,-0.265604,-0.654918,46.762337,10.280023,22.192152,5.244966,yes,1986,556,551,434,445
0,2881,4,0.499234,0.502670,0.001071,0.001649,22.980701,46.301089,-17.928287,-30.470974,99.608699,20.053795,49.256198,11.171281,yes,2610,753,745,550,562
0,2881,5,0.495639,0.501082,0.001005,0.001608,24.132612,37.263084,-17.795485,-24.956641,47.483709,11.255604,45.880452,10.922286,yes,3210,926,922,665,697
0,2881,6,0.492084,0.498647,0.000995,0.001605,41.155727,52.139385,-25.498008,-30.115913,67.508639,15.861231,59.540636,14.260887,yes,3790,1106,1112,759,813
0,2881,7,0.488960,0.496699,0.000950,0.001564,46.239192,48.554085,-24.833997,-25.715471,38.684774,10.206362,59.540636,14.891323,no,4348,1279,1296,847,926
0,2881,8,0.487080,0.496884,0.000924,0.001578,50.243316,44.823460,-32.669323,-30.222207,41.118731,11.281463,82.424242,20.510703,no,4876,1435,1453,940,1048
0,2881,9,0.485789,0.496439,0.000945,0.001595,60.222953,45.807474,-25.232404,-20.755207,77.068784,20.358977,60.106383,16.491623,yes,5383,1603,1626,1012,1142
0,2881,10,0.485164,0.495521,0.000965,0.001593,51.516726,34.875049,-24.833997,-18.579185,74.029581,20.703828,60.676157,17.475086,yes,5864,1770,1802,1075,1217
0,2881,11,0.484284,0.494256,0.000977,0.001578,59.276788,36.273916,-20.584329,-14.207984,66.333372,20.071268,48.032787,15.144013,yes,6331,1936,1981,1130,1284
0,2881,12,0.484361,0.493784,0.000999,0.001569,52.712939,29.157375,-20.318725,-12.825801,76.592270,23.809055,53.050847,17.332061,yes,6778,2105,2158,1178,1337
0,2881,13,0.484238,0.494298,0.001003,0.001568,48.723628,24.768699,-24.966799,-14.797753,54.086242,18.717342,58.978873,20.199213,no,7201,2254,2306,1233,1408
0,2881,14,0.484868,0.494847,0.001036,0.001588,44.954620,20.990276,-20.982736,-11.385048,87.152660,30.056512,52.533784,19.367362,yes,7600,2401,2451,1284,1464
0,2881,15,0.485646,0.495342,0.001063,0.001597,50.164646,21.459322,-17.928287,-9.015128,79.707866,29.879745,46.590909,18.600543,yes,7977,2552,2600,1322,1503
0,2881,16,0.486194,0.495665,0.001090,0.001612,56.049663,22.084008,-13.944223,-6.512088,78.574356,31.744609,42.204724,18.224175,yes,8330,2687,2734,1363,1546
0,2881,17,0.486777,0.495956,0.001108,0.001616,66.603147,23.999045,-15.936255,-7.054201,63.828182,28.636505,43.789809,20.353990,yes,8659,2821,2867,1394,1577
0,2881,18,0.487780,0.496714,0.001136,0.001629,51.941247,18.120660,-19.389110,-8.222772,78.031553,37.541115,48.519737,24.432366,yes,8961,2948,2987,1423,1603
0,2881,19,0.488858,0.497634,0.001170,0.001656,58.181035,18.885834,-19.123506,-7.694754,84.148480,43.747378,47.308320,25.887943,yes,9244,3050,3079,1469,1646
0,2881,20,0.490159,0.498816,0.001194,0.001670,59.096225,18.082372,-16.069057,-6.077948,68.140410,40.387995,43.561208,26.625634,yes,9501,3161,3176,1496,1668
0,2881,21,0.491268,0.499694,0.001220,0.001682,64.662218,18.538338,-14.873838,-5.343290,67.054659,44.544323,40.873635,27.894570,yes,9734,3263,3267,1519,1685
0,2881,22,0.492411,0.500447,0.001245,0.001693,67.562139,18.300751,-12.483400,-4.248470,63.449574,47.967666,36.611195,28.246650,yes,9949,3358,3352,1541,1698
0,2881,23,0.493393,0.500873,0.001268,0.001700,89.623535,22.056870,-7.569721,-2.422140,60.061896,52.477182,30.869565,27.285982,yes,10140,3441,3429,1562,1708
0,2881,24,0.493791,0.500927,0.001285,0.001704,96.334159,22.315692,-10.225764,-3.169511,41.973353,43.192147,30.115274,30.953399,yes,10308,3512,3499,1578,1719
0,2881,25,0.494259,0.501122,0.001298,0.001706,115.082205,24.552998,-2.523240,-0.729992,36.531213,45.047166,22.357724,27.250439,yes,10452,3573,3557,1593,1729
0,2881,26,0.494608,0.501037,0.001308,0.001699,135.343277,26.614176,12.749004,3.363702,26.044368,39.293644,5.000000,7.235659,yes,10572,3622,3607,1607,1736
0,2881,27,0.494423,0.500547,0.001296,0.001681,180.003504,31.444066,14.209827,3.591169,1.009355,1.811115,4.032258,7.320646,no,10669,3658,3650,1617,1744
0,2881,28,0.494274,0.500136,0.001291,0.001672,180.311634,30.208639,15.139442,3.676266,4.114466,10.060151,4.032258,9.853665,yes,10741,3686,3684,1623,1748
0,2881,29,0.493930,0.499528,0.001289,0.001665,195.787193,30.656764,20.717131,4.751969,1.231599,4.505213,-3.215434,-11.099954,yes,10791,3704,3711,1626,1750
0,2881,30,0.493760,0.499260,0.001286,0.001661,183.658060,28.218637,20.185923,4.481150,1.190756,8.896535,0.221976,1.609264,yes,10817,3713,3724,1628,1752

2882 國泰金 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	 no news found in 20220313
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	 no news found in 20220330
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	 no news found in 20220410
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	 no news found in 20220417
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	 no news found in 20220525
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	 no news found in 20220808
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	 no news found in 20220814
Processing for date 20220816	 no news found in 20220815
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2882,1,0.494236,0.491396,0.001079,0.000857,13.892155,315.887323,2.759740,34.753152,97.165733,17.550506,3.957382,0.928703,yes,694,257,266,86,85
0,2882,2,0.494860,0.494000,0.001080,0.000858,22.759129,116.246265,-2.110390,-7.709169,97.994082,18.324756,11.601307,2.740714,yes,1362,494,506,180,182
0,2882,3,0.495782,0.493524,0.001107,0.000879,27.056384,80.689329,3.896104,9.903100,105.442997,20.158717,8.757962,2.164446,yes,2015,724,743,275,273
0,2882,4,0.494518,0.491770,0.001064,0.000856,29.061329,59.882226,-14.123377,-24.426673,76.795907,16.262220,30.592734,7.312978,yes,2645,956,988,352,349
0,2882,5,0.496157,0.493238,0.001150,0.000934,30.974929,48.489006,-13.311688,-18.884288,142.421316,27.517108,27.663551,6.934147,yes,3253,1167,1199,447,440
0,2882,6,0.496090,0.493180,0.001162,0.000975,50.292437,64.210801,-26.136364,-30.844192,97.637966,21.461505,50.275028,12.326404,yes,3836,1374,1412,529,521
0,2882,7,0.496247,0.493241,0.001179,0.001006,62.525382,65.820014,-28.490260,-29.474328,101.131173,23.079270,55.051078,13.920887,yes,4397,1569,1612,613,603
0,2882,8,0.494730,0.492926,0.001184,0.001045,51.151315,45.619494,-34.253247,-31.717149,86.953671,21.431467,72.474747,18.431312,yes,4934,1742,1792,699,701
0,2882,9,0.493750,0.492630,0.001200,0.001083,64.261965,48.740628,-32.224026,-26.741063,89.469520,23.030493,61.084906,16.722055,yes,5440,1905,1962,781,792
0,2882,10,0.494265,0.493333,0.001220,0.001116,78.908465,52.017729,-34.821429,-26.522312,97.373110,25.975615,70.112080,19.774091,yes,5928,2072,2128,858,870
0,2882,11,0.494841,0.493727,0.001241,0.001136,80.442951,48.061578,-31.818182,-22.481571,98.913261,28.045867,59.953162,18.394808,yes,6396,2243,2300,922,931
0,2882,12,0.494740,0.493629,0.001247,0.001147,81.011370,43.131727,-29.464286,-19.017516,79.911403,24.677921,59.766082,19.239581,yes,6844,2402,2464,984,994
0,2882,13,0.493810,0.493058,0.001248,0.001154,82.196939,39.719626,-32.142857,-19.441605,66.764391,22.501608,62.619048,21.283985,yes,7270,2557,2629,1033,1051
0,2882,14,0.493549,0.492600,0.001260,0.001170,83.820417,36.677490,-29.383117,-16.352285,75.923283,26.725599,58.652729,21.352266,yes,7673,2696,2777,1091,1109
0,2882,15,0.493355,0.492286,0.001275,0.001184,92.037259,36.618281,-27.597403,-14.308555,78.409807,29.460476,54.002255,21.238456,yes,8051,2840,2929,1132,1150
0,2882,16,0.493100,0.491898,0.001297,0.001204,83.391961,31.250011,-27.759740,-13.567547,84.562888,33.827116,52.625698,22.267141,yes,8406,2975,3073,1170,1188
0,2882,17,0.492903,0.491593,0.001313,0.001222,94.193495,32.270636,-27.516234,-12.681795,74.455352,32.827606,53.483146,24.426691,yes,8736,3099,3205,1207,1225
0,2882,18,0.492423,0.491137,0.001330,0.001239,78.714447,26.004436,-27.678571,-12.103093,69.167146,33.713311,53.483146,26.713537,yes,9041,3214,3330,1238,1259
0,2882,19,0.491849,0.490533,0.001344,0.001256,95.139186,28.685957,-27.191558,-11.282626,62.446567,33.423897,50.606395,27.555558,yes,9324,3316,3444,1270,1294
0,2882,20,0.491702,0.490718,0.001361,0.001277,99.059718,27.944748,-27.191558,-10.737854,62.620271,37.361598,52.285396,31.597729,yes,9581,3410,3539,1301,1331
0,2882,21,0.491339,0.490871,0.001377,0.001299,107.176210,28.195366,-27.759740,-10.495772,58.298187,39.063609,53.655793,36.123332,yes,9814,3495,3625,1327,1367
0,2882,22,0.491375,0.491141,0.001400,0.001326,107.923476,26.912230,-27.678571,-10.012963,65.054728,49.125330,51.777778,39.478670,yes,10029,3576,3705,1352,1396
0,2882,23,0.491292,0.491304,0.001414,0.001344,106.183345,25.281987,-21.185065,-7.147414,50.129782,43.964354,41.995842,36.949468,yes,10220,3644,3773,1377,1426
0,2882,24,0.491336,0.491310,0.001435,0.001366,108.294318,24.494490,-20.616883,-6.661458,51.012337,52.538189,34.448819,35.423030,yes,10388,3703,3834,1401,1450
0,2882,25,0.491265,0.491357,0.001450,0.001382,127.402032,26.557872,-8.766234,-2.595946,41.214555,51.009044,20.458554,24.895110,yes,10532,3752,3884,1422,1474
0,2882,26,0.491457,0.491582,0.001466,0.001396,135.152807,26.585915,-0.487013,-0.134512,38.479725,59.382018,9.630819,14.071277,yes,10652,3796,3926,1439,1491
0,2882,27,0.491208,0.491656,0.001464,0.001400,186.553594,32.253650,-1.785714,-0.477325,13.337543,25.077356,11.967213,22.387446,yes,10749,3830,3960,1450,1509
0,2882,28,0.490990,0.491461,0.001465,0.001403,201.309270,32.639822,2.597403,0.658857,11.906516,30.661230,8.240887,20.714810,yes,10821,3856,3990,1457,1518
0,2882,29,0.490663,0.491244,0.001464,0.001404,222.959429,33.519081,10.876623,2.578522,4.814788,18.446225,-1.443001,-5.098104,yes,10871,3871,4009,1463,1528
0,2882,30,0.490502,0.491204,0.001465,0.001407,215.463024,31.508735,9.253247,2.132310,4.644360,38.660875,1.335312,10.021563,yes,10897,3881,4020,1464,1532

2891 中信金 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	 no news found in 20220104
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	 no news found in 20220106
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	 no news found in 20220228
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	 no news found in 20220309
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	 no news found in 20220313
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	 no news found in 20220317
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	 no news found in 20220410
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	 no news found in 20220424
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	 no news found in 20220517
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	 no news found in 20220522
Processing for date 20220524	 no news found in 20220523
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	 no news found in 20220525
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	 no news found in 20220706
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	 no news found in 20220710
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	 no news found in 20220801
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	 no news found in 20220911
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	20220929 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	 no news found in 20221002
Processing for date 20221004	20221003 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	20221004 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2891,1,0.488235,0.514644,0.001096,0.001505,12.375739,259.083125,7.184466,113.865265,97.705041,17.627011,37.192982,7.822757,yes,680,246,232,86,116
0,2891,2,0.490284,0.513733,0.001172,0.001524,21.546425,108.320408,2.912621,11.403023,118.773840,21.269763,45.895522,9.751171,yes,1338,505,478,151,204
0,2891,3,0.489136,0.511096,0.001149,0.001504,24.505250,71.857910,13.980583,38.167432,92.171166,18.129326,36.000000,8.158469,yes,1979,737,705,231,306
0,2891,4,0.489419,0.511041,0.001159,0.001509,31.971130,66.575410,-1.165049,-2.132524,101.797688,20.400534,53.634578,12.024478,yes,2599,972,930,300,397
0,2891,5,0.487973,0.510004,0.001130,0.001477,45.731965,73.630825,2.135922,3.144860,74.581235,16.528110,49.236641,11.617045,yes,3201,1198,1151,364,488
0,2891,6,0.490346,0.512608,0.001170,0.001523,41.594843,52.715753,-10.873786,-13.076526,117.113269,24.763389,70.370370,16.422714,yes,3781,1423,1353,431,574
0,2891,7,0.490431,0.512934,0.001168,0.001539,56.196071,59.101034,-11.067961,-11.497973,83.108006,19.692982,68.172043,16.704396,yes,4337,1626,1544,501,666
0,2891,8,0.490353,0.513498,0.001161,0.001560,58.071698,51.672552,-20.582524,-18.913431,74.115121,18.779737,94.527363,22.937299,no,4872,1826,1730,563,753
0,2891,9,0.490247,0.514264,0.001164,0.001585,64.038607,48.578804,-15.728155,-12.794074,81.768521,21.385893,77.727273,20.503961,yes,5383,2019,1907,620,837
0,2891,10,0.490460,0.514778,0.001176,0.001603,55.513947,37.427589,-14.368932,-10.567663,84.089485,23.029665,78.538813,21.757047,yes,5870,2212,2085,667,906
0,2891,11,0.489506,0.514856,0.001160,0.001610,75.229689,45.203344,-9.902913,-6.698885,52.887166,16.487383,68.534483,20.640059,no,6337,2374,2237,728,998
0,2891,12,0.489609,0.515078,0.001168,0.001624,67.494898,36.573948,-11.650485,-7.212326,72.974151,22.850224,72.246696,22.655934,yes,6785,2545,2396,777,1067
0,2891,13,0.489043,0.515556,0.001164,0.001639,103.028638,48.412336,-15.145631,-8.749702,56.841275,19.555214,80.184332,26.322701,no,7210,2701,2538,825,1146
0,2891,14,0.488571,0.515772,0.001167,0.001656,93.321548,40.258759,-9.514563,-5.001987,58.883865,21.426365,67.811159,24.241772,no,7612,2845,2671,874,1222
0,2891,15,0.487982,0.516012,0.001159,0.001664,102.696879,40.193419,-3.883495,-1.876199,42.043864,16.945394,58.299595,22.735875,no,7988,2981,2796,917,1294
0,2891,16,0.488612,0.516860,0.001167,0.001671,89.736299,33.266888,1.165049,0.520738,55.205579,23.245489,49.236641,20.968658,yes,8342,3127,2923,949,1343
0,2891,17,0.489332,0.517809,0.001181,0.001683,84.908257,29.567666,-7.378641,-3.178474,60.000239,27.094370,66.382979,29.655932,no,8671,3271,3046,972,1382
0,2891,18,0.490251,0.518835,0.001191,0.001696,90.748858,29.316248,-4.854369,-1.961534,54.023892,26.960056,59.591837,29.476249,no,8975,3402,3155,998,1420
0,2891,19,0.491520,0.520029,0.001215,0.001716,67.670361,21.527659,-4.077670,-1.558257,67.661107,35.953072,54.240631,29.376084,yes,9257,3531,3259,1019,1448
0,2891,20,0.492904,0.521447,0.001240,0.001740,73.188061,21.724664,6.796117,2.381516,69.939506,41.366859,42.700730,26.129624,yes,9513,3647,3347,1042,1477
0,2891,21,0.493279,0.522092,0.001257,0.001764,94.750435,25.519887,8.932039,2.960376,53.738269,36.175785,38.898757,26.604780,yes,9745,3734,3418,1073,1520
0,2891,22,0.494126,0.522898,0.001279,0.001787,80.459166,21.191515,9.708738,3.062766,63.269268,47.837482,36.236934,27.966385,yes,9959,3825,3490,1096,1548
0,2891,23,0.494630,0.523260,0.001295,0.001797,96.204653,23.360943,23.883495,6.898913,46.734425,41.041019,23.343849,20.701845,yes,10149,3903,3556,1117,1573
0,2891,24,0.495299,0.523602,0.001316,0.001816,99.214969,22.848827,20.970874,5.848983,48.987988,50.443857,14.160584,14.529935,yes,10317,3971,3613,1139,1594
0,2891,25,0.495364,0.523518,0.001320,0.001820,114.225801,24.410615,37.475728,9.553925,24.337870,29.713769,7.417582,8.921526,yes,10461,4018,3657,1164,1622
0,2891,26,0.495794,0.523257,0.001337,0.001823,121.856366,24.570694,55.533981,12.950556,38.467020,59.361081,-2.493766,-3.551302,yes,10581,4061,3700,1185,1635
0,2891,27,0.495973,0.523044,0.001341,0.001826,162.664957,29.231732,34.757282,8.243456,19.395219,37.275701,13.333333,25.069054,yes,10678,4097,3736,1199,1646
0,2891,28,0.496372,0.523315,0.001348,0.001836,154.424419,27.017224,26.407767,6.185205,19.026465,51.297516,19.571865,52.950878,no,10750,4130,3762,1206,1652
0,2891,29,0.496667,0.523438,0.001355,0.001845,174.537702,28.276894,40.194175,8.687598,16.635608,74.017195,6.830601,26.854074,yes,10800,4154,3782,1210,1654
0,2891,30,0.496859,0.523492,0.001360,0.001849,170.414788,26.765372,45.048544,9.271398,7.859294,72.414789,2.894737,22.809159,yes,10826,4167,3793,1212,1654

6505 台塑化 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	 no news found in 20220104
Processing for date 20220106	 no news found in 20220105
Processing for date 20220107	 no news found in 20220106
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	 no news found in 20220113
Processing for date 20220117	 no news found in 20220116
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	 no news found in 20220120
Processing for date 20220124	 no news found in 20220123
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	 no news found in 20220206
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	 no news found in 20220208
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	 no news found in 20220210
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	 no news found in 20220216
Processing for date 20220218	 no news found in 20220217
Processing for date 20220221	 no news found in 20220220
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	 no news found in 20220222
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	 no news found in 20220306
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	 no news found in 20220309
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	 no news found in 20220314
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	 no news found in 20220317
Processing for date 20220321	 no news found in 20220320
Processing for date 20220322	 no news found in 20220321
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	 no news found in 20220324
Processing for date 20220328	 no news found in 20220327
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	 no news found in 20220405
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	 no news found in 20220410
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	 no news found in 20220414
Processing for date 20220418	 no news found in 20220417
Processing for date 20220419	 no news found in 20220418
Processing for date 20220420	 no news found in 20220419
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	 no news found in 20220421
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	 no news found in 20220425
Processing for date 20220427	 no news found in 20220426
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	 no news found in 20220428
Processing for date 20220503	 no news found in 20220502
Processing for date 20220504	 no news found in 20220503
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	 no news found in 20220508
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	 no news found in 20220518
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	 no news found in 20220522
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	 no news found in 20220524
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	 no news found in 20220605
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	 no news found in 20220612
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	 no news found in 20220614
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	 no news found in 20220620
Processing for date 20220622	 no news found in 20220621
Processing for date 20220623	 no news found in 20220622
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	 no news found in 20220626
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	 no news found in 20220629
Processing for date 20220701	 no news found in 20220630
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	 no news found in 20220710
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	 no news found in 20220719
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	 no news found in 20220721
Processing for date 20220725	 no news found in 20220724
Processing for date 20220726	 no news found in 20220725
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	 no news found in 20220801
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	 no news found in 20220807
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	 no news found in 20220814
Processing for date 20220816	 no news found in 20220815
Processing for date 20220817	 no news found in 20220816
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	 no news found in 20220821
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	 no news found in 20220823
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	 no news found in 20220831
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	 no news found in 20220904
Processing for date 20220906	 no news found in 20220905
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	 no news found in 20220911
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	 no news found in 20220913
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	 no news found in 20220918
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	 no news found in 20220920
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	 no news found in 20220925
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	20220929 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	 no news found in 20221002
Processing for date 20221004	20221003 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	 no news found in 20221004
Processing for date 20221006	20221005 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221007	 no news found in 20221006
Processing for date 20221011	20221010 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221012	20221011 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221013	20221012 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221014	20221013 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221017	 no news found in 20221016
Processing for date 20221018	20221017 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221019	20221018 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221020	 no news found in 20221019
Processing for date 20221021	20221020 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221024	20221023 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221025	20221024 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221026	 no news found in 20221025
Processing for date 20221027	 no news found in 20221026
Processing for date 20221028	20221027 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221031	 no news found in 20221030
Processing for date 20221101	20221031 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221102	20221101 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221103	 no news found in 20221102
Processing for date 20221104	20221103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221107	 no news found in 20221106
Processing for date 20221108	 no news found in 20221107
Processing for date 20221109	20221108 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221110	20221109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221111	 no news found in 20221110
Processing for date 20221114	 no news found in 20221113
Processing for date 20221115	20221114 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221116	20221115 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221117	20221116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221118	 no news found in 20221117
Processing for date 20221121	 no news found in 20221120
Processing for date 20221122	20221121 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221123	20221122 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,6505,1,0.509466,0.460526,0.001551,0.000298,5.025543,71.126951,0.313152,3.485053,137.319087,22.856661,-64.672802,-21.951192,yes,581,140,164,156,121
0,6505,2,0.507785,0.461300,0.001544,0.000338,2.788816,10.899788,-0.104384,-0.392044,131.703983,22.997318,-63.707983,-22.094814,yes,1156,298,348,289,221
0,6505,3,0.505257,0.459350,0.001469,0.000267,2.439986,6.136765,-3.444676,-8.295992,100.130631,19.358474,-62.363834,-22.061221,yes,1712,452,532,413,315
0,6505,4,0.505086,0.458079,0.001496,0.000275,5.649081,10.636645,-1.461378,-2.671582,130.030166,24.642478,-63.477801,-23.382541,yes,2261,601,711,541,408
0,6505,5,0.503041,0.454658,0.001476,0.000246,-0.544333,-0.796501,-0.835073,-1.221100,103.254059,21.495387,-63.707983,-24.288155,yes,2795,737,884,669,505
0,6505,6,0.503623,0.454922,0.001505,0.000278,2.255417,2.752417,-11.795407,-14.169536,128.069086,26.528638,-59.112426,-22.526750,yes,3312,878,1052,790,592
0,6505,7,0.504457,0.454872,0.001537,0.000303,5.050088,5.264170,-14.405010,-14.953401,133.832971,28.714553,-57.762836,-22.595220,yes,3814,1013,1214,911,676
0,6505,8,0.505114,0.454473,0.001559,0.000305,7.673476,6.957399,-16.492693,-15.123189,125.729185,28.746111,-56.265823,-22.637474,yes,4302,1148,1378,1025,751
0,6505,9,0.504921,0.452891,0.001565,0.000290,17.329192,13.638336,-11.169102,-9.039835,105.112834,26.237058,-59.778813,-25.575642,yes,4775,1269,1533,1142,831
0,6505,10,0.503919,0.451508,0.001568,0.000282,12.903003,9.130955,-16.179541,-11.933239,102.204083,27.014464,-56.649937,-24.714127,yes,5231,1392,1691,1244,904
0,6505,11,0.503615,0.450030,0.001578,0.000275,18.685516,12.064386,-13.256785,-9.022851,104.690519,29.370548,-59.160757,-27.525087,yes,5671,1504,1838,1352,977
0,6505,12,0.503117,0.447949,0.001571,0.000244,20.010337,11.653706,-11.169102,-6.907133,81.606283,25.117741,-58.672249,-28.241030,yes,6096,1605,1978,1462,1051
0,6505,13,0.502228,0.445689,0.001564,0.000212,30.670852,16.083958,-11.273486,-6.451112,78.174635,25.761667,-59.825581,-30.365054,yes,6507,1711,2128,1557,1111
0,6505,14,0.501739,0.443846,0.001563,0.000183,31.598857,15.134308,-10.125261,-5.331594,78.401995,27.471234,-59.448357,-31.508372,yes,6902,1814,2273,1649,1166
0,6505,15,0.501169,0.441736,0.001564,0.000148,39.720246,17.343726,-8.350731,-4.084033,76.574561,28.864804,-60.287356,-33.760790,yes,7271,1903,2405,1741,1222
0,6505,16,0.500459,0.439716,0.001562,0.000113,39.131390,15.960912,-17.223382,-8.126572,65.500481,27.067023,-56.321113,-32.553516,yes,7621,1984,2528,1830,1279
0,6505,17,0.500063,0.437860,0.001565,0.000086,37.134376,14.233664,-16.075157,-7.118950,65.574193,29.334041,-56.595477,-34.672082,yes,7947,2054,2637,1920,1336
0,6505,18,0.499818,0.436109,0.001570,0.000060,41.264025,14.743531,-15.866388,-6.646619,63.863571,31.380151,-56.973848,-37.253571,yes,8251,2116,2736,2008,1391
0,6505,19,0.498945,0.434045,0.001575,0.000033,41.119381,13.875657,-17.014614,-6.794031,61.016424,32.724514,-57.292954,-39.689736,yes,8534,2175,2836,2083,1440
0,6505,20,0.499147,0.432485,0.001597,0.000014,36.106312,11.666353,-14.196242,-5.333073,76.281984,44.789405,-57.762836,-43.031483,yes,8791,2226,2921,2162,1482
0,6505,21,0.499335,0.431227,0.001616,-0.000005,36.230103,11.118739,-17.536534,-6.363518,70.227373,46.509997,-55.818414,-44.370975,yes,9024,2273,2998,2233,1520
0,6505,22,0.499621,0.429976,0.001642,-0.000021,40.627013,11.739939,-22.964509,-8.143763,77.056268,57.710612,-53.373819,-45.581974,yes,9239,2318,3073,2298,1550
0,6505,23,0.500318,0.429325,0.001671,-0.000033,42.641751,11.698455,-28.914405,-10.085318,77.395162,67.205390,-49.635569,-45.941300,yes,9430,2360,3137,2358,1575
0,6505,24,0.500417,0.427881,0.001687,-0.000064,53.528721,13.655947,-25.678497,-8.479666,50.457890,51.964505,-52.410468,-53.264612,yes,9598,2391,3197,2412,1598
0,6505,25,0.501129,0.427133,0.001715,-0.000082,52.207772,12.798340,-29.645094,-9.589074,65.409761,82.402320,-48.586310,-54.820888,yes,9742,2418,3243,2464,1617
0,6505,26,0.502636,0.427043,0.001771,-0.000076,48.610395,11.541346,-31.732777,-9.990062,109.996876,189.301173,-47.412481,-60.156751,yes,9862,2435,3267,2522,1638
0,6505,27,0.503063,0.425987,0.001798,-0.000097,64.783994,14.182671,-33.611691,-10.307170,55.656138,120.519025,-45.245642,-65.920518,yes,9959,2449,3300,2561,1649
0,6505,28,0.503340,0.425337,0.001815,-0.000114,81.618367,16.511873,-47.077244,-15.037848,31.896479,93.124521,-32.519531,-60.744991,yes,10031,2461,3325,2588,1657
0,6505,29,0.504017,0.425198,0.001841,-0.000117,110.943903,20.207505,-48.538622,-15.109629,42.277756,255.871509,-29.417773,-71.469901,yes,10081,2467,3335,2614,1665
0,6505,30,0.504403,0.425177,0.001857,-0.000120,136.191234,22.741108,-54.123173,-16.953703,24.160667,374.990651,-20.756881,-81.270627,yes,10107,2469,3338,2629,1671

3231 緯創 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	 no news found in 20220103
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	 no news found in 20220206
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	 no news found in 20220208
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	 no news found in 20220217
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	 no news found in 20220221
Processing for date 20220223	 no news found in 20220222
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	 no news found in 20220302
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	 no news found in 20220306
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	 no news found in 20220308
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	 no news found in 20220313
Processing for date 20220315	 no news found in 20220314
Processing for date 20220316	 no news found in 20220315
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	 no news found in 20220320
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	 no news found in 20220405
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	 no news found in 20220407
Processing for date 20220411	 no news found in 20220410
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	 no news found in 20220414
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	 no news found in 20220505
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	 no news found in 20220509
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	 no news found in 20220526
Processing for date 20220530	 no news found in 20220529
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	 no news found in 20220606
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	 no news found in 20220612
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	 no news found in 20220623
Processing for date 20220627	 no news found in 20220626
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	 no news found in 20220628
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	 no news found in 20220705
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	 no news found in 20220710
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	 no news found in 20220712
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	 no news found in 20220718
Processing for date 20220720	 no news found in 20220719
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	 no news found in 20220724
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	 no news found in 20220807
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	20220815 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	 no news found in 20220821
Processing for date 20220823	 no news found in 20220822
Processing for date 20220824	 no news found in 20220823
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	 no news found in 20220825
Processing for date 20220829	 no news found in 20220828
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	 no news found in 20220904
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	20220911 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220913	 no news found in 20220912
Processing for date 20220914	20220913 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	 no news found in 20220925
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	20220929 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	 no news found in 20221002
Processing for date 20221004	20221003 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	20221004 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221006	20221005 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221007	20221006 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221011	20221010 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221012	20221011 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221013	20221012 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221014	 no news found in 20221013
Processing for date 20221017	20221016 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221018	20221017 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221019	20221018 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221020	20221019 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221021	20221020 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221024	20221023 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221025	20221024 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221026	 no news found in 20221025
Processing for date 20221027	20221026 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,3231,1,0.458268,0.454717,-0.000101,-0.000254,9.435487,168.557559,8.103448,134.835492,-22.264978,-5.822639,229.113924,32.808004,no,635,241,289,50,55
0,3231,2,0.457211,0.452991,-0.000026,-0.000212,14.059077,64.012318,1.724138,6.640746,-14.439764,-3.768720,250.758853,36.224219,no,1262,477,576,100,109
0,3231,3,0.454594,0.450878,-0.000121,-0.000275,10.298083,27.399555,1.379310,3.442343,-31.964825,-9.356454,254.344123,38.081915,no,1872,693,844,158,177
0,3231,4,0.454878,0.451262,-0.000072,-0.000244,12.124840,23.430462,-4.137931,-7.478892,-12.945545,-3.599553,276.811594,42.018021,no,2460,912,1109,207,232
0,3231,5,0.452412,0.449217,-0.000147,-0.000291,19.258908,29.439837,-1.034483,-1.511984,-36.357324,-11.666178,265.553603,42.736679,no,3026,1119,1372,250,285
0,3231,6,0.451271,0.447899,-0.000131,-0.000283,17.413657,21.583554,-8.620690,-10.394113,-18.699550,-5.736977,295.437262,48.047269,no,3581,1311,1616,305,349
0,3231,7,0.450133,0.446099,-0.000128,-0.000290,18.661814,19.503792,-5.862069,-6.096767,-21.620819,-6.983574,283.057090,49.048739,no,4121,1498,1860,357,406
0,3231,8,0.448417,0.444268,-0.000204,-0.000344,17.275967,15.601300,-7.586207,-6.925836,-44.421542,-16.663923,295.437262,53.214526,no,4643,1678,2099,404,462
0,3231,9,0.448356,0.443250,-0.000205,-0.000353,22.153800,17.361482,-5.172414,-4.159790,-25.357626,-9.049291,277.495463,53.853191,no,5141,1855,2330,450,506
0,3231,10,0.447926,0.441541,-0.000197,-0.000371,26.699755,18.576481,5.172414,3.697748,-19.737269,-7.195129,245.514950,52.361603,no,5617,2028,2565,488,536
0,3231,11,0.446784,0.439728,-0.000199,-0.000389,29.051156,18.480379,4.137931,2.732610,-24.602311,-9.653387,233.333333,54.158623,no,6079,2196,2798,520,565
0,3231,12,0.445501,0.437803,-0.000235,-0.000434,47.026878,26.229429,14.310345,8.418164,-39.083623,-16.985306,219.508449,54.690206,no,6523,2351,3019,555,598
0,3231,13,0.444860,0.435983,-0.000219,-0.000459,51.155655,25.902128,44.310345,22.690761,-14.828705,-6.171051,151.207729,44.129624,no,6946,2496,3229,594,627
0,3231,14,0.444066,0.434158,-0.000242,-0.000517,84.070050,36.772722,72.413793,32.256739,-34.728720,-16.379497,116.216216,38.171680,no,7348,2631,3429,632,656
0,3231,15,0.442718,0.431733,-0.000304,-0.000622,84.655335,34.081383,164.482759,59.214011,-51.174790,-27.367705,29.675810,12.288970,no,7725,2751,3621,669,684
0,3231,16,0.441391,0.429257,-0.000361,-0.000739,163.854958,54.503948,341.379310,94.595490,-52.443075,-29.769739,-22.676580,-11.509822,no,8079,2861,3804,705,709
0,3231,17,0.439700,0.426657,-0.000454,-0.000872,245.191704,68.554810,322.413793,83.522350,-62.640265,-39.483473,-6.306306,-3.268294,no,8408,2961,3979,736,732
0,3231,18,0.437902,0.424044,-0.000526,-0.000980,172.914351,49.136504,250.000000,64.662919,-59.772722,-39.543136,-6.306306,-3.535781,no,8712,3051,4144,764,753
0,3231,19,0.436291,0.421789,-0.000591,-0.001068,148.154787,40.898818,220.000000,55.083488,-56.353924,-38.905071,14.035088,8.118557,no,8994,3136,4299,788,771
0,3231,20,0.434919,0.419835,-0.000643,-0.001138,125.068368,33.694199,219.310345,51.525362,-49.463954,-35.953388,13.289760,8.487164,no,9250,3213,4440,810,787
0,3231,21,0.433196,0.417612,-0.000704,-0.001213,126.178417,32.089509,243.103448,52.258195,-52.612188,-41.501424,5.476673,3.902291,no,9483,3277,4570,831,805
0,3231,22,0.431326,0.415327,-0.000772,-0.001291,110.662032,27.454058,334.482759,61.328833,-56.840878,-48.833944,-15.102041,-12.239759,no,9698,3333,4692,850,823
0,3231,23,0.430175,0.413705,-0.000782,-0.001322,89.287469,21.989447,324.137931,56.843220,-23.110670,-20.996738,-14.754098,-13.338101,no,9889,3387,4800,867,835
0,3231,24,0.428856,0.412104,-0.000822,-0.001363,95.076953,22.081308,289.655172,50.094336,-44.122652,-44.910249,-8.771930,-8.975980,no,10057,3432,4896,881,848
0,3231,25,0.427899,0.410930,-0.000826,-0.001374,71.290606,16.683362,286.206897,47.310971,-16.707701,-19.614567,-8.771930,-10.384952,no,10201,3474,4980,891,856
0,3231,26,0.427381,0.410169,-0.000837,-0.001387,59.414366,13.720584,275.862069,44.059457,-22.335547,-30.366491,-6.306306,-8.905034,no,10321,3509,5046,902,864
0,3231,27,0.426761,0.409586,-0.000856,-0.001400,55.806055,12.496590,235.517241,37.911260,-28.980939,-45.753440,1.463415,2.630515,no,10418,3538,5100,908,872
0,3231,28,0.426025,0.409054,-0.000872,-0.001412,76.355829,15.637803,248.275862,37.652865,-22.204771,-44.950155,0.970874,2.323566,no,10490,3560,5143,909,878
0,3231,29,0.425617,0.408618,-0.000882,-0.001422,56.647432,11.702598,281.034483,39.075768,-16.652596,-48.094726,-7.964602,-25.828404,no,10540,3575,5174,911,880
0,3231,30,0.425461,0.408256,-0.000894,-0.001439,63.613752,12.454518,329.310345,41.533549,-12.293061,-61.109414,-13.333333,-64.310943,yes,10565,3580,5189,915,881

2207 和泰車 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	 no news found in 20220306
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	 no news found in 20220411
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	 no news found in 20220424
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	20220515 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	 no news found in 20220530
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	 no news found in 20220605
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	 no news found in 20220726
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	 no news found in 20220801
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	 no news found in 20220807
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	 no news found in 20220814
Processing for date 20220816	 no news found in 20220815
Processing for date 20220817	 no news found in 20220816
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	 no news found in 20220821
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	 no news found in 20220823
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	 no news found in 20220831
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	 no news found in 20220904
Processing for date 20220906	 no news found in 20220905
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	 no news found in 20220911
Processing for date 20220913	20220912 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220914	 no news found in 20220913
Processing for date 20220915	20220914 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	 no news found in 20220918
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	 no news found in 20220920
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	 no news found in 20220925
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	20220929 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	 no news found in 20221002
Processing for date 20221004	20221003 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	 no news found in 20221004
Processing for date 20221006	20221005 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221007	 no news found in 20221006
Processing for date 20221011	20221010 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221012	20221011 news found

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2207,1,0.458003,0.453515,0.000079,0.000202,6.441705,98.176100,-2.272727,-22.266600,-2.912388,-0.701518,1.642036,0.388686,no,631,200,241,89,101
0,2207,2,0.454766,0.449649,0.000031,0.000106,25.085146,132.064998,-5.519481,-19.228620,-5.479266,-1.378528,6.540448,1.572881,no,1238,384,470,179,205
0,2207,3,0.450549,0.444082,-0.000010,0.000048,31.017023,94.925431,-6.168831,-14.556086,-10.486249,-2.785966,8.027923,1.989092,no,1820,544,681,276,319
0,2207,4,0.447491,0.440935,-0.000058,-0.000009,46.477972,101.801441,-6.006494,-10.769001,-16.622319,-4.693318,7.093426,1.828682,no,2371,698,885,363,425
0,2207,5,0.443795,0.435992,-0.000105,-0.000080,55.834726,91.547072,0.487013,0.714338,-19.459599,-5.767685,-1.589825,-0.438963,no,2909,831,1075,460,543
0,2207,6,0.442078,0.432145,-0.000110,-0.000103,58.647866,75.390835,-1.948052,-2.366494,-11.183929,-3.328164,2.995008,0.845754,no,3427,933,1226,582,686
0,2207,7,0.440570,0.429948,-0.000188,-0.000195,55.280531,58.130049,-5.681818,-5.909529,-33.438420,-11.393130,5.451448,1.589897,no,3929,1071,1420,660,778
0,2207,8,0.440118,0.428724,-0.000180,-0.000216,48.362373,43.173070,-6.168831,-5.628062,-10.722286,-3.458651,11.531532,3.445028,no,4417,1203,1603,741,870
0,2207,9,0.439468,0.427328,-0.000183,-0.000241,48.070474,36.890961,0.000000,0.000000,-14.990816,-5.131058,-0.322061,-0.104566,no,4890,1326,1777,823,964
0,2207,10,0.439020,0.426200,-0.000181,-0.000253,44.637035,30.437134,-3.409091,-2.466434,-10.437621,-3.674610,5.451448,1.819080,no,5346,1438,1936,909,1063
0,2207,11,0.439336,0.425549,-0.000172,-0.000264,44.900680,27.966696,1.623377,1.076481,-7.655376,-2.822450,-6.354009,-2.332347,no,5786,1549,2091,993,1153
0,2207,12,0.438738,0.424056,-0.000173,-0.000280,49.948765,27.739497,0.162338,0.098072,-11.047181,-4.301203,1.143791,0.428036,no,6211,1650,2241,1075,1245
0,2207,13,0.438689,0.423123,-0.000180,-0.000305,50.658417,25.671054,4.220779,2.331639,-12.818172,-5.298246,-2.056962,-0.821426,no,6622,1753,2390,1152,1327
0,2207,14,0.439362,0.422584,-0.000154,-0.000309,46.424598,21.618451,9.902597,4.965566,5.786059,2.386541,-7.749627,-3.325687,yes,7017,1845,2521,1238,1413
0,2207,15,0.438939,0.421341,-0.000165,-0.000348,81.381579,32.939384,33.603896,14.858723,-15.442484,-7.208414,-25.511432,-12.310073,yes,7386,1923,2641,1319,1503
0,2207,16,0.437767,0.419870,-0.000184,-0.000386,90.873395,33.624421,24.512987,10.330126,-20.248722,-10.199442,-20.231959,-10.190468,no,7737,1999,2762,1388,1588
0,2207,17,0.437360,0.419466,-0.000191,-0.000395,70.863486,25.325512,12.337662,5.024744,-13.333868,-7.040099,-10.289855,-5.388600,no,8062,2073,2869,1453,1667
0,2207,18,0.437418,0.419532,-0.000180,-0.000382,58.947173,20.259557,6.331169,2.474001,0.662484,0.365569,-4.915515,-2.747067,yes,8365,2135,2954,1524,1752
0,2207,19,0.437211,0.419939,-0.000179,-0.000369,55.767906,18.198361,0.162338,0.061210,-4.575427,-2.745151,-1.746032,-1.041441,no,8648,2203,3043,1578,1824
0,2207,20,0.437156,0.420516,-0.000174,-0.000364,56.817647,17.474202,13.798701,4.735667,-1.450162,-0.949137,-12.198582,-8.142422,yes,8903,2267,3124,1625,1887
0,2207,21,0.436672,0.420395,-0.000179,-0.000367,63.112740,18.156782,9.577922,3.168144,-9.444421,-6.874776,-7.886905,-5.727597,no,9135,2321,3200,1668,1946
0,2207,22,0.436624,0.420182,-0.000181,-0.000367,68.276507,18.464723,5.519481,1.764587,-7.113185,-5.714613,-5.783866,-4.640113,no,9349,2361,3258,1721,2009
0,2207,23,0.436897,0.420603,-0.000184,-0.000369,75.423961,19.133154,4.545455,1.394284,-5.358560,-4.819098,-4.769231,-4.287748,no,9540,2413,3324,1755,2048
0,2207,24,0.436959,0.420710,-0.000192,-0.000378,78.856509,18.957660,-1.136364,-0.340654,-10.158729,-10.393161,-0.482315,-0.494050,no,9708,2454,3379,1788,2087
0,2207,25,0.436910,0.421008,-0.000197,-0.000377,66.303883,15.699206,-0.324675,-0.093189,-9.892534,-11.698066,0.487013,0.581921,no,9851,2489,3423,1815,2124
0,2207,26,0.436810,0.421246,-0.000205,-0.000383,72.739302,16.265641,0.649351,0.178614,-10.391693,-14.538327,0.324149,0.464447,no,9970,2522,3465,1833,2150
0,2207,27,0.435979,0.420844,-0.000230,-0.000401,109.355154,21.676947,-2.435065,-0.652479,-24.215085,-39.076306,1.809211,3.256480,no,10067,2544,3501,1845,2177
0,2207,28,0.435422,0.420483,-0.000239,-0.000408,87.987822,17.544944,3.084416,0.781008,-11.222494,-24.647519,-3.582555,-8.307834,no,10135,2562,3531,1851,2191
0,2207,29,0.434701,0.419539,-0.000248,-0.000420,79.925986,15.584571,7.305195,1.753726,-9.813972,-31.055229,-7.196402,-23.575372,no,10184,2568,3553,1859,2204
0,2207,30,0.434519,0.419271,-0.000249,-0.000424,62.034050,12.194705,3.571429,0.840124,-2.677188,-17.748188,-3.281250,-21.353960,yes,10209,2576,3568,1860,2205

3661 世芯 tw tv1
Processing for date 20220103	 no news found in 20220102
Processing for date 20220104	 no news found in 20220103
Processing for date 20220105	 no news found in 20220104
Processing for date 20220106	 no news found in 20220105
Processing for date 20220107	 no news found in 20220106
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	 no news found in 20220110
Processing for date 20220112	 no news found in 20220111
Processing for date 20220113	 no news found in 20220112
Processing for date 20220114	 no news found in 20220113
Processing for date 20220117	 no news found in 20220116
Processing for date 20220118	 no news found in 20220117
Processing for date 20220119	 no news found in 20220118
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	 no news found in 20220120
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	 no news found in 20220124
Processing for date 20220126	 no news found in 20220125
Processing for date 20220207	 no news found in 20220206
Processing for date 20220208	 no news found in 20220207
Processing for date 20220209	 no news found in 20220208
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	 no news found in 20220214
Processing for date 20220216	 no news found in 20220215
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	 no news found in 20220217
Processing for date 20220221	 no news found in 20220220
Processing for date 20220222	 no news found in 20220221
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	 no news found in 20220223
Processing for date 20220225	 no news found in 20220224
Processing for date 20220301	 no news found in 20220228
Processing for date 20220302	 no news found in 20220301
Processing for date 20220303	 no news found in 20220302
Processing for date 20220304	 no news found in 20220303
Processing for date 20220307	 no news found in 20220306
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	 no news found in 20220309
Processing for date 20220311	 no news found in 20220310
Processing for date 20220314	 no news found in 20220313
Processing for date 20220315	 no news found in 20220314
Processing for date 20220316	 no news found in 20220315
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	 no news found in 20220320
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	 no news found in 20220327
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	 no news found in 20220331
Processing for date 20220406	 no news found in 20220405
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	 no news found in 20220407
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	 no news found in 20220411
Processing for date 20220413	 no news found in 20220412
Processing for date 20220414	 no news found in 20220413
Processing for date 20220415	 no news found in 20220414
Processing for date 20220418	 no news found in 20220417
Processing for date 20220419	 no news found in 20220418
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	 no news found in 20220420
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	 no news found in 20220424
Processing for date 20220426	 no news found in 20220425
Processing for date 20220427	 no news found in 20220426
Processing for date 20220428	 no news found in 20220427
Processing for date 20220429	 no news found in 20220428
Processing for date 20220503	 no news found in 20220502
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	 no news found in 20220504
Processing for date 20220506	 no news found in 20220505
Processing for date 20220509	 no news found in 20220508
Processing for date 20220510	 no news found in 20220509
Processing for date 20220511	 no news found in 20220510
Processing for date 20220512	 no news found in 20220511
Processing for date 20220513	 no news found in 20220512
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	 no news found in 20220516
Processing for date 20220518	 no news found in 20220517
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	 no news found in 20220522
Processing for date 20220524	 no news found in 20220523
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	 no news found in 20220525
Processing for date 20220527	 no news found in 20220526
Processing for date 20220530	 no news found in 20220529
Processing for date 20220531	 no news found in 20220530
Processing for date 20220601	 no news found in 20220531
Processing for date 20220602	 no news found in 20220601
Processing for date 20220606	 no news found in 20220605
Processing for date 20220607	 no news found in 20220606
Processing for date 20220608	 no news found in 20220607
Processing for date 20220609	 no news found in 20220608
Processing for date 20220610	 no news found in 20220609
Processing for date 20220613	 no news found in 20220612
Processing for date 20220614	 no news found in 20220613
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	 no news found in 20220615
Processing for date 20220617	 no news found in 20220616
Processing for date 20220620	 no news found in 20220619
Processing for date 20220621	 no news found in 20220620
Processing for date 20220622	 no news found in 20220621
Processing for date 20220623	 no news found in 20220622
Processing for date 20220624	 no news found in 20220623
Processing for date 20220627	 no news found in 20220626
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	 no news found in 20220629
Processing for date 20220701	 no news found in 20220630
Processing for date 20220704	 no news found in 20220703
Processing for date 20220705	 no news found in 20220704
Processing for date 20220706	 no news found in 20220705
Processing for date 20220707	 no news found in 20220706
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	 no news found in 20220710
Processing for date 20220712	 no news found in 20220711
Processing for date 20220713	 no news found in 20220712
Processing for date 20220714	 no news found in 20220713
Processing for date 20220715	 no news found in 20220714
Processing for date 20220718	 no news found in 20220717
Processing for date 20220719	 no news found in 20220718
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	 no news found in 20220720
Processing for date 20220722	 no news found in 20220721
Processing for date 20220725	 no news found in 20220724
Processing for date 20220726	 no news found in 20220725
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	 no news found in 20220727
Processing for date 20220729	 no news found in 20220728
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	 no news found in 20220801
Processing for date 20220803	 no news found in 20220802
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	 no news found in 20220804
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	 no news found in 20220808
Processing for date 20220810	 no news found in 20220809
Processing for date 20220811	 no news found in 20220810
Processing for date 20220812	 no news found in 20220811
Processing for date 20220815	 no news found in 20220814
Processing for date 20220816	 no news found in 20220815
Processing for date 20220817	 no news found in 20220816
Processing for date 20220818	 no news found in 20220817
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	 no news found in 20220821
Processing for date 20220823	 no news found in 20220822
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	 no news found in 20220825
Processing for date 20220829	 no news found in 20220828
Processing for date 20220830	 no news found in 20220829
Processing for date 20220831	 no news found in 20220830
Processing for date 20220901	 no news found in 20220831
Processing for date 20220902	 no news found in 20220901
Processing for date 20220905	 no news found in 20220904
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	 no news found in 20220906
Processing for date 20220908	 no news found in 20220907
Processing for date 20220912	 no news found in 20220911
Processing for date 20220913	 no news found in 20220912
Processing for date 20220914	 no news found in 20220913
Processing for date 20220915	 no news found in 20220914
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	 no news found in 20220918
Processing for date 20220920	 no news found in 20220919
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	 no news found in 20220921
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	 no news found in 20220925
Processing for date 20220927	 no news found in 20220926
Processing for date 20220928	 no news found in 20220927
Processing for date 20220929	 no news found in 20220928
Processing for date 20220930	20220929 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	 no news found in 20221002
Processing for date 20221004	20221003 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	20221004 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221006	 no news found in 20221005
Processing for date 20221007	20221006 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221011	20221010 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221012	 no news found in 20221011
Processing for date 20221013	20221012 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221014	 no news found in 20221013
Processing for date 20221017	20221016 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221018	 no news found in 20221017
Processing for date 20221019	 no news found in 20221018
Processing for date 20221020	20221019 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221021	 no news found in 20221020
Processing for date 20221024	 no news found in 20221023
Processing for date 20221025	 no news found in 20221024
Processing for date 20221026	 no news found in 20221025
Processing for date 20221027	20221026 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221028	20221027 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221031	 no news found in 20221030
Processing for date 20221101	20221031 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221102	 no news found in 20221101
Processing for date 20221103	 no news found in 20221102
Processing for date 20221104	 no news found in 20221103
Processing for date 20221107	 no news found in 20221106
Processing for date 20221108	20221107 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221109	20221108 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221110	20221109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221111	20221110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221114	 no news found in 20221113
Processing for date 20221115	20221114 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221116	 no news found in 20221115
Processing for date 20221117	20221116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221118	 no news found in 20221117
Processing for date 20221121	20221120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221122	 no news found in 20221121
Processing for date 20221123	20221122 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221124	 no news found in 20221123
Processing for date 20221125	 no news found in 20221124
Processing for date 20221128	 no news found in 20221127
Processing for date 20221129	20221128 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221130	 no news found in 20221129
Processing for date 20221201	20221130 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221202	20221201 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221205	 no news found in 20221204
Processing for date 20221206	20221205 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221207	20221206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221208	20221207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221209	 no news found in 20221208
Processing for date 20221212	 no news found in 20221211
Processing for date 20221213	20221212 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221214	20221213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221215	20221214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221216	 no news found in 20221215
Processing for date 20221219	 no news found in 20221218
Processing for date 20221220	 no news found in 20221219
Processing for date 20221221	20221220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221222	20221221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221223	20221222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221226	 no news found in 20221225
Processing for date 20221227	 no news found in 20221226
Processing for date 20221228	 no news found in 20221227
Processing for date 20221229	20221228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221230	20221229 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230103	 no news found in 20230102
Processing for date 20230104	20230103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230105	 no news found in 20230104
Processing for date 20230106	20230105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230109	20230108 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230110	 no news found in 20230109
Processing for date 20230111	 no news found in 20230110
Processing for date 20230112	 no news found in 20230111
Processing for date 20230113	 no news found in 20230112
Processing for date 20230116	20230115 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230117	20230116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230130	 no news found in 20230129
Processing for date 20230131	 no news found in 20230130
Processing for date 20230201	20230131 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230202	20230201 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230203	20230202 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230206	 no news found in 20230205
Processing for date 20230207	 no news found in 20230206
Processing for date 20230208	 no news found in 20230207
Processing for date 20230209	20230208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230210	20230209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20230213	20230212 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,3661,1,0.520958,0.470297,0.002023,-0.001154,7.714948,125.752441,-6.406406,-51.587499,108.608782,19.140746,245.263158,34.331991,no,501,190,214,71,26
0,3661,2,0.526633,0.474874,0.002387,-0.000896,3.007255,11.788814,9.109109,38.804199,198.356766,30.901233,203.703704,31.475251,no,995,378,418,146,53
0,3661,3,0.525996,0.473950,0.002332,-0.000894,8.844256,23.290972,-7.407407,-17.315584,125.279937,23.017150,248.565356,37.504024,no,1481,564,626,215,76
0,3661,4,0.528646,0.475241,0.002132,-0.001091,9.210383,17.593492,-4.904905,-8.835933,48.436087,11.009428,247.826087,39.043719,no,1920,691,763,324,142
0,3661,5,0.528302,0.475248,0.002190,-0.001037,3.624032,5.354093,-28.628629,-38.990750,139.437076,27.084258,335.013263,49.718406,no,2385,864,954,396,171
0,3661,6,0.530175,0.476766,0.002323,-0.000944,9.382418,11.535822,-29.329329,-34.466234,212.937752,38.483841,398.480243,58.162036,no,2850,1026,1126,485,213
0,3661,7,0.529713,0.476911,0.002407,-0.000855,-1.112874,-1.158593,-7.407407,-7.701403,201.254645,38.779287,277.011494,48.345776,no,3315,1198,1314,558,245
0,3661,8,0.529989,0.477186,0.002444,-0.000809,19.954891,18.001187,-8.008008,-7.312390,167.834417,35.764467,296.135266,53.298406,no,3768,1370,1501,627,270
0,3661,9,0.530724,0.477421,0.002510,-0.000756,51.782636,39.629657,-16.916917,-13.779590,208.899931,44.164998,289.086595,55.369711,no,4215,1533,1678,704,300
0,3661,10,0.531082,0.477100,0.002553,-0.000714,34.680736,23.908171,-11.411411,-8.354319,187.793453,43.190522,298.541920,59.931706,no,4649,1698,1861,771,319
0,3661,11,0.531232,0.476717,0.002548,-0.000711,49.336219,30.558076,-15.315315,-10.464161,129.559497,34.814609,279.629630,61.537034,no,5075,1853,2034,843,345
0,3661,12,0.530463,0.475919,0.002554,-0.000689,52.058337,28.822522,-5.505506,-3.364267,133.350695,37.470363,216.908213,54.216206,no,5482,2006,2209,902,365
0,3661,13,0.530022,0.475044,0.002556,-0.000686,67.148707,33.163398,24.124124,12.804625,124.012025,37.722633,171.074380,48.549547,no,5879,2151,2377,965,386
0,3661,14,0.529327,0.474066,0.002506,-0.000717,98.024111,41.999585,27.627628,13.337825,51.259188,18.948110,143.866171,45.322580,no,6257,2285,2535,1027,410
0,3661,15,0.530603,0.473944,0.002557,-0.000715,169.879810,60.759392,76.176176,31.101186,183.173486,59.082884,82.222222,30.687127,yes,6617,2401,2665,1110,441
0,3661,16,0.529818,0.472598,0.002515,-0.000781,208.306283,65.675771,113.213213,40.423496,46.622141,19.956334,52.558140,22.241405,no,6959,2518,2810,1169,462
0,3661,17,0.528846,0.471306,0.002443,-0.000852,232.436294,65.901524,149.749750,47.065395,12.287513,6.090173,34.979424,16.533900,no,7280,2628,2948,1222,482
0,3661,18,0.529311,0.470954,0.002463,-0.000881,273.220451,68.928093,169.269269,48.340315,101.720906,47.372000,20.146520,10.675355,yes,7574,2724,3060,1285,505
0,3661,19,0.530116,0.470874,0.002471,-0.000914,325.740207,72.719750,182.282282,47.917096,79.798786,41.719583,14.886165,8.597418,yes,7853,2813,3161,1350,529
0,3661,20,0.529296,0.470073,0.002396,-0.000999,271.939429,60.030633,233.833834,53.957223,-15.439475,-10.370405,-6.552707,-4.328079,no,8107,2898,3267,1393,549
0,3661,21,0.529680,0.469591,0.002422,-0.001025,291.940063,59.326753,273.873874,56.783386,84.581846,55.278040,-11.351351,-8.286923,yes,8339,2965,3349,1452,573
0,3661,22,0.530285,0.469249,0.002464,-0.001043,247.578394,50.022610,318.918919,59.424089,113.044041,82.786428,-19.607843,-15.974538,yes,8552,3029,3426,1506,591
0,3661,23,0.531061,0.469130,0.002515,-0.001024,235.956215,45.859519,245.345345,47.117274,130.951882,111.838578,-5.202312,-4.678189,yes,8741,3085,3491,1557,608
0,3661,24,0.531432,0.469021,0.002553,-0.000999,264.101377,47.085124,211.311311,40.364488,102.906185,106.438309,4.960000,5.084001,yes,8908,3134,3548,1600,626
0,3661,25,0.531934,0.469243,0.002642,-0.000921,112.130333,24.060509,187.287287,35.330119,203.640436,276.780354,13.691508,16.561921,yes,9050,3181,3598,1633,638
0,3661,26,0.533050,0.469996,0.002749,-0.000820,99.084606,20.906048,152.752753,29.130179,245.976809,491.312800,31.726908,48.372058,yes,9168,3219,3630,1668,651
0,3661,27,0.534060,0.470460,0.002825,-0.000746,174.639389,30.770642,124.224224,23.914229,148.288543,408.019082,45.454545,95.358254,yes,9263,3249,3657,1698,659
0,3661,28,0.534983,0.470791,0.002889,-0.000687,173.942828,29.444512,137.237237,24.762312,115.126086,517.917803,36.666667,110.144796,yes,9333,3272,3678,1721,662
0,3661,29,0.535330,0.471085,0.002923,-0.000633,411.557350,49.553252,98.198198,18.374310,50.095692,331.445180,60.391198,447.835174,no,9383,3291,3695,1732,665
0,3661,30,0.535551,0.471386,0.002954,-0.000590,251.954615,34.985839,131.731732,22.184583,46.284913,1446.808910,45.777778,1408.611953,yes,9409,3303,3704,1736,666

2603 長榮 tw tv1
Processing for date 20220103	20220102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220104	20220103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220105	20220104 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220106	20220105 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	20220109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	20220118 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	20220120 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220124	20220123 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	20220125 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220207	20220206 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220208	20220207 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220209	20220208 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220210	20220209 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220211	20220210 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220214	20220213 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220215	20220214 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	20220220 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	20220223 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	20220228 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220302	20220301 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	20220308 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	20220313 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220315	20220314 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	20220320 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	20220327 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	20220329 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	20220331 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	20220417 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	20220419 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220421	20220420 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	20220424 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220426	20220425 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220427	20220426 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	20220428 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220503	20220502 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220504	20220503 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	20220505 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220509	20220508 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220510	20220509 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220511	20220510 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	20220518 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	20220529 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220531	20220530 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	20220601 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220606	20220605 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	20220607 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	20220620 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	20220630 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220704	20220703 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	20220710 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	20220713 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	20220717 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220719	20220718 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220720	20220719 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220721	20220720 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	20220724 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	20220727 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220729	20220728 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220801	20220731 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220802	20220801 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	20220804 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	20220808 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	20220814 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220816	 no news found in 20220815
Processing for date 20220817	20220816 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	20220821 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	20220823 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	20220825 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	20220830 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	20220918 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	20220921 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	20220925 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	20220929 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221003	20221002 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2603,1,0.436090,0.403141,-5.662437e-04,-0.002154,-5.232856,-44.505419,-18.996416,-90.056834,-37.866657,-10.716132,81.451613,15.247899,no,665,154,228,136,147
0,2603,2,0.447244,0.406907,-1.179666e-04,-0.002076,-9.564705,-31.486116,14.695341,67.480101,8.660725,2.067134,36.778116,8.020345,no,1270,271,395,297,307
0,2603,3,0.447313,0.410696,-3.108346e-05,-0.001919,-17.150326,-37.175330,1.433692,3.579486,-8.028380,-2.111985,63.043478,13.279225,no,1898,407,584,442,465
0,2603,4,0.444666,0.408805,-8.239841e-06,-0.001900,9.796134,18.756248,-3.225806,-5.853125,-13.951839,-3.895474,56.250000,12.525633,no,2503,520,752,593,638
0,2603,5,0.439857,0.406494,-1.751002e-04,-0.001837,1.794857,2.640616,-29.247312,-39.764025,-44.154129,-14.779011,107.373272,22.166391,no,3076,676,987,677,736
0,2603,6,0.440893,0.407942,-9.953240e-05,-0.001696,-16.894892,-20.171956,-31.541219,-36.954674,5.820244,1.627606,132.919255,27.290798,no,3629,791,1148,809,881
0,2603,7,0.440096,0.408500,-8.237973e-05,-0.001584,-34.066336,-35.191450,-42.867384,-44.173808,-8.077665,-2.471883,181.250000,35.974272,no,4165,942,1364,891,968
0,2603,8,0.441195,0.410058,-1.898081e-05,-0.001455,-6.579180,-6.003602,11.469534,10.382497,14.123407,4.185181,44.230769,12.037343,no,4685,1060,1525,1007,1093
0,2603,9,0.439104,0.408870,-5.990024e-05,-0.001414,-11.738684,-9.506722,11.469534,9.074931,-28.464080,-10.294587,45.161290,12.847556,no,5181,1180,1706,1095,1200
0,2603,10,0.437489,0.408385,-1.125343e-04,-0.001396,-19.752240,-14.652324,16.129032,11.367221,-32.726132,-12.595712,41.955836,12.635344,no,5655,1315,1905,1159,1276
0,2603,11,0.436468,0.407899,-1.537529e-04,-0.001388,-1.783059,-1.189139,9.318996,6.103333,-33.641597,-13.707312,49.501661,15.553439,no,6115,1415,2054,1254,1392
0,2603,12,0.436297,0.408773,-1.782931e-04,-0.001370,5.490603,3.282911,12.544803,7.403100,-26.890700,-11.097553,44.230769,14.745487,no,6546,1519,2197,1337,1493
0,2603,13,0.435831,0.408283,-1.654504e-04,-0.001335,-4.125841,-2.321671,13.620072,7.378522,-7.659621,-3.112966,42.405063,15.060598,no,6966,1607,2329,1429,1601
0,2603,14,0.435031,0.408339,-1.818406e-04,-0.001310,3.096991,1.577694,8.243728,4.149407,-21.524042,-9.663566,45.161290,16.913386,no,7365,1704,2469,1500,1692
0,2603,15,0.435350,0.408997,-1.683419e-04,-0.001273,41.889652,18.211451,15.770609,7.253467,-3.289862,-1.480941,38.888889,15.779650,no,7734,1791,2588,1576,1779
0,2603,16,0.435466,0.409599,-1.730248e-04,-0.001243,45.108946,18.168968,-29.677419,-14.604001,-12.982422,-6.398064,122.772277,46.351820,no,8081,1869,2694,1650,1868
0,2603,17,0.435812,0.410224,-1.772816e-04,-0.001221,25.786224,10.150341,-24.014337,-10.928296,-14.856419,-7.876805,113.270142,47.161525,no,8405,1942,2792,1721,1950
0,2603,18,0.436890,0.411477,-1.703980e-04,-0.001197,-16.947540,-7.126057,-16.845878,-7.080815,-7.634298,-4.293784,98.237885,45.960295,no,8707,2022,2892,1782,2011
0,2603,19,0.438376,0.413197,-1.458715e-04,-0.001156,-17.636224,-7.058029,-20.788530,-8.416285,9.786332,5.705953,99.115044,50.580732,no,8990,2104,2988,1837,2061
0,2603,20,0.439494,0.414588,-1.268413e-04,-0.001124,-7.953548,-2.923042,-15.053763,-5.672826,6.461110,4.172151,84.426230,49.122190,no,9247,2177,3074,1887,2109
0,2603,21,0.440717,0.415726,-1.004468e-04,-0.001098,-33.123701,-12.819854,12.186380,3.999117,17.379942,12.192763,41.955836,28.599190,no,9480,2247,3158,1931,2144
0,2603,22,0.441349,0.416457,-7.881947e-05,-0.001073,-18.968884,-6.618955,6.093190,1.944400,14.696852,11.555359,51.006711,38.913305,no,9693,2318,3248,1960,2167
0,2603,23,0.442331,0.417238,-4.530098e-05,-0.001051,-9.574423,-3.086356,21.863799,6.352965,32.621840,28.813336,29.682997,26.250524,yes,9884,2372,3313,2000,2199
0,2603,24,0.443140,0.417818,-3.076544e-05,-0.001045,12.794976,3.660329,34.050179,9.143850,11.303961,11.595074,17.493473,17.956368,no,10051,2420,3372,2034,2225
0,2603,25,0.443943,0.418802,9.233525e-07,-0.001020,-41.232959,-14.135606,50.896057,12.518792,33.131336,40.743887,4.408353,5.287240,yes,10195,2468,3425,2058,2244
0,2603,26,0.444401,0.419803,1.577380e-05,-0.000987,-26.888738,-8.272628,31.899642,7.932567,13.325619,19.615637,28.205128,42.725282,no,10315,2510,3469,2074,2262
0,2603,27,0.445159,0.421061,3.919362e-05,-0.000944,-38.762527,-12.210213,24.014337,5.881669,30.039989,59.912407,25.000000,49.005011,yes,10412,2547,3502,2088,2275
0,2603,28,0.445345,0.421811,4.891404e-05,-0.000919,-32.073852,-9.429851,33.691756,7.719688,9.433295,23.900295,21.951220,60.285918,no,10484,2576,3531,2093,2284
0,2603,29,0.445320,0.421951,4.608354e-05,-0.000916,22.697624,5.173131,46.236559,9.824372,-3.676876,-12.616383,9.223301,37.383657,no,10534,2595,3555,2096,2288
0,2603,30,0.445265,0.421862,4.161481e-05,-0.000921,10.627996,2.437245,63.440860,12.426176,-6.715973,-39.380486,-1.960784,-13.288088,no,10560,2605,3570,2097,2288

2408 南亞科 tw tv1
Processing for date 20220103	 no news found in 20220102
Processing for date 20220104	 no news found in 20220103
Processing for date 20220105	 no news found in 20220104
Processing for date 20220106	 no news found in 20220105
Processing for date 20220107	20220106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220110	 no news found in 20220109
Processing for date 20220111	20220110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220112	20220111 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220113	20220112 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220114	20220113 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220117	20220116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220118	20220117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220119	 no news found in 20220118
Processing for date 20220120	20220119 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220121	 no news found in 20220120
Processing for date 20220124	 no news found in 20220123
Processing for date 20220125	20220124 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220126	 no news found in 20220125
Processing for date 20220207	 no news found in 20220206
Processing for date 20220208	 no news found in 20220207
Processing for date 20220209	 no news found in 20220208
Processing for date 20220210	 no news found in 20220209
Processing for date 20220211	 no news found in 20220210
Processing for date 20220214	 no news found in 20220213
Processing for date 20220215	 no news found in 20220214
Processing for date 20220216	20220215 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220217	20220216 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220218	20220217 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220221	 no news found in 20220220
Processing for date 20220222	20220221 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220223	20220222 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220224	 no news found in 20220223
Processing for date 20220225	20220224 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220301	 no news found in 20220228
Processing for date 20220302	 no news found in 20220301
Processing for date 20220303	20220302 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220304	20220303 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220307	20220306 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220308	20220307 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220309	 no news found in 20220308
Processing for date 20220310	20220309 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220311	20220310 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220314	 no news found in 20220313
Processing for date 20220315	 no news found in 20220314
Processing for date 20220316	20220315 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220317	20220316 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220318	20220317 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220321	 no news found in 20220320
Processing for date 20220322	20220321 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220323	20220322 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220324	20220323 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220325	20220324 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220328	 no news found in 20220327
Processing for date 20220329	20220328 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220330	 no news found in 20220329
Processing for date 20220331	20220330 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220401	 no news found in 20220331
Processing for date 20220406	20220405 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220407	20220406 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220408	20220407 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220411	20220410 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220412	20220411 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220413	20220412 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220414	20220413 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220415	20220414 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220418	 no news found in 20220417
Processing for date 20220419	20220418 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220420	 no news found in 20220419
Processing for date 20220421	 no news found in 20220420
Processing for date 20220422	20220421 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220425	 no news found in 20220424
Processing for date 20220426	 no news found in 20220425
Processing for date 20220427	 no news found in 20220426
Processing for date 20220428	20220427 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220429	 no news found in 20220428
Processing for date 20220503	 no news found in 20220502
Processing for date 20220504	 no news found in 20220503
Processing for date 20220505	20220504 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220506	 no news found in 20220505
Processing for date 20220509	 no news found in 20220508
Processing for date 20220510	 no news found in 20220509
Processing for date 20220511	 no news found in 20220510
Processing for date 20220512	20220511 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220513	20220512 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220516	 no news found in 20220515
Processing for date 20220517	20220516 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220518	20220517 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220519	 no news found in 20220518
Processing for date 20220520	20220519 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220523	20220522 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220524	20220523 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220525	20220524 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220526	20220525 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220527	20220526 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220530	 no news found in 20220529
Processing for date 20220531	 no news found in 20220530
Processing for date 20220601	20220531 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220602	 no news found in 20220601
Processing for date 20220606	 no news found in 20220605
Processing for date 20220607	20220606 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220608	 no news found in 20220607
Processing for date 20220609	20220608 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220610	20220609 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220613	20220612 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220614	20220613 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220615	20220614 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220616	20220615 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220617	20220616 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220620	20220619 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220621	 no news found in 20220620
Processing for date 20220622	20220621 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220623	20220622 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220624	20220623 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220627	20220626 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220628	20220627 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220629	20220628 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220630	20220629 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220701	 no news found in 20220630
Processing for date 20220704	 no news found in 20220703
Processing for date 20220705	20220704 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220706	20220705 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220707	20220706 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220708	20220707 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220711	 no news found in 20220710
Processing for date 20220712	20220711 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220713	20220712 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220714	 no news found in 20220713
Processing for date 20220715	20220714 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220718	 no news found in 20220717
Processing for date 20220719	 no news found in 20220718
Processing for date 20220720	 no news found in 20220719
Processing for date 20220721	 no news found in 20220720
Processing for date 20220722	20220721 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220725	 no news found in 20220724
Processing for date 20220726	20220725 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220727	20220726 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220728	 no news found in 20220727
Processing for date 20220729	 no news found in 20220728
Processing for date 20220801	 no news found in 20220731
Processing for date 20220802	 no news found in 20220801
Processing for date 20220803	20220802 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220804	20220803 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220805	 no news found in 20220804
Processing for date 20220808	20220807 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220809	 no news found in 20220808
Processing for date 20220810	20220809 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220811	20220810 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220812	20220811 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220815	 no news found in 20220814
Processing for date 20220816	 no news found in 20220815
Processing for date 20220817	 no news found in 20220816
Processing for date 20220818	20220817 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220819	20220818 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220822	 no news found in 20220821
Processing for date 20220823	20220822 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220824	 no news found in 20220823
Processing for date 20220825	20220824 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220826	 no news found in 20220825
Processing for date 20220829	20220828 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220830	20220829 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220831	 no news found in 20220830
Processing for date 20220901	20220831 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220902	20220901 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220905	20220904 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220906	20220905 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220907	20220906 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220908	20220907 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220912	 no news found in 20220911
Processing for date 20220913	 no news found in 20220912
Processing for date 20220914	 no news found in 20220913
Processing for date 20220915	 no news found in 20220914
Processing for date 20220916	20220915 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220919	 no news found in 20220918
Processing for date 20220920	20220919 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220921	20220920 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220922	 no news found in 20220921
Processing for date 20220923	20220922 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220926	 no news found in 20220925
Processing for date 20220927	20220926 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220928	20220927 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220929	20220928 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20220930	 no news found in 20220929
Processing for date 20221003	 no news found in 20221002
Processing for date 20221004	20221003 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221005	20221004 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221006	20221005 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221007	20221006 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221011	 no news found in 20221010
Processing for date 20221012	20221011 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221013	20221012 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221014	20221013 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221017	20221016 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221018	20221017 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221019	20221018 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221020	20221019 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221021	20221020 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221024	20221023 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221025	20221024 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221026	 no news found in 20221025
Processing for date 20221027	20221026 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221028	20221027 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221031	 no news found in 20221030
Processing for date 20221101	20221031 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221102	20221101 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221103	20221102 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221104	20221103 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221107	20221106 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221108	 no news found in 20221107
Processing for date 20221109	20221108 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221110	20221109 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221111	20221110 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221114	 no news found in 20221113
Processing for date 20221115	20221114 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221116	 no news found in 20221115
Processing for date 20221117	20221116 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221118	20221117 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221121	 no news found in 20221120
Processing for date 20221122	20221121 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']
Processing for date 20221123	20221122 news found
Ungenerated list ['9', '10', '11', '12', '13', '14', '15', '16']

,stock_id,tv,accuracy,precision,ev,precision_ev,Train_RTN,Ann_Train_RTN,Train_B&H,Ann_Train_B&H,RTN,Ann_RTN,B&H,Ann_B&H,win B&H,avail_count,tp,fp,tn,fn
0,2408,1,0.475564,0.410326,-0.000085,-0.002539,0.531784,5.983224,-5.511811,-46.269199,-12.296235,-3.076791,-61.714660,-20.441884,yes,532,151,217,102,62
0,2408,2,0.473884,0.404795,-0.000196,-0.002708,1.131992,4.324623,-0.787402,-2.929524,-21.799806,-5.877506,-61.360634,-20.882726,yes,1053,287,422,212,132
0,2408,3,0.469191,0.402647,-0.000303,-0.002722,11.538411,30.968333,-16.141732,-35.268843,-29.335963,-8.475694,-54.153605,-18.038055,yes,1558,426,632,305,195
0,2408,4,0.467349,0.401862,-0.000285,-0.002686,11.923230,23.022534,-12.335958,-21.508084,-16.403883,-4.627357,-55.948795,-19.489518,yes,2052,561,835,398,258
0,2408,5,0.468960,0.403519,-0.000198,-0.002592,7.856929,11.718788,-22.703412,-31.428781,0.914850,0.250306,-51.086957,-17.824183,yes,2529,688,1017,498,326
0,2408,6,0.471180,0.404654,-0.000127,-0.002550,-0.027543,-0.033529,-31.364829,-36.756864,4.864464,1.364793,-43.965517,-15.235989,yes,2984,800,1177,606,401
0,2408,7,0.473638,0.405598,-0.000016,-0.002485,-0.701672,-0.730560,-31.627297,-32.693079,25.005178,6.857270,-42.759295,-15.277799,yes,3433,913,1338,713,469
0,2408,8,0.474528,0.404942,0.000022,-0.002476,0.929860,0.845583,-34.120735,-31.591958,7.054922,2.138216,-41.206030,-15.196530,yes,3867,1016,1493,819,539
0,2408,9,0.473697,0.403515,-0.000013,-0.002530,22.814755,17.869228,-21.391076,-17.514525,-19.177757,-6.672416,-51.005025,-20.657002,yes,4277,1125,1663,901,588
0,2408,10,0.473042,0.401771,-0.000048,-0.002593,29.803786,20.660994,-29.527559,-22.272642,-23.523670,-8.705809,-43.750000,-17.749991,yes,4674,1225,1824,986,639
0,2408,11,0.473518,0.400790,-0.000060,-0.002639,19.804303,12.765672,-24.278215,-16.882396,-13.344870,-5.018749,-51.492537,-22.900345,yes,5060,1319,1972,1077,692
0,2408,12,0.473346,0.399435,-0.000073,-0.002677,31.089108,17.773464,-23.359580,-14.851700,-15.502085,-6.130098,-48.952880,-22.316996,yes,5440,1414,2126,1161,739
0,2408,13,0.473702,0.398570,-0.000077,-0.002709,14.578550,7.882601,-12.729659,-7.310218,-12.551456,-5.183376,-55.948795,-27.772180,yes,5799,1505,2271,1242,781
0,2408,14,0.474455,0.397793,-0.000067,-0.002740,26.426299,12.789031,-15.091864,-8.053741,-2.352129,-0.993071,-54.439252,-28.080486,yes,6146,1586,2401,1330,829
0,2408,15,0.474676,0.396950,-0.000081,-0.002787,28.647352,12.801044,0.000000,0.000000,-14.542304,-6.769112,-61.155378,-34.410501,yes,6476,1666,2531,1408,871
0,2408,16,0.474886,0.396080,-0.000104,-0.002840,41.240380,16.745822,-7.611549,-3.487621,-21.326801,-10.778690,-58.392603,-34.093785,yes,6789,1738,2650,1486,915
0,2408,17,0.475653,0.395665,-0.000114,-0.002882,32.898509,12.733230,-14.304462,-6.298126,-14.516235,-7.689228,-55.000000,-33.457937,yes,7085,1807,2760,1563,955
0,2408,18,0.475835,0.394414,-0.000123,-0.002938,31.033034,11.360147,-13.910761,-5.788728,-14.259134,-8.150350,-56.730769,-37.057915,yes,7366,1864,2862,1641,999
0,2408,19,0.476097,0.393406,-0.000143,-0.002997,30.998500,10.723089,-13.910761,-5.493919,-21.273686,-13.251904,-55.748865,-38.403101,yes,7635,1921,2962,1714,1038
0,2408,20,0.476209,0.391981,-0.000148,-0.003058,30.582396,10.022480,-5.380577,-1.960286,-10.528404,-7.005410,-59.487535,-44.561130,yes,7881,1965,3048,1788,1080
0,2408,21,0.477113,0.391584,-0.000109,-0.003076,10.157194,3.353799,-9.711286,-3.423613,23.206695,16.163793,-59.090909,-47.361132,yes,8105,2010,3123,1857,1115
0,2408,22,0.478345,0.391404,-0.000093,-0.003112,8.469586,2.682308,-13.517060,-4.618153,6.078254,4.818083,-56.081081,-48.116891,yes,8312,2049,3186,1927,1150
0,2408,23,0.479934,0.391419,-0.000054,-0.003131,12.706665,3.796348,-8.661417,-2.782606,32.205182,28.450350,-57.299270,-53.379661,yes,8497,2080,3234,1998,1185
0,2408,24,0.480776,0.391054,-0.000028,-0.003153,1.191606,0.354311,-13.779528,-4.330243,20.399649,20.946050,-56.666667,-57.541553,yes,8661,2107,3281,2057,1216
0,2408,25,0.482108,0.391033,0.000019,-0.003155,-12.120041,-3.636223,-15.354331,-4.666608,45.071552,55.947982,-54.439252,-60.893345,yes,8803,2128,3314,2116,1245
0,2408,26,0.483242,0.390805,0.000045,-0.003187,-13.314992,-3.863022,-3.018373,-0.841457,22.687932,34.013360,-60.738255,-73.779662,yes,8921,2142,3339,2169,1271
0,2408,27,0.484472,0.390855,0.000072,-0.003201,0.061418,0.016305,-33.070866,-10.113723,23.838321,46.539166,-44.811321,-65.435878,yes,9016,2154,3357,2214,1291
0,2408,28,0.485802,0.391069,0.000107,-0.003207,-3.040227,-0.787558,-39.238845,-11.978827,36.496905,109.524756,-37.231760,-66.951225,yes,9086,2163,3368,2251,1304
0,2408,29,0.486424,0.390732,0.000127,-0.003218,7.311570,1.755217,-41.469816,-12.372259,19.141431,87.856456,-33.823529,-77.377898,yes,9134,2167,3379,2276,1312
0,2408,30,0.486844,0.390678,0.000150,-0.003213,9.664627,2.223864,-52.362205,-16.204584,24.905365,395.888301,-18.296089,-76.657440,yes,9159,2171,3386,2288,1314

    tv Ann_Train_RTN Ann_Train_B&H Ann_Test_RTN Ann_Test_B&H  Win B&H     Diff
0    1        95.09%        -0.21%       11.54%        8.70%     True    7.55%
1    2        36.31%        -0.05%       12.95%        9.40%     True   12.22%
2    3        29.66%        -7.58%       10.65%       11.01%    False  -12.69%
3    4        24.68%       -15.35%       12.19%       12.97%    False  -16.08%
4    5        20.94%       -16.88%       11.13%       14.71%    False  -29.46%
5    6        18.70%       -19.17%       15.93%       17.55%    False  -22.81%
6    7        15.12%       -17.84%       14.67%       18.48%    False  -29.32%
7    8        15.75%       -15.57%       16.64%       20.55%    False  -30.44%
8    9        18.21%       -11.70%       16.96%       18.58%    False  -17.18%
9   10        16.13%       -10.46%       16.91%       20.71%    False  -24.75%
10  11        16.35%        -8.62%       17.28%       19.43%    False  -17.90%
11  12        16.94%        -6.26%       16.60%       19.58%    False  -17.53%
12  13        17.22%        -2.41%       16.47%       18.59%    False  -12.95%
13  14        17.36%        -1.08%       18.26%       18.62%    False   -6.12%
14  15        21.35%         6.93%       20.09%       11.27%     True   25.11%
15  16        22.26%         8.60%       16.25%       11.57%     True   10.74%
16  17        22.69%         8.84%       17.67%       13.41%     True   11.23%
17  18        20.04%         6.78%       21.39%       13.88%     True   16.79%
18  19        18.47%         5.37%       23.35%       16.73%     True   13.13%
19  20        16.61%         7.27%       23.58%       14.77%     True   15.18%
20  21        15.97%         8.11%       30.15%       14.28%     True   24.02%
21  22        15.46%         9.17%       35.89%       13.28%     True   30.56%
22  23        16.51%        10.72%       39.58%        6.65%     True   37.68%
23  24        16.95%         9.25%       35.52%        8.08%     True   26.65%
24  25        13.43%        10.40%       56.34%        2.80%     True   42.14%
25  26        14.89%        11.79%       68.81%       -3.51%     True   42.72%
26  27        17.75%         8.16%       49.57%       11.98%     True   15.70%
27  28        17.70%         7.93%       65.32%       19.40%     True   12.63%
28  29        20.63%         9.29%       53.97%       18.75%     True    9.72%
29  30        19.34%         9.00%      152.27%       92.50%     True    5.53%

# Reserch

In [ ]:
# from TV_usable_dt_stock import TV_UsableFactorDT
# import pandas as pd

# ttl_indiv = [0] * 8

# for stock in data:
#     for date_range in data_range_tv:
#         env = {
#             "stock_id" : stock[0],
#             "stock_name" : stock[1],
#             "country" : stock[2],
#             "start_date" : date_range[0],
#             "end_date" : date_range[1],
#             "tv" : date_range[2],
#             "run_count" : str(1)
#         }
#         print(env['stock_id'], env['stock_name'], env['country'], f"tv{date_range[2]}")

#         eval_module = TV_UsableFactorDT(env)
#         indiv, text = eval_module.get_individual_with_factors(1)

#         for idx, e in enumerate(indiv):
#             if idx >= 8:
#                 print("len > 8", indiv)
#                 break
#             if e == 1:
#                 ttl_indiv[idx] += 1
                
# print(ttl_indiv)

In [ ]:
# def calculate_cagr(total_return: float, years: int) -> float:
#     """
#     計算年化報酬率（CAGR）
#     :param total_return: 總報酬率（以小數表示，例如 180.74% = 1.8074）
#     :param years: 投資期間（年數）
#     :return: 年化報酬率（CAGR，以小數表示）
#     """
#     return (1 + total_return) ** (1 / years) - 1

# # 三年的數據
# rtn_total = 1.8074  # 180.74% 轉換為小數
# bh_total = 0.2644  # 26.44% 轉換為小數
# years = 3

# # 計算年化報酬率
# rtn_cagr = calculate_cagr(rtn_total, years)
# bh_cagr = calculate_cagr(bh_total, years)

# print(f"策略年化報酬率 (CAGR): {rtn_cagr:.2%}")
# print(f"B&H 年化報酬率 (CAGR): {bh_cagr:.2%}")

# Danger Zone

In [11]:
# # Delete folders named in the directory tree
# import os
# import shutil

# # Set the root directory for the project
# root_dir = r"/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Training_result/FactorUsableDT"

# # Walk the directory tree and delete folders named 
# for dirpath, dirnames, filenames in os.walk(root_dir, topdown=False):
#     for dirname in dirnames:
#         if dirname.lower() == "2379":
#             full_path = os.path.join(dirpath, dirname)
#             print(f"Deleting folder: {full_path}")
#             shutil.rmtree(full_path)

In [12]:
# # 合併 Usable 跟 F42 變成 F24
# import json
# import os

# new_expands = {}

# for stock in data:
#     exp2_exist = False
#     print(f"stock: {stock[0]}")
#     if not os.path.exists(f"out_stock/Expands/F42/{stock[0]}/expand.json"):
#         print(f"{stock[0]} Not exist")
#         continue
    
#     with open(f"out_stock/Expands/F42/{stock[0]}/expand.json", "r") as f:
#         expand = json.load(f)
#     new_expands["model"] = expand["model"]
#     new_expands["temperature"] = expand["temperature"]
#     new_expands["stock_id"] = expand["stock_id"]
#     new_expands["output_data"] = {}
    
#     if os.path.exists(f"out_stock/Expands/FactorUsable/{stock[0]}/expand.json"):
#         exp2_exist = True
#         with open(f"out_stock/Expands/FactorUsable/{stock[0]}/expand.json", "r") as f:
#             expand2 = json.load(f)
    
#     date = expand["output_data"].keys()
#     for d in date:
#         # print(d)
#         new_expands["output_data"][d] = {"skeleton": {}}  # Ensure the structure exists

#         if exp2_exist:
#             # print("usable exist")
#             factors2 = expand2["output_data"][d]["skeleton"].keys()
#             for factor in factors2:
#                 new_expands["output_data"][d]["skeleton"][factor] = expand2["output_data"][d]['skeleton'][factor]
#         else:
#             print("usable not exist")
        
#         factors = expand["output_data"][d]["skeleton"].keys()
#         for factor in factors:
#             new_factor = str(int(factor) + 8)
#             if int(new_factor) > 24:
#                 continue
#             new_expands["output_data"][d]["skeleton"][new_factor] = expand["output_data"][d]['skeleton'][factor]


#     # print(new_expands["output_data"]["20230403"]['skeleton'])
#     os.makedirs(f"out_stock/Expands/F24/{stock[0]}", exist_ok=True)
#     with open(f"out_stock/Expands/F24/{stock[0]}/expand.json", "w") as f:
#         json.dump(new_expands, f, indent=4)
#     # break

In [ ]:
# # rename path1 to path2
# import os

# for stock in data:
#     path1 = f"/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Expands/FactorUsable/{stock[0]}/expand.json"
#     path2 = f"/Users/yanyifu/Documents/_Coding/LLM Predict Stock/run_factor/out_stock/Expands/UsableExp/{stock[0]}_expand.json"


#     os.rename(path1, path2)